### ISSUE TITLE
Icono e identidad de  - Obelisco

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#10]
Armar la imagen e identidad del icono de Obelisco  [https://drive.google.com/file/d/1ZTq4aGK7q313wL7magDbPxKY2fXJTWzL/view?usp=sharing](url)

**Comment by Jinik** [comment]
Holis, vengo a compartir una idea.

Desde mi punto de vista, el Proyecto Obelisco integra los estándares, el sistema de componentes y el sistema de íconos, sumando cualquier pauta o recurso que se estandarice a futuro para interfaces conversacionales, realidad virtual o todas las cosas que se nos imaginemos.

Para los productos en sí, como el sistema de componentes o íconos, creo que deberíamos armar identidades individuales que sean más identificables y "únicas".

El otro día estaba rumiando esta idea y se me ocurrió como ejemplo jugar con las palabras Buenos Aires y el famoso baires, para armar **Baire** como nombre para el sistema de componentes y **Baico** como nombre para los íconos.
Esto lo podríamos extender a **Baimo** para aplicaciones móviles, **Baira** para realidad aumentada y así.
Además del nombre, cada producto podría tener un logo-iso-imago-tipo.

Para seguir jugando con la identidad y lo autóctono, cada uno de estos productos va a ir avanzando en versiones, por lo que también podemos asignarle un nombre a cada una. Esto es algo común, como por ejemplo Android tiene nombres de postres, Mac OS tuvo felinos en su momento y ahora pasó a montañas, y wordpress tiene nombres de músicos de jazz.

Para esto podríamos usar nombres de vegetación o animales autóctonos de la ciudad, barrios, apellidos comunes, nombres de avenidas, palabras del lunfardo, comidas (cómo olvidar al [milanesat](https://en.wikipedia.org/wiki/%C3%91uSat)) y un muy largo etcétera. Cada producto podría tener una categoría diferente.

Más allá de los nombres, que son solo ejemplos, me interesan opiniones sobre ponerle uno a cada producto y el tema de las versiones.

**Comment by aloyber** [comment]
Hola Nico,

me gusta el juego de palabras que empieza a surgir con la idea de Baires y los diferentes usos que puede tener pero me parece que a simple vista no es tan identificable **"Baico"** como Iconos. Además que Baico puede llegar a confundirse con "co" de Componentes. Me parece que el hecho de nombrar las cosas como son esta bién y no necesita algo extra, talvez lo mantendría como está.

En cuanto a las versiones podemos agregar "el nombre asignado" siempre que mantengamos el "nro de versión" visible, me parece que asi puede funcionar

Dejo abierto el debate..
Saludoss

**Comment by nirougi** [comment]
Sip, el juego de palabras era solo un ejemplo.

Respecto a las versiones, la idea es seguir el [versionado semántico](https://semver.org/) para el número que hoy en día ya es un estándar. Por lo general se le pone nombre a cada versión principal, las definidas por el primer número.

**Comment by Vpappacena** [comment]
https://dribbble.com/shots/14732282-Conoc-Obelisco  - Icono de obelisco
