### ISSUE TITLE
Menú sticky en home Obelisco

### ISSUE THREAD

**Issue by techlowiec** [gcba/estandares#101]
¿Es posible que el contenido del menú acompañe el scroll efectuado en la página?

@nirougi @Vpappacena

**Comment by nirougi** [comment]
Sí es posible, habría que definir bien el comportamiento antes de implementarlo:

1. ¿El acompañamiento sería de todo el sidebar o solamente el menú? ¿El logo debería también quedar siempre visible arriba?
2. ¿Qué pasa si el contenido del sidebar es mayor al alto del navegador? ¿Se agrega una barra de scroll independiente para el sidebar?

**Comment by mathiassassone1** [comment]
@nirougi @techlowiec 

Como referencia y respuesta a esas preguntas, tomamos como concepto la idea que plantean acá.

https://spectrum.adobe.com/

**Comment by nirougi** [comment]
Ok. Esto sería solamente para la web de estándares, no? No estamos pensando que sea un feature general de Obelisco.

**Comment by nirougi** [comment]
@mathiassassone1

**Comment by mathiassassone1** [comment]
@nirougi

Esa funcionalidad debe estar en el componente, tanto para la web de como para todo Obelisco, ya que ese componente esta dentro de Obelisco.
