### ISSUE TITLE
Uso del Ghost button

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#102]

**Comment by aloyber** [comment]
Subo lo que se trabajo de los Botones Fantasmas agregándolos al UI KIT.
Estos botones se pueden utilizar para generar una acción secundaria en un nivel de jerarquía inferior al botón primario/secundario. También se pueden utilizar dentro de tablas y/o tarjetas.
También se modificaron el componente maestro de los botones pequeños y se le asigno a cada botón sus correspondientes estados.

![Botones](https://user-images.githubusercontent.com/65788688/107379484-ba36f000-6acb-11eb-80af-70ebc006213c.png)

@Vpappacena
