### ISSUE TITLE
Cambiar tamaños tipográficos

### ISSUE THREAD

**Issue by aloyber** [gcba/estandares#106]

**Comment by aloyber** [comment]
Cambios en tamaños tipográficos:
- Se modificaron los headings
- Se agrego H5
- Se quito Subtitulo 2 y se modifico el Subtitulo 1

![Tipografía](https://user-images.githubusercontent.com/65788688/108251904-c6a7f200-7136-11eb-8be4-7f2844628be7.png)

**Comment by Vpappacena** [comment]
@nirougi @techlowiec @armenio-s
