### ISSUE TITLE
Paleta de colores

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#11]
- Construir una paleta de colores que cumple con las pautas de accesibilidad (niveles de contraste)

**Comment by aloyber** [comment]
**Ajustar la paleta para que cada color siga su línea de HSB**

Colores a ajustar: 

- [ ] Rojo 

- [ ] Verde

- [ ] Azul

Colores para agregar: 

- [ ] Naranja (alertas)

_PD: Los colores de los estados en los botones se pueden ver afectados, por ejemplo el Rojo 60 (hover en botón)_

@Fcunsolo @mathiassassone1

**Comment by aloyber** [comment]
Adjunto la primer versión de la paleta de colores

[PALETA DE COLORES.pdf](https://github.com/gcba/estandares/files/4833627/PALETA.DE.COLORES.pdf)
@Vpappacena

**Comment by aloyber** [comment]
Agregar:

- [ ] Gama de 3 colores para la paleta de Buenos Aires

**Comment by Vpappacena** [comment]
> Agregar:
> 
> * [ ] Gama de 3 colores para la paleta de Buenos Aires 
>   @aloyber

@aloyber , esta Gama esta subida ?

**Comment by mathiassassone1** [comment]
@techlowiec @lautarorodriguez96 @nirougi

Agregamos un color a la paleta de colores en la sección PALETA EN BUENOS AIRES. 

Color: #009AFD

[Paleta de colores.pdf](https://github.com/gcba/estandares/files/5312840/Paleta.de.colores.pdf)

**Comment by Vpappacena** [comment]
@mathiassassone1 @aloyber @Fcunsolo  , queda pendiente  revisar la propuesta de Paleta de colores de "Detalles cromáticos" para la sección de colores de guía de estilos

**Comment by Vpappacena** [comment]
@mathiassassone1 @aloyber @Fcunsolo , queda pendiente revisar la propuesta de Paleta de colores de "Detalles cromáticos" para la sección de colores de guía de estilos

**Comment by mathiassassone1** [comment]
@nirougi @techlowiec @lautarorodriguez96 @Vpappacena 

Comparto propuesta final de "Detalles cromáticos".

Se realizó un cambio de color, el #038ED9 por el #FFDB2E.

Además se agregaron 2 colores, #E6EBF0 y #D1D8E0.

Dejo link al Ui Kit, en donde los pueden encontrar en Colores.

https://xd.adobe.com/view/c5e691f2-0643-4e9e-a769-f2252af77984-90b5/

**Comment by Vpappacena** [comment]
Agregar colores nuevos , @mathiassassone1 @aloyber @SantiBugdadi , ajustar la ficha de adobe para poder materializar en obelisco

**Comment by aloyber** [comment]
Ajustes de paleta crómatica.
Objetivos: 
- Estandarizar y dar consistencia, en cuanto a ajustes de los niveles de saturación, tonos y accesibilidad web.
- Definir la paleta primaria. ¿El amarillo es el color principal? Trabajar sobre esto.
- Definir la paleta secundaria
- Ajustar paleta semántica/sistema


Dos propuestas de trabajo para ver el 07/01/2022

- [ ] Propuesta 1: Ajustar saturación de grisulados y colores semánticos; definir una nueva paleta secundaria consistente y sólida para aplicar en los recursos y componentes de obelisco; definir el color azul/celeste como principal.
- [ ] Propuesta 2: Mantener saturación, definir una nueva paleta secundaria consistente y sólida para aplicar en los recursos y componentes de obelisco; mantener el color amarillo como principal.

A partir de estas dos propuestas, aplicar lo trabajo a una propuesta real donde se puedan visualizar los diferentes estilos y tomar una desición en base a lo trabajado.

@mathiassassone1 @Vpappacena
