### ISSUE TITLE
Patrones de Formulario

### ISSUE THREAD

**Issue by aloyber** [gcba/estandares#110]

**Comment by aloyber** [comment]
Encontre este formulario que te va agregando a medida que completas los pasos como una especie de bloque a la derecha con los campos que seleccionaste. En este caso tampoco haría siempre falta un último paso de confirmación con todo el resumen sino que lo verías siempre al costado...

Lo divide en Pasos arriba de todo con la opcion de volver al paso anterior.

Es re estetico y funcional.

Cuando te da la confirmación, te recuerda los próximos turnos/tramites/inscripciones (podría ser lo que querramos). Y te da un detalle de todo lo que cargaste.

Los que desarrollaron tienen esta web https://es.fresha.com/ (también hay versión app). Es como una especie de template que se puede adecuar a cada tipo de negocio.

![1](https://user-images.githubusercontent.com/65788688/109683493-29998000-7b5e-11eb-8994-33b7ca9f9f4b.png)
![2](https://user-images.githubusercontent.com/65788688/109683500-2acaad00-7b5e-11eb-9457-c81094091f54.png)
![3](https://user-images.githubusercontent.com/65788688/109683503-2b634380-7b5e-11eb-895e-1b126a0d61e4.png)
![4](https://user-images.githubusercontent.com/65788688/109683514-2d2d0700-7b5e-11eb-989f-4ad34b394213.png)
![5](https://user-images.githubusercontent.com/65788688/109683516-2dc59d80-7b5e-11eb-8313-81637cf6114e.png)

**Comment by aloyber** [comment]
Trabajando en el portal de pagos comenzamos a generar una propuesta visual para lo que son formularios. Comienza con un "Paso a paso" (stepper) que contiene:
- Título del paso en el que se encuentra la persona
- Muestra el nombre del paso siguiente
- Componente visual de cuantos pasos hay que completar

A su vez el formulario en si está conformado por diferentes bloques de información los cuales contienen el contenido a completar para avanzar en los pasos. También se agrego un bloque a la derecha con un detalle (en este caso del pago total que tiene que realizar con el detalle de las boletas a pagar).

@Vpappacena

![Web 1366 – 27](https://user-images.githubusercontent.com/65788688/111199548-843fcc80-859f-11eb-8f42-c6ddbaf2c4ae.png)
![Web 1366 – 30](https://user-images.githubusercontent.com/65788688/111199558-86a22680-859f-11eb-80dc-10b87f136432.png)

**Comment by Vpappacena** [comment]
Se modificaron los estados de todos los controles . 
queda pendiente revisar placeholder y label @mathiassassone1  @aloyber  @Fcunsolo  , antes de pasar a desarrollo
