### ISSUE TITLE
Mensajes de sistema

### ISSUE THREAD

**Issue by mathiassassone1** [gcba/estandares#113]
- Empezar a pensar conceptualmente si una alerta debería ser de sistema o de accion frente al usuario.
- Si debería llevar un botón ? cuales son las acciones de una alerta?
- Cual es el concepto de alerta ? un modal o un aviso o una notificación? como se diferencia ?
- Construir una ficha detallando comportamiento y uso del componente dentro de una pagina

**Comment by Vpappacena** [comment]
@mathiassassone1 , en que quedo  esto ? lo resolvimos entro issue con las nuevas alertaS?

**Comment by mathiassassone1** [comment]
Si esta resuelta la diferenciación entre alerta y modal.
