### ISSUE TITLE
Ficha de Modal, Paginado y Paso a paso.

### ISSUE THREAD

**Issue by mathiassassone1** [gcba/estandares#114]
@nirougi @techlowiec @lautarorodriguez96 @armenio-s 

Agregamos 3 fichas mas a las existentes 

https://xd.adobe.com/view/b15aa7bf-9779-43ac-a85b-9d818c499c23-e409/

**Comment by Vpappacena** [comment]
@mathiassassone1  , esta tarea ya esta para cerrar ?
