### ISSUE TITLE
desplegables (selector de perfil )

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#123]
Componente desplegables (selector de perfil )
Tomar como referencia  la propuesta del pago que fue testeados con usuario

para  pulir componente y armar ficha.

- [x] armar componente para ui kit
- [x] tener el documentos de comportamiento
- [x] armar ficha

**Comment by Vpappacena** [comment]
@aloyber  sumar el material de la propuesta de pago de referencia para empezar a trabajar

**Comment by aloyber** [comment]
![Desplegable de opciones](https://user-images.githubusercontent.com/65788688/115917842-1f547d80-a44d-11eb-9ce0-0c5528b47c57.png)

@SantiBugdadi

**Comment by Vpappacena** [comment]
@aloyber @SantiBugdadi  , queda pendiente revisar la ficha y las definiciones de comportamiento antes de cerrar el componente

**Comment by Vpappacena** [comment]
@SantiBugdadi  se avanzo con las fichas ?

**Comment by SantiBugdadi** [comment]
Están terminadas todas las fichas nuevas! Solo queda pendiente revisarlos para ver si son correctos lo que se dice en Usabilidad (tanto desplegables como accesos)
