### ISSUE TITLE
Accesos - Menu

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#124]
Tomando como propuesta de home / perfil que se uso en el proyecto de pagos -  en base a lo que salió en al pruebas  pulir el componente y luego la ficha técnica.

- [x] armar componente para ui kit
- [x] tener el documentos de comportamiento
- [x] armar ficha

**Comment by Vpappacena** [comment]
@aloyber sumar el material de la propuesta de pago de referencia para empezar a trabajar

**Comment by aloyber** [comment]
![Accesos](https://user-images.githubusercontent.com/65788688/115918099-778b7f80-a44d-11eb-8b72-17bd14c6644f.png)
@SantiBugdadi

**Comment by Vpappacena** [comment]
@aloyber @SantiBugdadi , queda pendiente revisar la ficha y las definiciones de comportamiento antes de cerrar el componente

**Comment by Vpappacena** [comment]
@SantiBugdadi  se avanzo con las fichas ?
