### ISSUE TITLE
Definir la nueva grilla para trabajar

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#13]
- Definir el estándar de la primera versión de grilla para el uso en productos digitales

**Comment by ghoyos95** [comment]
@mathiassassone1 te subis el doc para la puesta en comun con vani y cerrar la tarjeta?

**Comment by mathiassassone1** [comment]
Dejo avances de grilla.

[Grilla.pdf](https://github.com/gcba/estandares/files/4881213/Grilla.pdf)

@Vpappacena @ghoyos95 @aloyber @Fcunsolo @techlowiec

**Comment by Jinik** [comment]
Una consulta respecto a esto, entiendo que el ancho de la columna en computadoras o tables va a estar definido por un múltiplo de de 8px, ¿no?

¿Cómo sería el caso para los teléfonos? ¿El ancho también va a estar definido por un múltiplo dejando el margen necesario  para ajustarse o de va a definir un medianil y margen fijo para el la columna tome el espacio disponible?

**Comment by mathiassassone1** [comment]
@nirougi 

Sí, va a estar definido por un múltiplo de 4. El medianil, en todos los casos es de 16 px. En Mobile se respeta un margen de 16 px tanto izquierdo como derecho, con 4 columnas, por lo tanto en Mobile quedaría definido un margen de 16 px y una separación de 16 px para las 4 columnas, esto hace que nos fije un espacio de trabajo, y con los breakpoints que determinamos se adapten los contenidos.

**Comment by nirougi** [comment]
Bien, simplemente tendría en cuenta que el ancho de las columnas difícilmente sea de múltiplos de 8px, más que nada para evitar definir elementos o contenidos que requieran ser pixel perfect.

Estos serían los tamaños de columna para las resoluciones más comunes, teniendo en cuenta que hay 16px de espacio a los costados y 16px entre las 4 columnas:

**Android**
|Ancho del navegador|Ancho de columna|
|---|---|
|320px | 60px |
|360px | 70px |
|412px | 83px |
|480px | 100px |

**iPhone**
|Ancho del navegador|Ancho de columna|
|---|---|
|375px | 73.75px |
|414px | 83.5px |

**Comment by mathiassassone1** [comment]
@nirougi 

Estas serian las medidas.

Web 1366 x 768
Área = (Columnas) + (Medianil) + (Margenes)
1120 = (76 px * 12) + (16 px * 11) + (16 px + 16 px)

Tablet 768 x 1024
Área = (Columnas) + (Medianil) + (Margenes)
640 = (62 px * 8) + (16 px * 7) + (16 px + 16 px)

Mobile 360 x 640
Área = (Columnas) + (Medianil) + (Margenes)
360 = (70 px * 4) + (16 px * 3) + (16 px +16 px)
