### ISSUE TITLE
Agenda

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#148]
### Discussed in https://github.com/gcba/estandares/discussions/147

<div type='discussions-op-text'>

<sup>Originally posted by **Vpappacena** November  1, 2021</sup>
Necesidad de crear una sección de agenda que responda a las diferentes áreas.

El objetivo es que las personas puedan visualizar los eventos calendarizados. 

Por ahora detectamos los siguientes casos:
- Eventos con o sin inscripción
- Talleres o actividades: puede o no requerir inscripción.
- Calendario de actividades: pueden o no requerir inscripción (sea por teléfono, mail o digitalmente)
</div>

**Comment by aloyber** [comment]
Diferenciar "transacción" vs "eventos, talleres y actividades dinámicas" lo duro vs lo blando. 
Hipótesis: La transacción podemos encontrarla en por ejemplo: la inscripción a un curso prolongado en el tiempo que tiene cupos y una fecha máxima. Y la inscripción a una actividad puede ser por ejemplo: una actividad deportiva/recreativa en una plaza sin fecha límite. Lo que es transacción ¿Aparecería en la parte de trámites/servicios y no en la agenda/calendario? sino 

- [ ] Hacer un análisis de los diferentes tipos de programación que existen en BA a nivel calendario
- [ ] Relevar los diferentes comportamientos para inscripción o asistencia de un evento, taller o actividad
- [ ] Agrupar y definir categorías de los diferentes tipos de eventos
- [ ] Realizar propuesta en base a necesidades relevadas


Adjunto algunas referencias visuales de lo que encontramos. Se pueden seguir subiendo a medida que vayamos encontrando mas casos. 

![screencapture-buenosaires-gob-ar-jefaturadegabinete-movilidad-semana-de-la-movilidad-sustentable-2021-2021-11-02-16_25_30](https://user-images.githubusercontent.com/65788688/139943812-dc0e2cdf-6366-4a8a-9791-bf826aabd516.png)
![screencapture-buenosaires-gob-ar-desarrollohumanoyhabitat-personas-mayores-talleres-distancia-2021-11-02-16_24_18](https://user-images.githubusercontent.com/65788688/139943824-2ff8aa6a-00da-48bf-8e7d-2dd98acf72b1.png)
![screencapture-portalinscripciones-scp-buenosaires-gob-ar-2021-11-02-16_55_06](https://user-images.githubusercontent.com/65788688/139943826-dc2313aa-5930-48cf-a24b-9abf58ee3c9a.png)
![screencapture-buenosaires-gob-ar-museocasacarlosgardel-visitas-guiadas-2021-11-02-16_30_27](https://user-images.githubusercontent.com/65788688/139943827-120d0fb7-4410-4fc2-9fb8-0babd9117665.png)

**Comment by aloyber** [comment]
Adjunto propuesta de página sobre cómo sería la página informativa sobre el "evento, taller o actividad" antes de realizar la inscripción (tanto sea telefónicamente, por mail o digital)

![Home – Servicios - Tránsito y movilidad - Licencia de conducir - Otorgamiento – 1](https://user-images.githubusercontent.com/65788688/139947324-bff9a3fd-735d-4465-8e37-1195c0be5ecd.png)

![Home – Servicios - Salud - Personas mayores - Talleres a distancia](https://user-images.githubusercontent.com/65788688/139947322-e1150ebc-b230-4581-b26d-f0eb501d7f48.png)
