### ISSUE TITLE
Unificar y subir la documentación de Pautas accesibilidad

### ISSUE THREAD

**Issue by ghoyos95** [gcba/estandares#15]
La idea es que primero definamos con qué nos quedamos de las estándares actuales de accesibilidad web
(https://www.buenosaires.gob.ar/estandares/accesibilidad-web)

y luego lo subamos a este repo. 

@Vpappacena  necesitamos tu intervención en esta tarea

----------
Tareas
----

- [x] relevar documentación actual de accesibilidad
- [x] unificar lo relevado con la documentación nueva que tengamos
- [x] subirlo a este repo :)

**Comment by Vpappacena** [comment]
@Jinik  , cuando podemos ver como subir imagenes o PDF a la documentación? . Subì una imagen de barreras y un pdf pero no logre hacer que funciones

**Comment by Jinik** [comment]
@Vpappacena  Sip, es algo que había quedado pendiente.

Para subir archivos hay que agregarlos dentro de la capeta `static`, no dentro de `pages`. En esa carpeta, se pueden crear las que quieran para organizar los archivos y se respeta en la url.

Todos los archivos que se suban, se tienen que vincular siguiendo ese patrón, comenzando con una `/`, por ejemplo:

```markdown
![gráfico que describie las barreras que generan discapacidades temporales,situacionales o permanentes](/pautas/accesibilidad/barreras.png)
```

Si te fijás, [acá ya actualicé el archivo que habías subido](https://github.com/gcba/estandares/commit/7c9c483857c2de0430126267c2941deb8df29564#diff-605cc4568533f4ee9e8f110839da2bc8R43). Mañana subo esta info a la wiki para que quede de referencia.

Por otro lado, en la página de Importancia, agregué otra opción más accesible para reemplazar esa imagen usando tablas en markdown. Se podrían subir cada figura individual, pero que el texto lo pueda leer un lector de pantallas.

**Comment by Vpappacena** [comment]
Para la Versión se subio 

- [ ] Normativas
- [ ] Normativas
- [ ] Normativas
- [ ] Normativas
