### ISSUE TITLE
Agenda

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#155]
### Discussed in https://github.com/gcba/estandares/discussions/154

<div type='discussions-op-text'>

<sup>Originally posted by **Vpappacena** November  1, 2021</sup>
Necesidad de crear un componente para agenda que responda a las áreas de cultura y desarrollo económico con el objetivo de visualizar  los eventos calendarizados y que a partir de ahi pueda selección e inscribirse a un evento de ser necesario </div>

**Comment by Vpappacena** [comment]
De que manera se muestran las agendas hoy : 
- Cultura - FIBA 2020
-impulso cultural - ba audiovisual 
-Usina del artes - calendario
-Cartelera - BA disfrutemos 
- Info cartelera  Festivales BA ( home y diferentes festivales. 
-Pagina de libro - info del evento , dia
- Programación agenda - cards

**Comment by Vpappacena** [comment]
**Primeras conclusiones del análisis para construir el modulo agenda:**

-PODER UTILIZAR MÓDULOS REDUCIDOS DE AGENDA:
-Visualizar UNA REDUCCIÓN DE LA AGENDA EN OTRA PAGINA SIN NECESIDAD DE ABRIR EL MODO COMPLETO.
- PODER DESGLOSAR EN MÓDULOS MÁS CHICOS PARA UTILIZAR EN OTRAS PÁGINAS. SOLO UN EVENTO PARTICULAR DE UN ÁREA. 
EJ: 25 DE ENERO - INICIO DE INSCRIPCIONES EDUCACIÓN
- NO DARLE TANTA ENTIDAD AL BUSCADOR PARA QUE NO COMPITA CON EL BUSCADOR DEL SITIO. REDUCIR A LUPA
- METERLE CONTENIDO REAL A LA PROPUESTA PARA "ESTRESAR" LA INTERFAZ Y REDUCIR CAMBIOS EN EL FUTURO. (ANTES DE PASARLO A ALTA)
- SUMAR CALL TO ACTION
- Trabajar en como seria la VERSIÓN MOBILE

**Comment by Vpappacena** [comment]
**Próximos pasos para ver el viernes 19/11/2021 :** 

- [ ]  construir módulos que se puedan utilizar en diferentes tipo de pagina según la necesidad. 
- [ ] Sumar contenido real a los ejemplos  y ver como funciona y poder sacarlo para testear. 
- [ ] construir la versión Mobile de los módulos de agenda
- [ ] Sumar posibilidad de call to action.  

@Fcunsolo  @Paulo-Bravo .

**Comment by aloyber** [comment]
Se trabajo en pasar las propuestas en baja fidelidad a propuestas con contenido real basado en casos de uso. Se tomaron como referencias:
- [PDF Educación - Agenda educativa 2021](https://www.buenosaires.gob.ar/sites/gcaba/files/agenda_educativa_2021_0.pdf) 
- [Abasto es teatro independiente](https://www.buenosaires.gob.ar/cultura/patrimonio-de-la-ciudad/noticias/abasto-es-teatro-independiente)
- [BAFICI](https://bafici2021.vivamoscultura.com/)

![1](https://user-images.githubusercontent.com/65788688/142653236-f0b4114f-8cda-414b-a543-8970b6b51af9.png)
![2](https://user-images.githubusercontent.com/65788688/142653244-ebbbaa33-a7cd-4822-9e32-1b0999f19824.png)
![3](https://user-images.githubusercontent.com/65788688/142653247-de93a4e9-754a-4394-aa6f-98cdb7e7ae25.png)


En proceso sigue la construcción de diferentes módulos para las paginas según la necesidad. Se hablo de concretar módulos que funcionen tanto en desktop como en mobile tratando de aprovechar los espacios que brinda cada dispositivo. 

![Desktop](https://user-images.githubusercontent.com/65788688/142653102-78d144fb-af81-4060-8b2a-24e2812cdb84.png)
![4](https://user-images.githubusercontent.com/65788688/142653340-926c1e97-b9f9-49e7-8214-98328d9bf496.png)


- [ ] Se va a trabajar en la semana en algun ejemplo más para validar el funcionamiento de la agenda y que aplique a todos los casos de uso.
- [ ] Ajustar los mínimos y máximos en las descripciones y las imagenes. Contemplar los casos de uso
- [ ] Definir como es el comportamiento en mobile.

**Comment by aloyber** [comment]
Se trabajó sobre otro caso de uso: Usina del Arte y su agenda 2021.
![Mesa de trabajo – 5](https://user-images.githubusercontent.com/65788688/143621682-5c0c02b0-1a16-48c3-aac4-9b9a36aa4393.png)
![Mesa de trabajo – 9](https://user-images.githubusercontent.com/65788688/143621687-b93cff2f-1dce-4e91-9ba7-cfca8b9c47b9.png)
![Mesa de trabajo – 10](https://user-images.githubusercontent.com/65788688/143621688-64778d20-eb1c-443a-81d7-f549eeb65ced.png)

Se agregaron nuevas formas de visualización del evento por separado en cards.
![Mesa de trabajo – 15](https://user-images.githubusercontent.com/65788688/143621780-786ec0e0-1074-4129-9deb-784476c172fc.png)

Se trabajaron diferentes formas de aplicar a la página del área.
![Mesa de trabajo – 6](https://user-images.githubusercontent.com/65788688/143622086-be1ad81a-a327-4b8b-828f-b6baf21cb15a.png)
![Desktop – 1](https://user-images.githubusercontent.com/65788688/143622093-8926d8c9-8da6-4095-a5fa-83cd88dda144.png)
![Desktop – 3](https://user-images.githubusercontent.com/65788688/143622095-f4ce24e8-489b-4549-be33-5a49c7ba32ef.png)

Validamos el comportamiento en mobile y quedaron pendiente los siguientes casos:
- [ ] Contemplar más casos de uso: Talleres, cursos, etc.. (Calendarización)
- [ ] Ajustar "descripciones e imágenes"
- [ ] Pensar cards para una actividad particular y no el evento en generales. Por ejemplo: Card actividad particular. ¿Que elementos podría llevar? Imagen, Titulo, Fecha, Modalidad, Botón para inscribirse, entre otros.. 

@Fcunsolo @Paulo-Bravo @Vpappacena @mathiassassone1

**Comment by aloyber** [comment]
Se estuvo trabajando sobre diferentes casos de uso que contemplen la calendarización.
- Se detectó la posibilida de ofrecer determinadas actividades/talleres que tienen una duración, por ejemplo de 1 semestre (agosto-diciembre)
- Además tienen un período de inscripción, por ejemplo: del 8 al 14 de agosto ("X" cantidad de días), en el cual una vez que cierra esa inscripción el ciudadano ya no puede inscribirse y participar de la actividad o taller
- Se debatió si las actividades que ya no tienen posibilidad de realizar inscripción deben mostrarse de cara al vecino
- Se puede dar la posibilidad de agregar, en las tarjetas, etiquetas en el que se indique al ciudadano varios casos sobre un mismo taller o actividad, por ejemplo: "Cupos agotados" ó "Inscripción finalizada" ó "Pocos cupos disponibles".. Para todo lo que tiene que ver con cupos habría que hablar con las áreas si hay alguna limitación en ese sentido.
- En los casos que haya cupos se podría agregar a la tarjeta la información del período de inscripción.

![Mesa de trabajo – 18](https://user-images.githubusercontent.com/65788688/144654658-ed6dd562-ea43-427e-991d-b0b540901c85.png)
![Mesa de trabajo – 17](https://user-images.githubusercontent.com/65788688/144654650-7a80f29c-cc04-4afd-9f3c-b665cdf9de0c.png)

@Fcunsolo @mathiassassone1 @Vpappacena

**Comment by Fcunsolo** [comment]
Se trabajó sobre los avances utilizando el contenido de https://www.buenosaires.gob.ar/vicejefatura/deportes para ver las posibilidades de escalabilidad del layout actual de agenda.

El equipo se quedó conforme con la adaptabilidad del layout al nuevo contenido: 
![Agenda-polideportivos](https://user-images.githubusercontent.com/65958941/147289273-c5582b9c-fa52-4f32-a3b4-f72cd4e4705e.png)

Se plantearon escenarios en los cuales una actividad tiene distintos días y horarios para realizarse. Resolvimos la selección de estos con selectores (para días y horarios) y un botón de "inscribirse".
Utilizamos la totalidad del contenido encontrado en https://www.buenosaires.gob.ar/vicejefatura/deportes/gimnasia-y-ritmos-en-parque-lezama.

Sacamos en claro que los elementos del listado de la izquierda se "estiran" dependiendo el contenido pero no se adapta la imagen a la altura final. Sigue respetando su tamaño y posición original:
![image](https://user-images.githubusercontent.com/65958941/147289943-531a2352-8a45-4210-b5d4-1da7509bd037.png)
![image](https://user-images.githubusercontent.com/65958941/147289955-388b713f-8671-4b9b-b8c8-93b6a4122e85.png)

Agregamos un posible feature que geolocalice al usuario y le ofrezca los resultados por cercanía (ese contenido tiene que poder seleccionarlo desde el filtro)
![image](https://user-images.githubusercontent.com/65958941/147290537-8f1eeabf-e06f-4487-856a-a2b67403ded2.png)

Incorporamos etiquetas para poder comunicar/identificar de forma rápida aquellos "eventos" que necesitan atención del usuario. Ej:
- "Ultimos cupos" (la acompaña la leyenda de cuántos cupos quedan)
- "Inscripción cerrada" (estos eventos van a estar visibles solo para que el usuario pueda pedir notificación si se vuelve a dar. Esta opción estaría dentro del detalle ej: "inscripción cerrada" + "notificarme cuando haya otra" - **¿Dónde se muestra esa notificación?**)
- "¡Nuevo!"
![image](https://user-images.githubusercontent.com/65958941/147290673-054afa76-17fd-4b86-86b5-7b4ad309d8fc.png)


Decidimos seguir trabajando en cuestiones como:

[ ]  Pensar una "antesala" al listado de eventos para una experiencia más personalizada y menos "invasiva" (en términos de volcar todo el contenido sin ningún filtro previo). Pensamos un layout simple como en https://trabajo.buenosaires.gob.ar/
Ej: "¿Qué actividad querés hacer?" + Selección de actividad + Selección de lugar (no son obligatorias tipo "despegar")

[ ] Semantizar las etiquetas con color. Ej: "ultimos cupos" en naranja.

[ ] Decidir cómo se comporta el dropdown del filtro. Pisa el contenido o lo desplaza?

[ ] Pensar cómo se destacaría un evento por fuera de la agenda.
