### ISSUE TITLE
Ajustar ficha colapsable - detalle

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#158]

**Comment by Vpappacena** [comment]
@SantiBugdadi   subir el  XD de la ficha

**Comment by SantiBugdadi** [comment]
Acá va la [ficha de colapsable](https://xd.adobe.com/view/93a7a8ea-7f6b-43d4-b737-c7ef7a6dfd8a-c6f4/screen/13f7e2ab-8a6b-49cc-804c-518c2b596e3a/) actualizada con la variante de colapsable para información!
