### ISSUE TITLE
Armar fichas de opciones

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#159]

**Comment by Vpappacena** [comment]
@SantiBugdadi   subir el  XD de la ficha

**Comment by SantiBugdadi** [comment]
Acá va la [ficha de opciones](https://xd.adobe.com/view/93a7a8ea-7f6b-43d4-b737-c7ef7a6dfd8a-c6f4/screen/b441bcc4-af9e-4387-a72f-bbc4dfd76a99/) nueva con las últimas modificaciones que vimos!
