### ISSUE TITLE
Auditoria de componentes

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#166]
- [x] Cards- contenedores
- [x] los  focus o lo hover
- [x] lista de navegacion
- [x] desplegable 
- [x] accesos
- [x] opciones
- [x] Paginado
- [x] colapsables
- [x] Botones
- [x] enlaces
- [x] controles de formulario
- [x] alerta -  (icono y el borde)
- [x] modal
- [x] etiquetas
- [ ] header
- [ ] footer

**Comment by mathiassassone1** [comment]
Dejo los primero componentes cerrados, se irá actualizando el mismo link, a medida que se terminen los restantes.

https://xd.adobe.com/view/261a24fd-6392-4e1c-9d28-0ec56be46608-7349/

@Vpappacena @nirougi @aloyber @Fcunsolo

**Comment by mathiassassone1** [comment]
Dejo link a continuacion con los cambios realizados tanto en componentes como en algunos de sus estados.

Este link se irá actualizando con los componentes faltantes.

https://xd.adobe.com/view/756054ec-3c46-4d88-80f8-2582c9dc348f-2033/

@nirougi @Vpappacena @aloyber @Fcunsolo @lautarorodriguez96 @techlowiec

**Comment by nirougi** [comment]
Ya resueltos:
- [x] controles de formulario

En proceso:
- [ ] Cards - contenedores
- [ ] los  focus o lo hover
- [ ] enlaces

Falta resolver:
- [ ] Lista de navegación
- [ ] Desplegable 
- [ ] Accesos
- [ ] Opciones
- [ ] Etiquetas

Cambios estéticos:
- [ ] Paginado
- [ ] Colapsables
- [ ] Botones
- [ ] Alerta -  (icono y el borde)
- [ ] Modal
- [ ] Header
- [ ] Footer

**Comment by mathiassassone1** [comment]
@mmainero @nirougi @lautarorodriguez96 @alan199912 

Header:
https://xd.adobe.com/view/756054ec-3c46-4d88-80f8-2582c9dc348f-2033/screen/3065dbc9-03c2-4de8-bc22-f697d57e5f9d/specs/

Footer:
https://xd.adobe.com/view/756054ec-3c46-4d88-80f8-2582c9dc348f-2033/screen/baffc5da-aa2f-4365-a055-f025ca1426db/specs/
