### ISSUE TITLE
Migas de pan (breadcrumbs)

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#17]
Analizar las diferente forma de usode miga de pan y luego sintetizar el analis en tres camino 
¨
- [x] revision

**Comment by ghoyos95** [comment]
encontré esta carpeta para relevar: link a carpeta falopa

**Comment by Vpappacena** [comment]
sfvnpdfvdfvz

**Comment by Vpappacena** [comment]
https://hodigital.blog.gov.uk/2016/12/21/creating-a-common-language-to-describe-services/

**Comment by Fcunsolo** [comment]
[Pendiente Revisión]
Comparto boceto de Componente Breadcrumb.

@aloyber @mathiassassone1 
[BREADCRUMBS-20200717.pdf](https://github.com/gcba/estandares/files/4939547/BREADCRUMBS-20200717.pdf)
@Vpappacena

**Comment by Jinik** [comment]
Dos cosas que tendría en cuenta:

1. Cómo se va a comportar en mobile. En teléfonos no tenemos tanto espacio para mostrar toda la cadena e incluso puede quedar pegado al título de la página, por lo que mostrar cuál es la actual puede ser redundante.

2. También tendría en cuenta para la ficha cuál sería el comportamiento ideal al recortar en base a la cantidad de caracteres, teniendo en cuenta que las páginas de áreas de gobierno siempre empiezan con el rango y podría estar ocultando la parte importante. Acá un ejemplo:
  `Buenos Aires / Salud / Subsecretaría de Atención Hospitalaria / Dirección General Sistema de Atención Médica de Emergencia (S.A.M.E.)`
  En ese caso el ministerio solo dice Salud, pero el resto tienen el nombre completo.

**Comment by julianrod** [comment]
Sumo el comentario de que el caracter "/" no es tan efectivo para manifestar jerarquía como un ">" o algo parecido, que indica dirección.

Ver por ejemplo: https://www.gov.uk/vehicle-tax

**Comment by Vpappacena** [comment]
@mathiassassone1 subí la última modificación sobre el componente. 
 
 Queda pendiente revisar la propuesta en mobile de como se ve  y se comporta el componentes

**Comment by Vpappacena** [comment]
@mathiassassone1  , queda pendiente subir como quedo para la V1 del componente.

**Comment by mathiassassone1** [comment]
Dejo propuesta para la primera versión.

[Migas de pan.pdf](https://github.com/gcba/estandares/files/5091681/Migas.de.pan.pdf)
