### ISSUE TITLE
Componentes barras de progreso

### ISSUE THREAD

**Issue by mmainero** [gcba/estandares#174]
Reemplazo de las barras de progreso con y sin porcentaje de BAstrap 

- [x] Subir diseño
- [ ] Estimar y priorizar desarrollo
- [ ] Subida a storybook

**Comment by mathiassassone1** [comment]
@mmainero @lautarorodriguez96 @alan199912 

Referencia:
https://gcba.github.io/BAstrap/#progreso

Reemplazo de barras de progreso:
https://xd.adobe.com/view/756054ec-3c46-4d88-80f8-2582c9dc348f-2033/screen/39aa3a58-f4ae-4a43-9a04-3834f0028387/specs/
