### ISSUE TITLE
Definir nuevos controles de formulario

### ISSUE THREAD

**Issue by ghoyos95** [gcba/estandares#18]
Subir link de la carpeta 

Objetivo: 
- Unificar los componentes relevados. 
- Armar la familia de controles de formularios estandarizada

**Comment by aloyber** [comment]
Proceso de controles de formulario primer etapa
@Vpappacena @Fcunsolo 
[Controles de formularios.pdf](https://github.com/gcba/estandares/files/4880511/Controles.de.formularios.pdf)

**Comment by aloyber** [comment]
Subo vista previa de un ejemplo de formulario
@Vpappacena 
[Ejemplo_formulario.pdf](https://github.com/gcba/estandares/files/4914850/Ejemplo_formulario.pdf)

**Comment by aloyber** [comment]
Para la v2:

[ ] Ver como funciona el **stepper** con texto alineado al centro

**Comment by Jinik** [comment]
1. Como hablamos ayer, no estoy seguro de que tener el label como parte de contenido y que al hacerle foco o escribir se mueva a la parte superior, algunos comentarios y opiniones personales al respecto:

  -  En caso de que algunos campos estén completos y otros no, por ejemplo teniendo opcionales, ésta solución va a modificar visualmente el espaciado que haya entre los campos y romper la consistencia que estamos definiendo. Material design hace algo parecido, pero el label queda dentro del contenedor o sobre el borde.

  ![image](https://user-images.githubusercontent.com/1561463/87864093-330d0980-c93a-11ea-925d-7501c50b8aad.png)

  - En el caso anterior, también pasa que las jerarquías de los labels van a quedar diferentes dependiendo el estado del input, esto creo que puede generar conflictos al escanear el contenido una vez completado el form, antes de enviarlo.
  [Éste artículo de NNGroup](https://www.nngroup.com/articles/form-design-placeholders/) habla un poco de eso, casi al final menciona a los floating labels.

- Me hace ruido también la diferencia de tamaño que quedaría entre labels de inputs y checkbox o radios.

2. Los campos deshabilitados quedan demasiado llamativos con ese fondo, ¿no? personalmente me resaltan casi lo mismo que el que tiene error.

3. Con radios y checkbox estaría bueno definir si la alineación es horizontal, vertical o ambas y en qué casos.
  Con la alineación horizontal, como está en los ejemplos, me preocupa un poco cómo quedarían con labels de largos dispares.

4. Tener en cuenta que, por lo general, con radios y checkbox hay un mensaje de error por cada grupo y no individualmente. Para todo se lo debería considerar un grupo de opciones, técnicamente esto se implementa con la etiqueta `<fieldset>`, a excepción de los checkbox de opt-in u opt-out.

5. El rango me parece que debería mostrar de alguna forma el valor que se está eligiendo y habría que definir cómo sería el label de ese elemento. También habría que definir el label para el input de archivos.

5. Me hace un poco de ruido que el label esté alineado al contenedor y el campo de ayuda al texto.

6. El stepper lo contemplaría como un componente aparte y lo dejaría para una segunda versión, vi que hay otra card con eso. El componente en sí viene acompañados de muchas definiciones dentro del patrón de separar un formulario en pasos, que al no tenerlas puede llegar a ser contraproducente.

7. Eventualmente deberíamos contemplar [todos los tipos de inputs](https://www.w3schools.com/html/html_form_input_types.asp), pero para la primera versión me parece importante contemplar los casos de números, emails, teléfonos y fechas. Por ahí no cambian tanto a nivel diseño, pero sí a nivel ficha e implementación.

**Comment by Vpappacena** [comment]
@Fcunsolo @aloyber ,  avancemos con la revisión de los tipos de formularios utilizados en GCBA según àreas (ej: educación, atención ciudadana...) para trabajar los formularios en contexto y poder analizar mas en profundidad los usos de los formularios (cuando, para que y porque).

**Comment by mathiassassone1** [comment]
@Vpappacena @Fcunsolo @aloyber @techlowiec @nirougi 

Dejo los avances para la V1 de los campos para formularios.

[Tipos de campos.pdf](https://github.com/gcba/estandares/files/5099042/Tipos.de.campos.pdf)
