### ISSUE TITLE
Sumar las Pautas de Contenidos

### ISSUE THREAD

**Issue by nirougi** [gcba/estandares#20]
Temas a sumar en el repositorio:
Comunicar con claridad
- [x]  Voz 
- [x] Tono
- [x] Lenguaje

Lenguaje
- [x] lenguaje incluyente
- [x] jerga 
- [x] tecnicismos

Convenciones de escritura
- [x] Títulos 
- [x] Bajadas
- [x] Uso de formatos (negrita, cursivas, etc)
- [x] Uso de horarios
- [x] Uso de de los símbolos numerales
- [x] Uso de signos de puntuación
- [x] Uso de enlaces

Cómo organizar el contenido
- [ ] pirámide invertida
- [ ] CHUNGING (escritura fragmentada)

***Pendiente definir gonza con Santi ***

- [ ]  Imágenes

https://gcba.github.io/estandares/pautas/contenido/

**Comment by ncorralesruiz** [comment]
### Voz

La voz del Gobierno de la Ciudad, como enunciador reconocido, es participativa y clara. Buscamos que nuestros usuarios se sientan acompañados durante la estadía dentro del sitio, y que reconozcan que atrás de lo que leen, también hay una persona (de carne y hueso y no un robot) pensando y redactando el contenido.

**Participativa**: Buscamos empatía pensando el contenido para nuestros visitantes, facilitando la interacción. Es importante que se sienta partícipes en todo el recorrido digital. 

**Simple y clara**: El usuario tiene que entender, independientemente de su procedencia sociocultural o nivel educativo el contenido que le presentamos. 

### Tono

El **tono** es la forma en que usamos la voz, es decir, cómo hablamos. cercano, conciso y directo y el **lenguaje** simple.  

**Cercano y amigable**
Trabajamos para que los vecinos visualicen que el contenido está dirigido hacia ellos para sentirse identificados. 
Por eso nos dirigimos utilizando el “**vos**”, que denota **cercanía** manteniendo el respeto.

**Ejemplo de este uso**:
“Encontrá la información para realizar los pagos por teléfono de gas, luz, celular, cable, internet y tarjetas. Llamá a cualquiera de estos números de teléfono para realizar tus pago”.
https://www.buenosaires.gob.ar/coronavirus/mayorescuidados/pago-de-servicios

**Corto y directo**
A la hora de redactar el contenido debemos de hacerlo de manera corta y directa, facilitando la inmediatez para encontrar y resolver lo que el usuario está buscando.

Ir al grano con el contenido es lo primordial, descartá palabras o frases innecesarias. 

**Uso correcto**: Conocé las iniciativas y sumate al voluntariado.
**Uso incorrecto**: Conocé las distintas iniciativas que el Gobierno tiene para sumarte al voluntariado”.

**Uso correcto**: Descargá las bases y condiciones
**Uso incorrecto**: Para conocer las bases y condiciones de la convocatoria, descargalas.

**Uso correcto**: Contraseña incorrecta.
**Uso incorrecto**: Has ingresado la contraseña incorrecta.

**Mensaje con valor agregado**

Todos los contenidos de nuestra web deben reflejar el valor y la utilidad de nuestros servicios para los ciudadanos. Preguntate qué beneficio obtiene el ciudadano y comunicalo en el primer párrafo. 

**Uso correcto**: Los vecinos de Parque Patricios fueron capacitados para combatir el dengue.
**Uso incorrecto**: El Ministro de Espacio Público recorrió el barrio de Parque Patricios y explicó a los vecinos cómo combatir el dengue. 

**Uso correcto**: Museos, Centros Culturales y teatros están temporalmente cerrados al público. Conocé Cultura en casa y disfrutá de la oferta cultural de forma remota. 
**Uso incorrecto**: Cultura en casa: recordá que los museos, centros culturales y teatros del GCBA están temporalmente cerrados al público. El Ministerio de Cultura implementó una nueva plataforma para disfrutar la oferta cultural de la Ciudad de manera remota. 

### Lenguaje simple

El lenguaje simple tiene como característica la claridad y sencillez, por eso usamos párrafos cortos que comuniquen una idea clara, lo cual permite a nuestros lectores entender fácilmente la información sin ambigüedades o múltiples interpretaciones. 

Escribí en **voz activa** y en **presente** ya que compromete y materializa las acciones que el usuario quiere realizar en tu sitio.
Uso correcto: Los vecinos de Villa Urquiza cuentan con un nuevo espacio verde para disfrutar”.
Uso incorrecto: El Jefe de Gobierno inauguró un nuevo espacio verde en el barrio de Villa Urquiza.

**Uso correcto**: Las Comunas reparten tapabocas a los adultos mayores
**Uso incorrecto**: Los adultos mayores recibieron tapabocas en las Comunas de la Ciudad.

**Uso correcto**: Terminá la secundaria con orientación en Formación Profesional.                 
**Uso incorrecto**: Los estudiantes que aún no finalizaron sus estudios secundarios pueden retomarlos con la orientación en Formación Profesional.  

**Lenguaje incluyente**
Para evitar el lenguaje sexista, el sesgo de género y la reproducción de estereotipos en el lenguaje tratamos de hacer uso de frases y expresiones más neutras e inclusivas.
**Ejemplo de lenguaje sexista**: “Los médicos infectólogos están trabajando en una vacuna contra el covid a nivel mundial”.
**Ejemplo de lenguaje incluyente**: “El personal de infectología está trabajando en una vacuna contra el covid a nivel mundial”. 

¿**Cuándo usamos lenguaje formal e institucional**?
Se reservará únicamente para comunicaciones de temas muy precisos que requieran extrema claridad al transmitir el mensaje.            
                                                    
**Ejemplo de este uso**: Aviso importante: ningún cuerpo médico o representantes del Ministerio de Salud están yendo a los domicilios particulares de los vecinos para realizar revisaciones por Coronavirus (COVID-19). https://www.buenosaires.gob.ar/coronavirus/medidas-de-gobierno

¿**Cuándo usamos jerga y tecnicismos**?
Evitemos palabras que no utilizamos habitualmente, a menos que se trate de un texto destinado exclusivamente a expertos de una disciplina. Hay que pensar que si un texto es comprensible sólo para los especialistas, estamos excluyendo a un gran número de lectores.
Si no queda más remedio que usar jerga porque cualquier otro término perdería precisión, expliquemos los conceptos la primera vez que los vayamos a utilizar, ya que es una forma de ampliar el público lector.

**Palabras en inglés**: No las uses, excepto nombres propios o términos especíﬁcos. En el caso de utilizar alguna palabra en inglés debe ir en cursiva.

**Comment by ncorralesruiz** [comment]
<h2>Títulos</h2>  

* El título de una página debe tener relación con el enlace de donde proviene (atajo, external link, banner, destacado, tarjeta, etc.).
* En los títulos de las páginas de área hablá como Gobierno y no como área, es decir, no debemos utilizar términos como «subsecretaría» o «ministerio», por ejemplo.
* Los títulos tiene que tener como **máximo 70 caracteres**. 

<hr>

<h2>Resúmenes o bajadas</h2>  

* Deben explicar de qué se trata toda la página de manera breve y concisa.
* Si tienen más de 2 líneas, se subdivide en oraciones, buscando que la información sea **fácil y rápida de entender** para el usuario.
* No deben repetir información mencionada en el título.
* Son **obligatorios** y su contenido indexa en las búsquedas de Google.
* No contienen negritas, mayúsculas, ni hipervínculos. 
* Deben tener como **máximo 150 caracteres**.

<hr>

<h2>Párrafo</h2>  

 Escribí una breve descripción de una idea, de **5 líneas** aproximadamente. 

<hr>

<h2>Negrita</h2>             

Utilizá la negrita para **destacar ciertos términos** que tienen mayor jerarquía en una oración. De este modo el usuario escanea rápidamente el contenido de tu sitio y encuentra fácilmente lo que está buscando. 

No utilizamos negrita en las bajadas de las páginas o dentro de una cita; tampoco en combinación con hipervínculos.     

Tampoco se usa negrita en los signos de puntuación, por ejemplo si escribo: “**Conocé las Postas saludables**.” Las comillas y el punto final no van en negrita.        
            
<h3>Ejemplo de buen uso</h3>   

*  El móvil cuenta con **personal técnico capacitado** que informa y asesora al vecino.           
*Destacá la información más relevante para el vecino.*       

<h3>Ejemplos de mal uso</h3>

* El móvil cuenta con personal técnico **capacitado** que informa y asesora al vecino.        
*No se le informa el contexto al vecino.*                          
*  El móvil cuenta con <u>**personal técnico capacitado**</u> que informa y asesora al vecino.                                   
*No combinar con un subrayado.*                       
* El móvil **cuenta con personal técnico capacitado que informa y asesora al vecino**.                 
*No destacar todo el texto, elegir lo más relevante para el vecino.*    
               
<hr>

<h2>Cursiva, bastardilla o itálica</h2>  

La cursiva se utiliza tanto para dar énfasis como para advertir al lector de que una palabra o una frase puede no resultarle familiar, ya sea porque es extranjera o porque forma parte de una jerga. 

<hr>

<h2>Enlaces</h2>  
           
Son hipervínculos que se usan en el sitio para que el vecino pueda tener **acceso a otras páginas** dentro y fuera del mismo. En el navegador, se ven como palabras subrayadas en color azul.     
                  
* Dirigí los enlaces siempre a una página existente.                      
* Es preferible que sean largos a muy cortos.                   
* Indexan en todos los motores de búsqueda, como Google, por eso debés incluirlos.   
                             
<h3>Ejemplo de buen uso</h3>  

Mirá toda la información sobre el [Plan Sarmiento](https://www.buenosaires.gob.ar/sarmientoba).                               
                        
* No uses «clic aquí » o «más información»; el texto debe tener sentido y clariﬁcar el enlace.                   
* No uses negrita en los hipervínculos.                  
* No incluyas signos de puntuación en los enlaces.   
                          
<h3>Ejemplo de mal uso</h3> 

Para más información sobre el Plan Sarmiento, haga [**clic aquí.**](https://www.buenosaires.gob.ar/sarmientoba)     

<hr>

<h2>Viñetas</h2>  

Nos permiten **listar y organizar** todo tipo de contenidos:                        

* Usalas para hacer listas que muestran etapas o grupos de información.                        
* Incluí una introducción para dar contexto a ese grupo de información.                               
* Enumerá cada etapa si el orden de la lista es importante.        

Ejemplo:          
Completá la solicitud con la siguiente información:

* Nombre y apellido            
* DNI          
* Domicilio         
* Correo electrónico      
  
<hr>

<h2>Uso de las mayúsculas y minúsculas</h2>  

<h3>Las mayúsculas se usan:</h3>

* Al principio de una oración.        
* Para nombres propios. Por ejemplo: "Ministerio de Educación", "Juan Pérez".   
* En términos como «Ciudad», «Gobierno», «Comunas» cuando se refieren a Buenos Aires.     
* En nombre de programas. Por ejemplo: “Plan Sarmiento”, “Ciudadanía Global”. 
* Para escribir siglas. Por ejemplo: "M.J.G.G.C."  

<h3>Las minúsculas se usan:</h3>

* Después de dos puntos a menos que armes una lista de elementos.
* En los días, meses y estaciones del año, excepto las efemérides.    
* Los cargos de funcionarios. Por ejemplo: "ministro de Educación".

*Importante*: nunca escribir TODO EN MAYÚSCULAS; **dificulta la lectura** y por convención web, sería como gritar o levantar la voz.

<hr>

<h2>Horarios</h2>  

* Al referirnos a horarios utilizamos el **símbolo h.** acompañado de un punto ﬁnal.   
* El símbolo puede incluirse en el último número; no es necesario incluirlo en ambos números.
 
Ejemplos:
La feria será de 14:30 a 19 h.

<hr>

<h2>Uso de símbolos numerales</h2>  

Usalos para números, no texto. Excepto para casos en el que se habla de pronombre «uno/una» o «unos/unas».

<h3>Ejemplo de buen uso</h3>

* Un funcionario se acercó al ediﬁcio.           
* 150.000 beneﬁciados.             
* 3 de cada 10 personas usan nuestro sistema.	         
* 8 de marzo de 2019.	                    

<h3>Ejemplos de mal uso</h3>

* 1 funcionario se acercó al ediﬁcio.          
* Ciento cincuenta mil beneﬁciados.      
* Tres de cada diez personas usan nuestro sistema.                   
* Hoy- Ayer.    

<hr>

<h2>Uso de los dos puntos</h2>  

**Representa una pausa** mayor que la de la coma y menor que la del punto. Detienen el discurso para llamar la atención sobre lo que sigue, que siempre está en estrecha relación con el texto precedente. Se escriben pegados a la palabra o el signo que los antecede, y separados por un espacio de la palabra o el signo que los sigue. Sirve para introducir enumeraciones, conclusiones, ejemplos o información que concreta lo que acaba de anunciarse.

Después de dos puntos se escribe minúscula, salvo en casos excepcionales.

Entre las excepciones a esta norma, más allá de otros usos no habituales en textos periodísticos (después de encabezamientos de cartas o mensajes electrónicos, por ejemplo, en cuyo caso lo apropiado es escribir la siguiente palabra en renglón aparte), los dos puntos van seguidos de mayúscula cuando introducen una cita o un pensamiento en estilo directo.

Ejemplo de un caso en mayúscula: “En una muestra más del trabajo en equipo que estamos haciendo con el Gobierno nacional y también con el de la provincia, pusimos en marcha un nuevo dispositivo para cuidar a la gente”. (Horacio Rodríguez Larreta)

<hr>

<h2>Signos de interrogación y exclamación</h2>  

A diferencia de lo que ocurre en otras lenguas, los signos de interrogación y exclamación son signos dobles en español, como los paréntesis o los corchetes. Por tanto, es incorrecto prescindir del signo de apertura en los enunciados interrogativos o exclamativos:

<h3>Ejemplo de buen uso</h3>

* ¿Completó el formulario?         
* ¡Gracias por inscribirte!        

<h3>Ejemplos de mal uso</h3>
     
* Completó el formulario?     
* Gracias por inscribirte!    

Cuando los signos de cierre (? !) constituyen el final del enunciado, la palabra que sigue se escribe con mayúscula inicial.

Ejemplos:

* ¿Completó el formulario? Puedo hacerlo desde nuestra página.   
* ¡Gracias por inscribirte! Pronto recibirás más información.

**Comment by victoriajustina** [comment]
@ncorralesruiz buenísimo que subiste la sección de "Usos y convenciones de escritura".

@nirougi decíamos con Nati que estaría bueno que nos den una mini capacitación la semana que viene o cuando puedan para subir los contenidos a esta otra sección: https://gcba.github.io/estandares/pautas/contenido/usos-y-convenciones-de-la-escritura/

¿Cómo lo ves?

**Comment by nirougi** [comment]
Dale, me parece bien. Por ahí @Vpappacena o alguien más de equipo puede encarar la capacitación, yo suelo ser medio complicado con los horarios.

En el mientras tanto, en la [descripción del proyecto](https://github.com/gcba/estandares) hay información (un tanto básica) de cómo hacer cambios, cómo deben estructurase los archivos, cómo subir imágenes u otros archivos, etc. Si todavía no le dieron una mirada, se los recomiendo.
Por ahí con eso ya tienen una base y en la reunión nos enfocamos más en dudas.

Respecto a modificar esa sección, [desde acá pueden ver los 3 archivos](https://github.com/gcba/estandares/tree/master/src/pages/pautas/contenido) de las pautas de contenidos. Haciendo clic en cada uno, y si iniciaron sesión en github, les va a aparecer un lapicito arriba a la derecha para editarlo.

**Comment by ncorralesruiz** [comment]
Perfecto Nico, revisamos lo que nos pasaste y les avisamos entonces!

Muchas gracias!


*Lic. Corrales Ruiz Natalia*
*Analista de contenidos y Administradora de www.buenosaires.gob.ar
<http://www.buenosaires.gob.ar> *
*Gerencia Operativa de Experiencia de Usuario*
*D**irección General Experiencia Digital*
*Subsecretaría Experiencia Digital*
*Secretaría de Innovación y Transformación Digital*
GCBA* | *Teléfono: 50309200 interno 2223
