### ISSUE TITLE
Alertas

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#21]
construir un estándar de Alertas para productos digitales de GCBA y  compartirla primera versión de las 4 Alertas

**Comment by aloyber** [comment]
Comparto adjunto la primer versión de las alertas

[FICHA 2 ALERTAS.pdf](https://github.com/gcba/estandares/files/4814783/FICHA.2.ALERTAS.pdf)
@Vpappacena

**Comment by aloyber** [comment]
Proxima etapa revisar:
- [ ] Cierre de las alertas. ¿Cuándo se puede cerrar y cuándo no?
- [ ] Alertas por tiempo. ¿Puede haber casos en el que las alertas aparezcan por "x" tiempo y se cierren solas?
- [ ] Hacer accesible el cierre. Que no solo esté el ícono de cerrar, sino también la palabra.

@Fcunsolo @Vpappacena @mathiassassone1
