### ISSUE TITLE
Template - Áreas de gobierno

### ISSUE THREAD

**Issue by paulajoglar** [gcba/estandares#211]

**Comment by paulajoglar** [comment]
https://xd.adobe.com/view/c52283b0-0c7b-4a24-b4dd-7600b0e22fdd-9071/

**Comment by lautarorodriguez96** [comment]
Finalizado

**Comment by paulajoglar** [comment]
**Pendiente:** 

- verificar si los espaciados en mobile son armónicos o hay que modificarlos
