### ISSUE TITLE
Destacado (ex Panel)

### ISSUE THREAD

**Issue by paulajoglar** [gcba/estandares#212]
Armar componente de información. 
Diseño
https://xd.adobe.com/view/0e981914-a860-4e8f-a915-2b5a4b3016b1-5bcb/

![Image](https://user-images.githubusercontent.com/106768801/212926410-de715e52-34cb-4b7c-a564-5ff29982ad7f.png)

**Comment by paulajoglar** [comment]
Tomar de acá el diseño de Componente "contacto e información"
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/UI-KIT---Obelisco?node-id=945%3A8852&t=N5NDa4gDEQhTSw4f-0

**Comment by lautarorodriguez96** [comment]
Faltaria la ficha en estandares para subir el componente

**Comment by aloyber** [comment]
@lautarorodriguez96 voy a actualizar el componente y ver la mejor manera para estandarizar su comportamiento en relación tambien a los paneles

**Comment by aloyber** [comment]
Se sube img de el estado del componente "Panel"

![Image](https://user-images.githubusercontent.com/65788688/235184076-f2bdd87c-a4c7-4fc6-9c6c-18437cf3ee67.png)

---

Se procede a la unificación de **bloque de información** y **panel**. Se cambia el nombre de esta tarjeta por **"Panel"**

**Comment by aloyber** [comment]
Se deja el branch correspondiente a la construcción del componente: https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/bgq6m9tRd2zTczVLtkTAIn/UI-KIT---Obelisco?node-id=945%3A8852&t=1SqepRGn1JagN85u-1

Se deja el branch correspondiente a la ficha del componente: https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/piMpFzFCCGVkG1REeNt3GP/Fichas?node-id=3122%3A12168&t=r7GCspiP3zjixxQV-1

Se requiere la revisión y aprobación de @camilagaldo para avanzar a la etapa de maquetado.

**Comment by NatiOertel** [comment]
**Actualización del componente:**


**Panel grande:**

- Se eliminó la opción de panel con botón de descarga, ya que se puede llegar al mismo resultado a través de las variables de los botones.
- Se corrigieron espaciados.
- Se agregaron variables booleanas para mostras 2 acciones o 2 enlaces en los Accionables.
- Se cambió el ancho de los paneles grandes para mobile. Antes era 340px y ahora es 328px para asegurar la correcta visualización del mismo en dispositivos mobile.

Antes:

![Image](https://github.com/gcba/estandares/assets/106767361/29f5785e-593d-4983-a54e-21f1478e2efd)

![Image](https://github.com/gcba/estandares/assets/106767361/3fb44828-2547-4d61-8323-c0032f816297)


Después:

![Image](https://github.com/gcba/estandares/assets/106767361/75ca27c4-1d01-4f0d-b2f5-10b90f65e476)

![Image](https://github.com/gcba/estandares/assets/106767361/ab22886e-ad33-4136-a2d5-d678027471fa)


**Panel chico:**

- Se separaron los paneles con mapa del panel chico para que sean un panel aparte.
- Se dejaron como variables booleanas solamente la imagen, el título H3 y la bajada del panel, ya que los demás agregados se pueden customizar a través de la variable “Tipo”.
- Se cambió el ancho de los paneles chicos para mobile. Antes era 340px y ahora es 328px para asegurar la correcta visualización del mismo en dispositivos mobile.
- Se crearon como componentes aparte en la misma branch la imagen que mostrarán los paneles chicos para que la misma pueda variar entre un tamaño de 150px y 104px. La lista de títulos H4 también se componetizó aparte con sus respectivas variables para customizarla a elección.

imagen panel y lista H4:

![Image](https://github.com/gcba/estandares/assets/106767361/3f2d5d1d-b6cc-463b-b403-f72ad0462747)

![Image](https://github.com/gcba/estandares/assets/106767361/d1fd8cfd-2fd5-439b-a5d8-cd80bb303eb6)


Antes:

![Image](https://github.com/gcba/estandares/assets/106767361/3bd81a1c-59a6-4707-a70f-8533e035a6da)

![Image](https://github.com/gcba/estandares/assets/106767361/0cdbc789-046a-4956-8077-d6bc77c03544)


Después:

![Image](https://github.com/gcba/estandares/assets/106767361/5a9ca492-2745-4dda-8c2f-89db442db038)

![Image](https://github.com/gcba/estandares/assets/106767361/2a8fda57-b194-45e1-9ffa-2db1d04e6e27)


**Panel con mapa:**

- Se agregó una variable para customizar la cantidad de columnas que ocupa el componente.

![Image](https://github.com/gcba/estandares/assets/106767361/3114d760-8ee8-4764-a5c9-dc06f3b72a98)

![Image](https://github.com/gcba/estandares/assets/106767361/5ecee9a7-4868-4b4e-a3ff-a3f8657e1436)

**Comment by marusaad** [comment]
Con @Diehault retomamos el análisis del Panel y comenzamos con algunas propuestas para poder ver el lunes en la daily. 

**Propuesta "Destacado"** 
Entendimos que este panel se utilizaba como un destacado dentro de la página, por lo que podría ser un componente aparte que cumpla esa función, despegándose de panel que no sabemos si va a seguir existiendo. En base a los usos que mapeamos y otros posibles en el futuro elaboramos la nueva propuesta con sus variantes que se puede ver en [Análisis de componentes](https://www.figma.com/file/mqy6dUBWeK47l1CMIYCdkX/An%C3%A1lisis-de-componentes?type=design&node-id=920%3A75&mode=design&t=af8tR7VtzUOyk4t4-1). 



![Image](https://github.com/gcba/estandares/assets/136834096/c2805c8a-583a-43d8-8a6b-2fe1a1ac2cfc)


**Propuesta para panel de descargas**
Va a depender de lo que se vaya analizando en plantillas @NicoAltamirano porque los usos mapeados están a partir de plantillas que no sabemos si se van a conservar. Además, en las plantillas aparecen ejemplos que no son de máxima (por ejemplo, 3 anexos, cuando pueden llegar a haber más de 7) por lo que se requiere un análisis de si a partir de estos casos es necesario que exista el componente. 

- Botón de descargas
Dado que el color del enlace de descarga actual no pasa accesibilidad con un fondo primario, hay que rever este componente de panel y considerar continuar utilizando el botón (especialmente en destacados con fondo) hasta que veamos colores. 


![Image](https://github.com/gcba/estandares/assets/136834096/97a10fa0-7e24-4a7a-ad90-ff0e8e2eddb7)

**Tarjeta destacada**
Comenzamos a considerar la posibilidad de que el panel que ocupa 6 columnas con botones sea considerado como una "tarjeta destacada". No nos centramos en este análisis aún, lo vamos a seguir viendo y retomando. 



![Image](https://github.com/gcba/estandares/assets/136834096/cf9c32b7-3636-4f41-a0d7-ea6ec70ee9cc)


Todas estas cosas las llevamos a la daily del lunes @camilembo para poder compartirlas

**Comment by marusaad** [comment]
✒️ **Comenzamos la construcción del componente Destacado que reemplazará al Panel Grande y Panel Chico** (el único que queda _por ahora_ es el de Institucional y el lateral de descargas). Por ahora se puede ver en [Análisis de Componentes](https://www.figma.com/file/mqy6dUBWeK47l1CMIYCdkX/An%C3%A1lisis-de-componentes?type=design&node-id=920%3A75&mode=design&t=DEPlZ25dAIaVtjPy-1). 

Se creó el componente **Multimedia - Destacado** que permite cambiar entre imagen y video. El componente se anida dentro de Destacado.

 

### Multimedia - Destacado
- Variante Tipo: Imagen / Video
- Variante Reproductor: N/A (para Imagen) / Primario / Secundario
> La variante _Reproductor_ se creó para que la barra de reproducción haga contraste con el color de fondo. Lo vamos a chequear con desarrollo. 


![Image](https://github.com/gcba/estandares/assets/136834096/d93bb6a9-c707-4013-aaac-5052fc55ad30)


### Destacado
- Variante Dispositivo: Desktop / Mobile
- Variante Tamaño: 6-col / 12-col / Único (para mobile)
- Variante Fondo: Sin fondo (para mobile) / Primario / Secundario
- Variante Multimedia: Sí / No (queda sólo fondo, texto y CTA)
- Tipo: Con 2 botones / Con botón / Con descarga / Con acceso / Con enlace externo
- Propiedad Texto Título
- Propiedad Texto Cuerpo

> Optamos por la nomenclatura basada en la cantidad columnas para la variante de tamaños, pero también podría ser por porcentaje (al 50% o al 100%) 



![Image](https://github.com/gcba/estandares/assets/136834096/2287bdfd-8cb4-47b9-b1d4-5a87b7bfa540)

**Comment by Diehault** [comment]
¡Hola! 👀​

Dejo por acá actualizaciones que fuimos haciendo sobre el componente a diferentes niveles. Estuvimos trabajando en el comportamiento del Destacado en los diferentes dispositivos, las variantes del componente y cómo está construido, y la nomenclatura del mismo.

![image](https://github.com/gcba/estandares/assets/144037453/d8048035-37a6-44f0-8af0-ee9318c261ea)
_Vista previa de una imagen de cómo está presentado el componente actualmente dentro de la branch de "Destacado" en el UI Kit_

## ¿Qué estuvimos cambiando?

- La nomenclatura del componente cambió de la siguiente manera:

![image](https://github.com/gcba/estandares/assets/144037453/97b6c0a7-b0af-4b53-bc03-3d6caf166a81)

Según esta imagen, tenemos entonces que la propiedad de "Tamaño" cambió por "Tipo" y la propiedad de "Tipo" cambió por "Accionable", como una nueva forma de nomenclar el componente.

### Nomenclatura de Accionable

![image](https://github.com/gcba/estandares/assets/144037453/e62c6760-8c94-4d6e-9e13-8077e2c4f961)

### Nomenclatura de Tipo

![image](https://github.com/gcba/estandares/assets/144037453/a9292dfb-edac-41de-aabc-92e2bd4be2a8)

- Definimos el comportamiento para cada una de las variantes del componente "Destacado" y su responsive.

Todas las variantes, a excepción del "Destacado lateral", pasan a la variante mobile; entonces, sea un "Destacado conjunto" o un "Destacado banner", siempre pasará a ocupar el 100 % del ancho de la página para tablet y mobile.

Por otro lado, la variante de "Destacado lateral" ocupa el 100 % de la grilla de la página (no llega hasta el final/borde de la página) al pasar a mobile y tablet. En tablet, el accionable del "Destacado lateral" está alineado a la izquierda, ajustado al contenido del mismo, y no se estira con el contenedor del componente.

### Destacado lateral en desktop

![image](https://github.com/gcba/estandares/assets/144037453/adcb2bbd-c129-405f-9ab6-7894b241e381)

### Destacado lateral en tablet

![image](https://github.com/gcba/estandares/assets/144037453/ba28e583-f2ba-4d20-afb5-8943deebd4c4)

### Destacado lateral en mobile

![image](https://github.com/gcba/estandares/assets/144037453/61487db5-7c68-4a7c-9593-a931045fe2de)

También, como parte de una nueva propuesta que estamos trabajando para la plantilla de los componentes, tienen una variante del "Destacado" para que puedan ver dentro del Playground del DevMode.

![image](https://github.com/gcba/estandares/assets/144037453/a02c0cf9-1bbc-43c2-aa28-7b4ddab9bad9)

**Comment by Diehault** [comment]
¡Hola! 🚗​ Actualizamos la imagen del Destacado, que antes no era una imagen de BA (cositas que sucedieron), y actualizamos el tamaño del Destacado full-width que no tenía el tamaño correcto.

### ¿Qué hicimos?

- Actualizamos la molécula de .multimediaDestacado.
- Ajustamos el tamaño del Destacado banner para desktop.
- Actualizamos la imagen de la molécula .multimediaDestacado en la ficha.

### ¿Cómo se ve ahora el componente?

![Image](https://github.com/gcba/estandares/assets/144037453/5e9c9ee7-4376-4613-a6ab-62cea8d73168)
![Image](https://github.com/gcba/estandares/assets/144037453/95a7a01f-51bb-42e6-bfea-d879c21f1674)

**Comment by Diehault** [comment]
¡Hola! 📎

Actualizamos el componente aprovechando la actualización general de la guía tipográfica.

### ¿Qué hicimos?
- Actualizamos los estilos tipográficos de la plantilla del UI kit y del componente Destacado.
- Actualizamos las instancias internas de botones de las diferentes variantes mobile.

### ¿Cómo se ve la página del componente en el UI kit?
![Image](https://github.com/user-attachments/assets/a9ee6f52-dddf-4e16-afe1-de7caf4de332)

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | El componente Destacado tuvo modificaciones en las variantes con “2 CTA”; Las variantes de botones a utilizar son btn-primary-filled + btn-primary-outlined. Queda descartada la utilización de la variante btn-secondary. - La modificación está contemplada en los patrones de uso y combinaciones de botones/accionables que definen que sólo puede existir un botón filled dentro de un mismo contexto y que para acciones repetitivas se utilizan botones outlined. <br> Hicimos la actualización de color correspondiente al contenido textual de todas las variantes del componente utilizando la variante $body-primary
