### ISSUE TITLE
Mensajes de estado

### ISSUE THREAD

**Issue by paulajoglar** [gcba/estandares#213]
**Nombre en Obelisco:** Mensajes de estado
**Descripción:** Se requiere construir un nuevo componente
**Tipo de componente:** organismo
**Ejemplo en bootstrap:** no existe
**Ejemplo de aplicación en BA:** 

- [x] Construcción nuevo componente
- [ ] Actualización componente existente

**Comment by paulajoglar** [comment]
Agregar a librería

**Comment by paulajoglar** [comment]
@victoriajustina Podrás revisar la documentación de Galería de img, por favor?

**Comment by aloyber** [comment]
@lautarorodriguez96 se requiere actualizar la ficha para la web de estándares

**Comment by victorianastasi** [comment]
Debido a la revisión realizada deTipografía, se observa que hay estilos que difieren en el componente Mensajes de estado entre [Storybook ](https://gcba.github.io/Obelisco/?path=/story/componentes-mensajes-de-estado--status-success) y [UI Kit](https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/UI-KIT---Obelisco?node-id=689-11418&mode=dev) en Figma.
1) El icono tiene 60x60 en Storybook y en UI Kit tiene 64x64.
2) El espaciado entre la lista y el botón es 32px en Storybook y en UI Kit es 48px

El componente fue maquetado en enero de 2023 acorde al [diseño provisto en XD](https://xd.adobe.com/view/4177d82c-6f12-414e-88ac-d930298974bd-1424/specs/) e incluido en la version 1.45.0 de Obelisco.

Se acuerda junto con el equipo de diseño que no se harán modificaciones, se modificará sólo la tipografía y cuando se tome este componente, se analizará.

**Comment by Diehault** [comment]
¡Hola! 📎

Actualizamos el componente aprovechando la actualización general de la guía tipográfica. Encontramos varias cosas que hay que ver a nivel de sistema de diseño y que consideramos evolutivos.

### ¿Qué hicimos?
- Actualizamos la plantilla del componente en la librería del UI kit.
- Actualizamos los estilos tipográficos del componente.
- Reemplazamos el componente "boton_ancho", que no era parte del UI kit y no existía en nuestra librería, por el componente Botón correspondiente para todas las variantes.
- Cambiamos la iconografía que quedó fuera de versión por íconos de la librería de Material Design Icons.
- Reemplazamos la estructura de lista que tenía cada una de las variantes por el componente Lista informativa, ya que es el componente que cumple con la función necesaria.
- Definimos un texto estándar para la descripción de cada variante del componente, para simplificar el contexto de uso.
- Sumamos propiedades de texto para el título y para la descripción, para hacer más fácil la edición de las instancias copiadas.

### ¿Qué encontramos y consideramos como evolutivo?
- Deberíamos evaluar si el nombre actual del componente es el mejor y/o el que mejor se ajusta a nuestras necesidades. Puede resultar confuso tener un componente llamado "Mensaje de estado" cuando hay otros componentes que, dentro de sus funciones, incluyen el informar sobre el estado de un progreso, del sistema, etc.
- El tamaño del ícono según lo que está disponibilizado en Storybook y lo que tenemos en la librería del UI kit difiere. Para el UI kit tenemos un ícono de 64px, mientras que en el Storybook disponibilizamos el componente con un ícono de 60px. Habría que empatar el tamaño por alguna de las 2 opciones.

### ¿Cómo se ve la página del componente en la librería del UI kit?
![Image](https://github.com/user-attachments/assets/58b7ac8d-0d6a-4655-af38-4eca755e0575)

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA).

## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Actualizamos el componente incluyendo la colección de variables con la nueva paleta de colores.<br>Sumamos una propiedad booleana para seleccionar la variante con 1 botón o con 2 botones.
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | Asignamos por defecto que el componente cuente con 2 botones primarios, respetando la jerarquía de acción principal (_filled_) y acción secundaria (_outlined_).

## ✏️ Notas
- El componente Mensaje de estado nos sirvió para identificar los nuevos patrones de diseño para accionables dentro de Obelisco. Al momento de tomar concretamente nuestros patrones de diseño, podemos tener este componente de referencia.
