### ISSUE TITLE
Home para templates

### ISSUE THREAD

**Issue by paulajoglar** [gcba/estandares#214]
Definir home para subir los templates a estándares
https://drive.google.com/drive/folders/1Nbn0akYWtMF-n9DHDlC2385k45mJ51-G

Armémoslo como esta propuesta pero con el ícono a la izquierda y colores como story (grisulado 90 y 5)
https://drive.google.com/file/d/11rx84ErKQgIK9e38DWn68PMLm1V5b308/view?usp=share_link

**Comment by victorianastasi** [comment]
Propuesta de home modificada: https://drive.google.com/file/d/1TodrRi5BDi50_UNS6VLkKu69OlnnPLeP/view?usp=share_link

**Comment by victorianastasi** [comment]
Propuesta de home modificada con titulos centrados: https://drive.google.com/file/d/1zaWRFvbPjhMnMsC-Tymz1YWX5U9Ln25l/view?usp=share_link
