### ISSUE TITLE
Migas de pan

### ISSUE THREAD

**Issue by paulajoglar** [gcba/estandares#215]
# Migas de pan

**Nombre en Obelisco**
Migas de pan

**Tipo de componente**
Átomo | **Molécula** | Organismo | Plantilla

**Links**
[UI Kit](https://www.figma.com/design/ToGlPBzfp1gKDmaCwKWtXS/UI-KIT---Obelisco?m=auto&node-id=1950-12806&t=NKlXrVPsDVFIJD18-1) | [Ficha Figma](https://www.figma.com/design/Pi8vXNQiMDtCNvV1aTCQX7/Fichas?m=auto&node-id=177-423&t=HhVdSUJytQBOSR4i-1) | [Estándares ](https://gcba.github.io/estandares/componentes/miga-de-pan/)| [Storybook](https://gcba.github.io/Obelisco/?path=/story/componentes-migas-de-pan--breadcrumb)

**Ejemplo en Bootstrap**
[Breadcrumb](https://getbootstrap.com/docs/5.0/components/breadcrumb/)

**Ejemplos de aplicación en BA**
Navegación en el encabezado

**Comment by paulajoglar** [comment]
**Requerimiento:** se necesita compatibilizar la información brindada en el Storybook, UI KIT y web de estándares para citas.
En el UI kit se modifica el último nivel para que sea enlace y muestre la página anterior.

**Comment by paulajoglar** [comment]
Diseño

![Image](https://user-images.githubusercontent.com/106768801/217593047-9ab51db2-c807-4966-8980-f1b0dcbc6668.png)

**Comment by paulajoglar** [comment]
**Pendiente**

- Actualización de librería

**Comment by aloyber** [comment]
**Requerimiento:** Se requiere actualización del componente que muestre el correcto funcionamiento en UI KIT y esté en una página por separado. Además se busca documentar el comportamiento del componente en casos donde el texto sea demasiado extenso, por ejemplo: https://buenosaires.gob.ar/educacion/escuelaabierta/vacaciones-en-la-escuela/inscripcion-docentes-y-administrativos

**Comment by aloyber** [comment]
@ncorralesruiz @victoriajustina se deja la ficha actualizada para una revisión de contenido: https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/tSvhxnqYDZkpK5C9rSxNhc/Fichas?node-id=1%3A534&t=Rz7nfnR1Fcw9I21d-1

- Se trabajó en la actualización de la ficha
- Se tuvo en cuenta un ejemplo de uso para textos con +36 caracteres
- Se actualizaron los textos
- Se actualizó la sección de usabilidad

**Comment by victorianastasi** [comment]
Reunión 14/03 - Aspectos trabajados:

- Se definió el ancho máximo para textos largos en migas de pan en dispositivos de escritorio (256px).
- Pendiente:
   - [ ] Revisión de la referencia "Última página visitada" en vez de "Página anterior".
   - [ ] Revisión de los niveles visualizados en dispositivos móviles. Definición del ancho máximo en el caso de textos extensos.

**Comment by victorianastasi** [comment]
Se modifica componente en Storybook en rama _fix_breadcrumb_
Se modifica ficha en Estándares, en rama _actualizacion_ficha_migas_de_pan_

**Comment by camilembo** [comment]
Reabrimos este requerimiento para hacer un ajuste en la variante de texto.
Crear branch y sumar texto truncado al texto :)

**Comment by Diehault** [comment]
¡Hola! Dejo por acá la actualización del componente, donde armamos las migas de pan nuevamente, con el componente de Enlace nuevo y el ajuste de propiedades. 🍞​

### ¿Qué se hizo?

- Armamos un nuevo componente con la actualización del componente Enlace
- Sumamos la documentación correspondiente de Storybook y la ficha en Estándares

### Muestra del nuevo componente

![Image](https://github.com/gcba/estandares/assets/144037453/9cb66074-ac95-4797-b920-a7090dd0a459)

![Image](https://github.com/gcba/estandares/assets/144037453/ba7b6416-9cd3-4edc-8df6-634f10cb9451)

Por acá dejo el [link](https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/R1LdVH9qzzEgoU5F5bL0Pt/UI-KIT---Obelisco?type=design&node-id=15306%3A3635&mode=design&t=L6NKxn1YK64UoGvG-1) a la branch para que lo puedan ver directamente.

**Comment by camilembo** [comment]
Listoo
Se hizo merge con estos ajustes el 29/09 :)

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA).

## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Actualizamos el componente incluyendo la colección de variables con la nueva paleta de colores.
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | 

## ✏️ Notas
- N/A.
