### ISSUE TITLE
Botones

### ISSUE THREAD

**Issue by paulajoglar** [gcba/estandares#216]
# Botón 

**Nombre en Obelisco**
Botón

**Descripción del componente**
Los botones permiten iniciar acciones o navegar a otras páginas. Las etiquetas de los botones expresan qué acción ocurrirá cuando la persona usuaria interactúe con él.

**Tipo de componente**
**Átomo** | Molécula | Organismo | Plantilla

**Links**
[UI Kit](https://www.figma.com/design/ToGlPBzfp1gKDmaCwKWtXS/UI-KIT---Obelisco?m=auto&node-id=618-8342&t=NKlXrVPsDVFIJD18-1) | [Ficha Figma](https://www.figma.com/design/Pi8vXNQiMDtCNvV1aTCQX7/Fichas?m=auto&node-id=2136-813&t=eaK5PJa16YhVHY77-1) | [Estándares ](https://gcba.github.io/estandares/componentes/boton/)| [Storybook](https://gcba.github.io/Obelisco/?path=/story/componentes-botones--button-types)

**Ejemplo en Bootstrap**
[Botón en bootstrap](https://getbootstrap.com/docs/5.0/components/buttons/)

**Ejemplos de aplicación en BA**
Acciones

**Comment by aloyber** [comment]
Documentación
https://docs.google.com/document/d/1XbWFO4LbiCB2_xm3NdQvTUpJaHKxhTjD/edit#heading=h.gjdgxs

**Comment by aloyber** [comment]
**Descripción:** Se requiere actualizar el componente con la incorporación de algunas variables:

- Botones con borde
- Botones con ícono

- [ ] Construcción nuevo componente
- [x] Actualización componente existente

---

¿A donde hay que llegar?
Ejemplos de aplicación de botones:
![Image](https://user-images.githubusercontent.com/65788688/210673951-397848c6-9dd5-4a86-beb9-da2abaea1b6e.png)
![Image](https://user-images.githubusercontent.com/65788688/210674093-819381b6-0c37-4253-9ccb-c26fa7f59

**Comment by paulajoglar** [comment]
Se creó un branch en UI KIT para el componente botones: https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/Am0LZV3t3wEaQsx1iiBQhC/UI-KIT---Obelisco?node-id=618-8342&t=Vb1jtrNVyh5cjHaN-0

**Comment by paulajoglar** [comment]
Se trabajó en:

**Estructura del botón:**
Se nomenclaron todas las capas y se eliminaron los frames vacios para mejorar la estructura del componentes.
Se modifico alineación de ícono y texto para poder utilizar el botón en diferentes anchos y se mantenga el contenido centrado.

Se elimina botón en caja por ser molécula.
Se cambio la variable foco para mobile por active
Se cambia de page los botón check basándonos en la funcionalidad y no en la apariencia. (Pasa a formularios)

**Se generaron propiedades:** 
![Image](https://user-images.githubusercontent.com/106768801/230964529-556af1f0-01de-41fd-be4f-e2f4b6b93ab4.png)

**Comment by NatiOertel** [comment]
Se revisó la ficha con @aloyber. Queda pendiente colocar un ejemplo en el apartado "Jerarquías".

**Comment by victorianastasi** [comment]
Se modifica componente en Storybook en rama _fix_buttons_ y se modifica ficha en Estándares, en rama _fix_button_

**Comment by victorianastasi** [comment]
Debido a la revisión realizada de Tipografía, se observa que hay estilos que difieren en el componente Botón entre [Storybook](https://gcba.github.io/Obelisco/?path=/story/componentes-botones--button-types) y [UI Kit](https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/UI-KIT---Obelisco?node-id=618-8342&mode=dev) en Figma.

1. En Storybook el borde esta por fuera del componente. En Figma esta por dentro.
![Image](https://github.com/gcba/estandares/assets/60082396/2f768aac-0f3e-48d9-9840-60341ab86338) 
![Image](https://github.com/gcba/estandares/assets/60082396/9dbda8c0-a634-4252-98e7-577f177916db)

Al modificarse el line-height y tener border, se modifica el alto el componente. Por lo que se acuerda junto con el equipo de Diseño, modificar el estilo en desarrollo.
Se reemplaza border por outline, con el fin de mantener su accesibilidad en High Contrast Mode, y en el caso del estado focus, se agrega `outline-width: 4px;` , en concordancia con el diseño, para mantener la accesibilidad en High Contrast Mode y navegación por teclado.

![Image](https://github.com/gcba/estandares/assets/60082396/d3fd60fb-7fc2-4f4d-ab8f-da08c7b4fb77)

2. El botón chico, al cambiar el line-height ( pasa de ser 18px a 20px) y tener padding top y bottom de 4px, y no tener los 2px de borde, su alto pasa a ser de 28px y no 30px como previamente. 

![Image](https://github.com/gcba/estandares/assets/60082396/b7abd361-4016-4b75-820b-645f6ebaa55d)

![Image](https://github.com/gcba/estandares/assets/60082396/7c66015e-3471-470b-a223-9eca02e5bc8c)

Se acuerda con el equipo de diseño que el alto mínimo del botón chico se mantenga en 30px. 

Se modifica su padding top y bottom a 5px con el fin de que el texto este centrado tanto en etiquetas `<button>` como `<a>`.

Con `padding: 4px 8px;`
![Image](https://github.com/gcba/estandares/assets/60082396/32639371-5bd8-4919-a834-bc2f95ab21a4)



Con `padding: 5px 8px;`
![Image](https://github.com/gcba/estandares/assets/60082396/51954fef-22a8-4e57-90fe-5265166d6e25)

**Comment by Diehault** [comment]
¡Hola! 👀

Actualizo con lo último que hicimos sobre el componente Botón, teniendo en cuenta la actualización general de la guía tipográfica.

### ¿Qué hicimos?
- Eliminamos 1305 variantes botón en la búsqueda de simplificar y optimizar el componente.
- Prescindimos de las variantes mobile porque el componente comparte las mismas características y forma para todos los dispositivos.
- Actualizamos los estilos tipográficos.
- Modificamos las propiedades del componente y simplificamos su consumo.
- Incorporamos el componente Spinner actualizado, ya que antes se utilizaba con componente que hacía parte ya de la librería.
- Eliminamos todas las variantes de Estado correspondientes al botón de solo contorno, porque son las mismas variantes del botón relleno.

### ¿Qué va a suceder tras la simplificación del componente?
- En todos los proyectos donde se utilice la variante antigua de mobile aparecerá que el componente no existe más y debe ser restaurado. En este caso, tendrán que reemplazar la variante por el componente Botón dentro de la librería del UI kit.
- Tenemos pensado sumar material de apoyo para compartir con el equipo de ED y con áreas internas que utilicen Obelisco, para acompañar el proceso de sustitución y reemplazo de la forma menos destructiva posible.

### ¿Cómo se ve la página del componente en el UI kit?
![Image](https://github.com/user-attachments/assets/bc937a81-84d1-4639-a132-fd3bad3c47eb)

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Tickets relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] <s>El componente tiene una medida definida para mobile, tablet y desktop</s>. **[no aplica para este componente]**
- [x] <s>El componente tiene una modulación definida para mobile, tablet y desktop</s>.  **[no aplica para este componente]**
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
No se realizaron cambios en esta revisión. 

## ✏️ Notas
No hay ninguna nota para mostrar.

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA).

## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Actualizamos el componente incluyendo la colección de variables con la nueva paleta de colores.<br>Sumamos la variante $light para fondos oscuros.
Arreglado | Actualizamos el ícono por default que va dentro del botón por el ícono de "add-circle".
Eliminado | Retiramos la variante de "Cargando en foco", teniendo en cuenta que el botón no es accionable en este estado.<br>Eliminamos la variante _outlined_ para el estado "Cargando", ya que el estado tendrá un único diseño para todos los botones.
Obsoleto | 
Cambiado | Cambiamos la concepción del botón en el estado "Cargando", que antes lo entendíamos como variante de tipo a nivel de sistema de diseño, por una variante de estado.<br>Definimos, luego de un mini-bench que hicimos sobre el estado "Cargando", que el botón debe estar deshabilitado en este estado.

## ✏️ Notas
- **Variante $light:** definimos que la variante $light se utilizará únicamente sobre fondos oscuros y como botón secundario, para asegurar la accesibilidad de una variante con menos peso jerárquico cuando se necesita reflejar más de 1 acción.
- **[EV]:** es posible reducir la variante de Botón Deshabilitado en el set del componente, dejando una única variante para todos y no que cada tipo tenga su versión deshabilitada.
