### ISSUE TITLE
Pie de página

### ISSUE THREAD

**Issue by paulajoglar** [gcba/estandares#217]
Documentación
https://docs.google.com/document/d/1XbWFO4LbiCB2_xm3NdQvTUpJaHKxhTjD/edit#heading=h.gjdgxs

**Comment by paulajoglar** [comment]
Se requiere analizar la posibilidad de añadir un enlace más al footer.

**Comment by paulajoglar** [comment]
Se solicita revisión sobre la opciones a @aloyber y @camilagaldo

**Comment by paulajoglar** [comment]
Se trabajó en la estructura del pie de página y en el componente del UI KIT para generar variables en sus usos.

![Image](https://user-images.githubusercontent.com/106768801/229152155-18c1e41f-78f5-4bb0-bc42-1ac1128978f2.png)



![Image](https://user-images.githubusercontent.com/106768801/229152611-cecea0d9-be5c-4fcf-9e15-8e0663d85aa3.png)

**Comment by paulajoglar** [comment]
@victoriajustina dejo el acceso a la ficha para una revisión de contenido:

https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/J1Saz3qum8wSlOzrsRaiIp/Fichas?node-id=1589-812&t=eZ1vDx9e8JrSObMf-0

**Comment by LuCostas** [comment]
@NatiOertel Nati, podrás dejar el último estatus? Mil gracias.
