### ISSUE TITLE
Armar ficha sobre alertas

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#22]
Construir la ficha de componente de alertas teniendo en cuenta las referencias.

[https://github.com/gcba/estandares/issues/21](url)

**Comment by aloyber** [comment]
Adjunto la primer versión de ficha de alertas

[FICHA 2 ALERTAS.pdf](https://github.com/gcba/estandares/files/4821518/FICHA.2.ALERTAS.pdf)
@Vpappacena @Fcunsolo @mathiassassone1 @victoriajustina

**Comment by aloyber** [comment]
Se definió usar un H4 de acuerdo a los estándares de tipografía.

**Comment by aloyber** [comment]
Subo ficha actualizada
[Uploading FICHA ALERTAS 24:07.pdf…]()

Se agregó visualización en mobile para resolver problema del espaciado.
@Vpappacena @Jinik

**Comment by nirougi** [comment]
@aloyber no se subió el archivo, quedó el link apuntando a cualquier lado.

**Comment by aloyber** [comment]
> Subo ficha actualizada
> [FICHA 2 ALERTAS.pdf](https://github.com/gcba/estandares/files/5001892/FICHA.2.ALERTAS.pdf)
> 
> Se agregó visualización en mobile para resolver problema del espaciado.
> @Vpappacena @Jinik @victoriajustina

actualizado

**Comment by nirougi** [comment]
Van un par de comentarios:

- Por el momento evitaría poner los ejemplos del html ya que pueden confundir porque no están correctamente armados.
- Habría que definir el área de clic para el botón de cerrar tanto en computadoras como teléfonos.
- En accesibilidad deberíamos aclarar que el botón para cerrar tiene que tener un `aria-label="Cerrar alerta"` o algún texto similar.

**Comment by Vpappacena** [comment]
@mathiassassone1  subir el link de la ficha :)

**Comment by Vpappacena** [comment]
@mathiassassone1 subir el link de la ficha :)

**Comment by Vpappacena** [comment]
[FICHA 2 ALERTAS.pdf](https://github.com/gcba/estandares/files/5740505/FICHA.2.ALERTAS.pdf)
