### ISSUE TITLE
Nuevo estilo de componente +Agregar lorem

### ISSUE THREAD

**Issue by AgusSurraco** [gcba/estandares#220]
**Botón Agregar Solicitante** @aloyber @camilagaldo @paulajoglar 
La sección Solicitante está compuesta por un mínimo (2) que es lo que visualiza el usuario en su estado inicial y un máximo que es personalizable. Es requerimiento que un usuario cargue el formulario con un mínimo de dos asistentes para que se habilite el botón Confirmar (acción que redirecciona a la pantalla Turno Confirmado)

**Comportamiento esperado, carga de 2 a 10 asistentes**
Accionar el botón Agregar Solicitante despliega un formulario en estado vacío con los campos requeridos para agregar un tercer asistente. Permite agregar el nro definido como máximo de asistentes (ejemplo 10). 
Una vez que completa el nro máximo, el botón se deshabilita, impidiendo la carga de nuevos asistentes

![image](https://user-images.githubusercontent.com/123394349/214128549-560be0f2-dec4-4a61-b29a-7406e8d2fb35.png)
Link a figma
https://www.figma.com/file/qnEQdvT9bcx4QePdSZpTjU/UI-KIT---Obelisco?node-id=565%3A57071&t=cl04bYA5f7VWDmKI-1

**Comment by paulajoglar** [comment]
Hola @AgusSurraco, te dejamos la rta que estuvimos viendo con @lautarorodriguez96. Quedamos atentos ante cualquier duda.

En Obelisco no tenemos un componente con este comportamiento. 

A continuación, sugerimos una posible solucione:
Utilizar un botón con ícono para la función de eliminar, agregar o editar.

![image](https://user-images.githubusercontent.com/106768801/214907296-749dbf50-5eb6-447a-ac47-3ecf5ee4423a.png)

Los inputs para los datos podrían mostrarse de esta manera. Luego de guardar, se pueden visualizar los asistentes en una etiqueta span y los botones de editar y eliminar o en una tabla con accionables (editar o eliminar)
Storybook: [Tabla con accionables](https://gcba.github.io/Obelisco/?path=/story/componentes-tablas-con-acciones--con-botones)
![image](https://user-images.githubusercontent.com/106768801/214907555-9b21dc98-58af-4725-8abd-6a46b954337b.png)

Otra opción, es mostrar solo un formulario. Una vez de completarlo, tocar en el botón “agregar asistente” y por debajo cargar los usuarios como en la primera opción, una lista o una tabla. Los inputs se limpiarán para una nueva carga de datos. 
Si solo se agrego un usuario y quiero continuar, deberá aparecer un mensaje “debe cargar al menos dos asistentes” 
En el caso de llegar al máximo de usuarios cargados, deberá bloquear el botón de agregar “agregar asistente”.

![image](https://user-images.githubusercontent.com/106768801/214907744-7c971d0d-79a2-424e-a2d0-041c4463c0b3.png)
