### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by aloyber** [gcba/estandares#224]
**Nombre en Obelisco:** Audio
**Tipo de componente:** Molécula
**Ejemplo en bootstrap:** No existe
**Ejemplo de aplicación en BA:** Página de noticias, videos, contenido multimedia.

**Comment by aloyber** [comment]
1. Hoy en día tenemos este componente en UI KIT. 
![Image](https://user-images.githubusercontent.com/65788688/218263800-5dd33a8d-9932-4e8f-be4a-253e69500629.png)
Entiendo que el reproductor de video dentro de las tarjetas no lo utilizamos ya que al hacer clcik el usuario se lo redirecciona a su respectiva página. 

2. Hoy en día en Storybook no tenemos un componente de "reproductor de video", basicamente esta compuesto por un ícono https://fonts.google.com/icons?icon.style=Rounded&icon.query=play arriba de la imagen. ¿Deberíamos agregarlo a la librería? Debatamoslo.

@lautarorodriguez96 @victorianastasi @Jesus1397 @aloyber @davisLjr @matilope 
Espero confirmación.

**Comment by aloyber** [comment]
¿Pudieron analizarlo? @lautarorodriguez96

**Comment by lautarorodriguez96** [comment]
Ari, ya tenemos la propuesta maquetada por @davisLjr 

Tenemos la opción con contenedor como el componente audio. No es una tarjeta, porque el funcionamiento seria distinto ya que te redireccionaría a otro lugar y no reproduciría el video.

 Después, tenemos la opción de cargar un video local con el icono proporcionado (hay algunas consultas a nivel diseño) y la opción de un video de youtube.

**Comment by marusaad** [comment]
Se actualizó la plantilla de la page del componente con los nuevos estilos tipográficos. 

![Image](https://github.com/user-attachments/assets/8ee2ef33-b12f-40e8-a78c-88deae3704c9)

### ¿Qué cosas consideramos como evolutivos?

- El componente de Audio es un reproductor que nosotros disponibilizamos desde Storybook y que hace parte de la librería de Obelisco, pero no hay una ficha técnica del componente y tampoco está muy claro su uso.  En algunas conversaciones con el equipo de Desarrollo salió este componente, y el resumen fue que se trata más de un componente representativo, porque los reproductores de audio que aparecen en la web de BA son nativos del navegador desde el que entra la persona usuaria.  
- Deberíamos ampliar con el equipo de Desarrollo para saber si hay más información al respecto.

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] El componente tiene una modulación definida para mobile, tablet y desktop.
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | Width de la variante desktop a 348px.

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 


### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [ ] El componente se ajusta a la grilla 4px.
- [ ] El componente tiene una medida definida para mobile, tablet y desktop. **[No incluye la medida Tablet]**
- [ ] El componente tiene una modulación definida para mobile, tablet y desktop. **[No incluye la disposición Tablet]**
- [ ] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [ ] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Cell
Arreglado | Cell
Eliminado | Cell
Obsoleto | Cell
Cambiado | Cambió la variante desktop del componente a 348px de width.

## ✏️ Notas

- **[EV]**: Evaluar si es necesario incluir la variante para dispositivos desktop, tanto su medida como su modulación.

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA).

## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Actualizamos el componente incluyendo la colección de variables con la nueva paleta de colores.
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | 

## ✏️ Notas
- N/A.
