### ISSUE TITLE
Spinner

### ISSUE THREAD

**Issue by paulajoglar** [gcba/estandares#225]
# Spinner

**Nombre en Obelisco**
Spinner

**Tipo de componente**
Molécula

**Referencias de Bootstrap**
[[Theming Bootstrap](https://getbootstrap.com/docs/4.6/getting-started/theming/#color) | [Utilities: Colors](https://getbootstrap.com/docs/4.6/utilities/colors/)](https://getbootstrap.com/docs/4.6/components/spinners/)

**¿Qué tenemos en Obelisco actualmente?**
[Estilos de color en Estándares](https://gcba.github.io/estandares/componentes/spinner/) | [UI Kit](https://www.figma.com/design/ToGlPBzfp1gKDmaCwKWtXS/UI-KIT---Obelisco?node-id=870-7996&t=263hVtEIAGAZz7hQ-0)

**Comment by paulajoglar** [comment]
Diseño

![Image](https://user-images.githubusercontent.com/106768801/217375558-e392973d-bdb6-4890-a329-47d200887cdd.png)

**Comment by paulajoglar** [comment]
Documentación para la ficha: https://docs.google.com/document/d/1XbWFO4LbiCB2_xm3NdQvTUpJaHKxhTjD/edit#heading=h.9m3fo5kl4s1p

**Comment by aloyber** [comment]
@lautarorodriguez96 se requiere maquetar la ficha para la web de estándares

**Comment by paulajoglar** [comment]
Se creó un branch en UI KIT para el componente spinner:
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/AvjnjMjNe1gyOCMfjPZIuO/UI-KIT---Obelisco?node-id=1333-14738&t=TDwE8LloQipfSOGW-0

**Comment by victorianastasi** [comment]
Según lo conversado en la reunión del 21/03, se realizaron las modificaciones en Storybook en la rama _fix_spinner_
Pendiente en ficha de estandares: aclaración sobre el posicionamiento del texto junto al spinner y en el caso de spinner expandible, la clase a la cual determinar el alto y el ancho del spinner (_spinner-size_).

**Comment by NatiOertel** [comment]
Se revisó la ficha con @aloyber

**Comment by victorianastasi** [comment]
Se modifica ficha en Estándares, en rama _fix_spinner_

**Comment by marusaad** [comment]
¡Hola! 👀

Actualizo con lo último que hicimos sobre el componente Botón, teniendo en cuenta la actualización general de la guía tipográfica.

### ¿Qué hicimos?

- Sumamos la variante de _Tipo_ en el componente Spinner, con la intención de hacerlo más completo de cara al componente “Botón”.

Para poder optimizar correctamente lo que tenemos hoy en día como componente “Botón”, era necesario generar variantes de _Tipo_ en Spinner que correspondieran a lo que mostramos y disponibilizamos desde Storybook. No contábamos con variantes que siguieran la lógica de color que sí sigue a nivel de desarrollo, por lo que las sumamos e implementaremos en el componente “Botón”.  En Storybook existe una variante con descripción, con un texto por ejemplo de “Cargando”. Esa propiedad no aparece en el UI Kit, pero sí tiene estilos asignados de texto según la escala nueva (Cuerpo M Regular). 

- Se incorporó la nueva plantilla del UI Kit. 

### ¿Evolutivos?

- Agregar la etiqueta de "Cargando" al componente
- Evaluar si vamos a conservar las lógicas de color de Storybook. ¿Se podría considerar sobreescribir el spinner predeterminado con estilos de color de texto y utilizarlos como componentes base de botones, en vez de como variantes de Spinner?
- Actualizar las fichas con las variantes de color incorporadas. Esto sería ideal una vez que se definan los estilos de color, por eso queda como evolutivo. 
- Incorporar descripciones por variante en el componente (una vez finalizado el punto de arriba) con las indicaciones de uso. Por ejemplo: _se utiliza para X y dentro de X botón_ 

### ¿Cómo se ve la página del componente en el UI kit?


![Image](https://github.com/user-attachments/assets/228ebd3e-87d7-4707-8a58-baf08af8afc4)

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] El componente tiene una modulación definida para mobile, tablet y desktop.
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | 

## ✏️ Notas

- No se realizó ningún cambio sobre el componente porque no era necesario. El tamaño del Spinner está definido por la grilla de 4px.

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA).

## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Actualizamos el componente incluyendo la colección de variables con la nueva paleta de colores.<br>Sumamos la variante $tertiary para el componente.<br>Definimos una variable $bg-ondark específica dentro de la capa funcional del componente.<br>Agregamos la variante con texto de soporte ("Cargando..."), junto con su propiedad booleana para cambiar entre variantes.
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | 

## ✏️ Notas
- **Variante $spinner-info**: conservamos esta variante porque se utiliza en producción (Obelisco Angular y TAD), pero decidimos no incluirla en el front de Obelisco v.2 y en el UI kit para desalentar su uso.
