### ISSUE TITLE
Accesos

### ISSUE THREAD

**Issue by aloyber** [gcba/estandares#226]
Nombre en Obelisco: Accesos
Tipo de componente: Molécula/Organismo
Ejemplo en bootstrap: No existe
Ejemplo de aplicación en BA: Listas, Página de trámites

**Comment by aloyber** [comment]
**Requerimiento:** Se necesita compatibilizar la información brindada en el Storybook, UI KIT y web de estándares para el componente de accesos.

- Se requiere hacer un cambio en la estructura del componente. Esto permitirá encontrar con mayor facilidad las variables con las que cuenta
- Se plantea una división entre lo que es el **componente** y el **organismo**
- Se requiere hacer un cambio estructural en el UI KIT donde el componente no este definido por una de sus variables
- Se requiere realizar una actualización en la web de estándares del comportamiento. Algunos conceptos a tener en cuenta: el componente no es utilizado para "cerrar sesión"; la descripción puede aplicar tanto a los accesos grandes como chicos (debe ser escalable y no estar reducido a necesidades puntuales); se debe mencionar como funcionan los accesos en conjunto formando **organismos**; agregar un apartado para describir como funciona el componente con sus diferentes variables (cómo es cuando se sacan y se agregan, versión min/max)

---

Se deja una imagen de referencia en cuanto a como se encuentra y que se espera:

![Image](https://user-images.githubusercontent.com/65788688/217402280-437788e4-8647-4e79-8594-48de1a5e16f9.png)

**Comment by aloyber** [comment]
Se creó un branch en UI KIT para el componente accesos: https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/yoHDMBDlk17xvznUXvcqS2/UI-KIT---Obelisco?node-id=1563%3A20240&t=7VM2qyAhiuXli4ts-1 

---

¿En que trabajamos?

- Unificar el componente y que contenga dentro todas las variables. 
- Nomenclatura. Figuraba como "Accionable" se determinó que el componente es "Acceso"

Antes:

![Image](https://user-images.githubusercontent.com/65788688/217403572-300f07ae-4333-47cb-b296-f9b99d7e071a.png)

Después:

![Image](https://user-images.githubusercontent.com/65788688/217403519-ecf779c4-e6da-45c8-b119-9f6460065cd6.png)

![Image](https://user-images.githubusercontent.com/65788688/217403742-7a7de2ef-3732-4688-9c59-b1bc9e2e95e2.png)

@paulajoglar

**Comment by aloyber** [comment]
@victoriajustina dejo el acceso a la ficha para una revisión de contenido: https://www.figma.com/proto/Pi8vXNQiMDtCNvV1aTCQX7/branch/Zk7lWtk8RzGfKCo7EE8YEG/Fichas?page-id=1%3A534&node-id=42%3A2133&viewport=385%2C711%2C0.44&review-number=1&scaling=min-zoom

**Comment by lautarorodriguez96** [comment]
En el componente acceso sin borde no se muestra en storybook por separado como si lo hacemos con borde, ya que se usa dentro de un organismo y puede generar una confusión al usarse.

**Comment by matilope** [comment]
Rama trabajada: fix_access

**Comment by Diehault** [comment]
¡Hola! 👀

Actualizamos el componente de "Acceso" y los organismos relacionados aprovechando la actualización general de la guía tipográfica. Consideramos algunos evolutivos, que detallamos debajo, con el fin de optimizar y brindar la mejor versión a nivel de diseño y estructura de los organismos que hacen parte del UI kit.

### ¿Qué hicimos?
- Actualizamos la plantilla del componente "Acceso" y de los organismos de "Accesos" dentro del UI kit.
- Corregimos propiedades y nomenclatura de ambas páginas dentro del UI kit.
- Actualizamos la iconografía dentro de los componentes, porque no estábamos utilizando Material Design Icons como lo requiere nuestro sistema de diseño.
- Incluimos descripciones para cada uno de los sets de componentes, con el fin de brindar mayor información sobre los componentes y recursos relacionados del sistema de diseño (links al Storybook y a la página web de Estándares).
- Reemplazamos el divisor de los organismos de "Accesos" por la propiedad de stroke de los contenedores principales. Con esto, evitamos tener un elemento adicional dentro de la estructura del componente y optimizamos su uso.

### ¿Qué cosas consideramos como evolutivos?
- Los diferentes sets de componentes que hay dentro de la página de los organismos de "Accesos" pueden ser un único componente con propiedades editables.
- Hay que revisar los usos y casos de máxima de los organismos en la página de "Accesos", para determinar en qué contextos se utilizan y cuáles podrían ser las buenas y malas prácticas correspondientes.
- El organismo de "Lista de accesos" dentro de la página de organismos de "Accesos" no necesita ser un componente. Podemos cubrir esta necesidad con explicar, dentro de la ficha del componente "Acceso", de qué forma modular diferentes instancias/componentes hijos del mismo.
- Revisar en conjunto con el equipo de Desarrollo cada uno de los casos que actualmente están como opciones.

### ¿Cómo se ve el componente y sus organismos dentro de la librería?
![Image](https://github.com/user-attachments/assets/c5ccebc8-ae95-49bf-a096-7e64a73a5136)
_Página del componente "Acceso"._

![Image](https://github.com/user-attachments/assets/0cef5ae5-d00e-4625-ad82-010452d025c3)
_Página de "Accesos" con los organismos provenientes de la molécula._

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#212 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] El componente tiene una modulación definida para mobile, tablet y desktop.
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | v.0
-- | --
Agregado | **Nueva variante tablet** <br> Min-width 336px (3-col) y max-width 696px (6-col). Min-height 48px. <br> Modulación: 24px. 
Arreglado | -
Eliminado | **Se elimina la variante de Storybook de acceso de 2 columnas**. Quedan las opciones de 4, 3 y 1 columna (esta última para no generar confusiones se llamaría algo “_disposición en aside_”). <br> **Se elimina la modulación de “lista ancho completo"** para no generar accesos de 12 columnas. <br> Se elimina la opción de modulación “simple horizontal” que implicaba que, por ejemplo, al haber 7 accesos queden en una fila 4 y en la fila de abajo 3. Sólo se conserva la disposición por ancho fijo de acceso.
Obsoleto | -
Cambiado | **Variante desktop:** min-width 253px (3-col) y max-width 328px (4-col) <br> **Variante mobile:** min-height 48p <br> **Modulación desktop** vertical y horizontal: 32px. <br> **Modulación mobile:** 16px <br> 

## ✏️ Notas

- **[EV]**:  actualizar la ficha del componente.

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [ ] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [ ] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Cell
Arreglado | Cell
Eliminado | Cell
Obsoleto | Cell
Cambiado | Cell

## ✏️ Notas

-  Se asignaron las variables de color correspondientes según el estado del componente.
