### ISSUE TITLE
Paneles

### ISSUE THREAD

**Issue by paulajoglar** [gcba/estandares#227]
Nombre en Obelisco: paneles
Descripción: se requiere construir un nuevo componente
Tipo de componente: organismo
Ejemplo en bootstrap: https://getbootstrap.com/docs/4.6/components/jumbotron/
Ejemplo de aplicación en BA:

- [X] Construcción nuevo componente
- [ ] Actualización componente existente

**Comment by paulajoglar** [comment]
Diseño de los componentes

![Image](https://user-images.githubusercontent.com/106768801/217584334-e31aff63-ead8-47a2-ba53-50d0d26179fc.png)



![Image](https://user-images.githubusercontent.com/106768801/217584349-804af2e4-8b70-42d6-9912-36af20881de8.png)

**Comment by paulajoglar** [comment]
Documentación para ficha: 

https://docs.google.com/document/d/1XbWFO4LbiCB2_xm3NdQvTUpJaHKxhTjD/edit#heading=h.nmsnqm6mih7d

**Comment by aloyber** [comment]
Para este requerimiento ya se hizo el **merge**. Se archiva ya que se unifica el componente de **bloque de información** y **panel**: en el issue https://github.com/gcba/estandares/issues/212
