### ISSUE TITLE
Tarjeta horizontal

### ISSUE THREAD

**Issue by paulajoglar** [gcba/estandares#228]
**Nombre en Obelisco:** tarjeta horizontal
**Descripción:** se requiere construir un nuevo componente
**Tipo de componente:** molécula
**Ejemplo en bootstrap:** 
**Ejemplo de aplicación en BA:** accesos a otras paginas

- [x] Construcción nuevo componente
- [ ] Actualización componente existente

**Comment by paulajoglar** [comment]
Diseño del componente

![Image](https://user-images.githubusercontent.com/106768801/217584974-b98c2c51-7b3d-4ebd-a4ad-fc56231ccae0.png)

**Comment by paulajoglar** [comment]
**Pendientes:**
- se propone un cambio de nomenclatura para las tarjetas horizontales
- se sugiere unificar las tarjetas de 6 y 4 columnas por un único componente que sea responsivo.
- Actualizar documentación en estándares

**Comment by aloyber** [comment]
@paulajoglar Unificar en "Tarjeta", vertical y horizontal son las variables. Deberiamos tener toda la info en un solo lugar del componente.

**Comment by paulajoglar** [comment]
Se unifican "tarjeta vertical" y "tarjeta horizontal" en el siguite issue: https://github.com/gcba/estandares/issues/240
