### ISSUE TITLE
Citas

### ISSUE THREAD

**Issue by paulajoglar** [gcba/estandares#229]
Nombre en Obelisco: citas
Tipo de componente: átomo
Ejemplo en bootstrap:
Ejemplo de aplicación en BA: destacados en el sitio web y citas.

**Comment by paulajoglar** [comment]
Requerimiento: se necesita compatibilizar la información brindada en el Storybook, UI KIT y web de estándares para citas.
En el UI kit se modifica la variable tipográfica del autor por itálica.

**Comment by paulajoglar** [comment]
Diseño

![Image](https://user-images.githubusercontent.com/106768801/217591758-92d7eeed-1ea5-4ab0-b818-98c4160149c4.png)

**Comment by paulajoglar** [comment]
**Pendiente**

- Actualizar UI Kit

**Comment by Diehault** [comment]
¡Hola! 🐹

Actualizamos el componente aprovechando la actualización general de la guía tipográfica.

### ¿Qué hicimos?
- Actualizamos la plantilla del componente en la librería del UI kit.
- Actualizamos los estilos tipográficos del componente.
- Empatamos los tamaños de los textos dentro del componente en la librería del UI kit con lo que disponibilizamos desde Storybook. Ahora, el nombre del autor de la cita estará en Cuerpo S/Semibold, cuando antes estaba en Cuerpo L/Regular.

### ¿Cómo se ve ahora la página del componente en el UI kit?
![Image](https://github.com/user-attachments/assets/6e4c847a-b4e5-4532-8c60-b246d1223cd5)

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311  

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] El componente tiene una modulación definida para mobile, tablet y desktop.
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | v.0
-- | --
Agregado | Se creó la variante Tablet - Widht: 696px (100%) - para todos los tipos de páginas en las que se incluya el componente. 
Arreglado | Cell
Eliminado | Cell
Obsoleto | Cell
Cambiado | En la variante Desktop se agregó el padding izquierdo de 63px. (1-col) para incluirlo en la aplicación del componente.

## ✏️ Notas

- **[EV]**: -

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Se creó la variable $mark
Arreglado | Cell
Eliminado | Cell
Obsoleto | Cell
Cambiado | Cell

## ✏️ Notas

-  Se creo una variable ($mark) dentro de la capa funcional, con quotes/, para asignar el color del identificador de la cita sin depender de una variable de texto.
