### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by paulajoglar** [gcba/estandares#231]
# Modal 

**Nombre en Obelisco**
Modal

**Tipo de componente**
Átomo | Molécula | **Organismo** | Plantilla

**Links**
[UI Kit](https://www.figma.com/design/ToGlPBzfp1gKDmaCwKWtXS/UI-KIT---Obelisco?m=auto&node-id=956-8466&t=p1qG5ar7TIdEIzEM-1) | [Ficha Figma](https://www.figma.com/design/Pi8vXNQiMDtCNvV1aTCQX7/Fichas?m=auto&node-id=4261-215186&t=dpetcnWNnI97E4T7-1) | [Estándares](https://gcba.github.io/estandares/componentes/modals/) | [Storybook](https://gcba.github.io/Obelisco/?path=/story/componentes-modal--default) 

**Ejemplo en Bootstrap**
[Modal](https://getbootstrap.com/docs/5.0/components/modal/)

**Ejemplos de aplicación en BA**
Página de trámites

**Comment by paulajoglar** [comment]
**Requerimiento:** se necesita compatibilizar la información brindada en el Storybook, UI KIT y web de estándares para el componente modal.

Se cambió en nombre del componente "modal" en librería por "modal de confirmación"

**Pendiente:**
revisión y actualización del branch

**Comment by aloyber** [comment]
@paulajoglar ¿por qué estamos especificando el modal de confirmación?¿debería haber varios tipos de modal? Si le cambiamos al nombre de modal de confirmación, vamos a estar sesgando todos los modales a modales con comportamiento de confirmación y talvez haya modales que no requieran este comportamiento. Ojo con esto. Revisemoslo.

**Comment by NatiOertel** [comment]
Requerimientos:

- Se requiere crear un único componente en UI KIT con sus respectivas variables para que pueda ser costumizado a elección

**Comment by NatiOertel** [comment]
Se analizaron ejemplos de modals de otros sistemas de diseño, como Carbono y Spectrum, para contemplar las necesidades básicas del componente en relación a su contexto de uso y las necesidades que pueden surgir a futuro.

Ejemplos:


![Image](https://user-images.githubusercontent.com/106767361/234629343-2da538cf-28cd-4df0-8e69-d2fefed934fe.png)


![Image](https://user-images.githubusercontent.com/106767361/234629445-01240b3c-26ac-4376-b2bc-f2b6644529a7.png)


![Image](https://user-images.githubusercontent.com/106767361/234629586-1df980b1-d13e-4143-8832-3c1a753b3baa.png)


![Image](https://user-images.githubusercontent.com/106767361/234629765-870b8c42-6a71-4be3-9e22-c1ba1d2eddc7.png)


![Image](https://user-images.githubusercontent.com/106767361/234629921-1a891661-6442-494b-89d0-a9f5cc982a60.png)


![Image](https://user-images.githubusercontent.com/106767361/234630016-aff0c4ef-f518-43b6-b5a6-11438359f73f.png)


![Image](https://user-images.githubusercontent.com/106767361/234630100-a2423cc6-b071-41a2-a5dd-0798081e67c9.png)


![Image](https://user-images.githubusercontent.com/106767361/234630169-fcadc88e-77d0-444f-a505-b7c71194913a.png)


![Image](https://user-images.githubusercontent.com/106767361/234630240-34277839-bd7b-4244-a8e7-933fec5b47f9.png)


![Image](https://user-images.githubusercontent.com/106767361/234630303-2b533d87-2fb7-4084-9405-c29328be582f.png)

**Comment by NatiOertel** [comment]
Antes:

![Image](https://user-images.githubusercontent.com/106767361/235933269-31000e0b-05a0-4876-bd73-7617dcd51074.png)


Después:

![Image](https://user-images.githubusercontent.com/106767361/235933376-cd7565d5-0a28-4ef2-a019-41897973836a.png)

**Comment by NatiOertel** [comment]
¿En qué se trabajó?:

- Se volvió a reestructurar el componente para que pueda ser customizado a elección a través de las variables y las moléculas que lo componen.
- Se agregó un tercer nivel de texto (volanta) para contemplar casos en los que sea necesario dar más información a la persona usuaria para que esta pueda tomar una decisión.
- Se asignó como H4 el título del componente para contemplar accesibilidad.
- Se mantuvieron los mismos espaciados y paddings en ambos dispositivos.
- Se consideró la posibilidad de agregar al modal un botón close (X), pero no se llevó a cabo debido a que sumar esta molécula implicaba que el ancho del componente se viera afectado. En desktop no había inconvenientes para modificar el ancho, pero en mobile superaba la medida mínima, impidiendo que quedaran márgenes a la izquierda y derecha de la pantalla.


![Image](https://user-images.githubusercontent.com/106767361/235935407-4968b582-6ac6-4e0a-b9a7-3b97883d7a38.png)

**Comment by camilagaldo** [comment]
Sobre la opción de que el modal se cierre cuando haces clic afuera, chequear una última vez cn Desarrollo y sumarlo a la ficha.

**Comment by camilembo** [comment]
Se ajustó la ficha en base al último comentario dejando todas las opciones de cierre del modal incluyendo "haciendo clic por fuera del modal"

**Comment by Diehault** [comment]
¡Hola! 🦭

Actualizamos el componente aprovechando la actualización general de la guía tipográfica. Encontramos también posibles evolutivos que nos parecen importantes.

### ¿Qué hicimos?
- Actualizamos la plantilla del componente en la librería del UI kit.
- Actualizamos los estilos tipográficos del componente.
- Actualizamos las propiedades del componente y la nomenclatura.

### ¿Qué consideramos como evolutivos?
- Hoy en día, tanto en la página web de Estándares, como en el Storybook, mostramos diferentes tipos de modales que no se ven reflejados en la plantilla del componente dentro del UI kit. Habría que analizar cuál es la mejor forma de sumar estos tipos o si hace falta sumar variantes al componente actual.
- Este componente quedará en revisión dentro del UI kit, porque también consideramos que hay cosas en la ficha técnica de la página web de Estándares que debemos repasar.

### ¿Qué comentarios dejamos en la página del componente?
![Image](https://github.com/user-attachments/assets/3a50c792-17af-4a98-9543-fbbeae637ee6)

### ¿Cómo se ve la ficha del componente en el UI kit?
![Image](https://github.com/user-attachments/assets/10839a3c-191a-41d5-804c-4a285c141e12)

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados


### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [ ] El componente se ajusta a la grilla 4px.
- [ ] El componente tiene una medida definida para mobile, tablet y desktop.
- [ ] El componente tiene una modulación definida para mobile, tablet y desktop.
- [ ] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [ ] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Se creó la variante para dispositivos Tablet con un ancho fijo de 336px equivalentes a 3-col
Arreglado | -
Eliminado | -
Obsoleto | -
Cambiado | -

## ✏️ Notas

- **[EV]**: Revisar la ficha del componente

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA).

## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Actualizamos el componente incluyendo la colección de variables con la nueva paleta de colores.<br>Sumamos la variante de "Modal de peligro" dentro del UI kit.
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | 

## ✏️ Notas
- El componente Modal nos sirvió para definir patrones de acción dentro de nuestros patrones de diseño. Al momento de revisar a profundidad los patrones de diseño, el Modal nos sirve como referencia.
