### ISSUE TITLE
Tarjeta vertical

### ISSUE THREAD

**Issue by paulajoglar** [gcba/estandares#232]
**Nombre en Obelisco:** tarjeta vertical
**Tipo de componente:** molécula
**Ejemplo en bootstrap:** 
**Ejemplo de aplicación en BA:** accesos a otras páginas

**Comment by paulajoglar** [comment]
**Requerimiento:** se necesita analizar la nomenclatura de los componentes pensando en su uso y escalabilidad.

Se propone cambiar el nombre de tarjeta noticias por tarjeta vertical con imagen y analizar la posibilidad de incluir la variante con reproductor de audio y video dentro de estas. Para esto, es necesario tocar la estructura del componente. 

**Pendiente:**

- Definir
- Actualizar el UI Kit
- Ajustar estas definiciones en estándares y storybook

**Comment by aloyber** [comment]
@paulajoglar Unificar en "Tarjeta", vertical y horizontal son las variables. Deberiamos tener toda la info en un solo lugar del componente.

**Comment by paulajoglar** [comment]
Se unifican "tarjeta vertical" y "tarjeta horizontal" en el siguiente issue: https://github.com/gcba/estandares/issues/240
