### ISSUE TITLE
Navegación y pestañas

### ISSUE THREAD

**Issue by aloyber** [gcba/estandares#234]
# Navegación y pestañas

**Nombre en Obelisco** 
Navegación y pestañas

**Tipo de componente** 
Molécula

**Ejemplo en bootstrap**
[Navs-Tabs](https://getbootstrap.com/docs/5.3/components/navs-tabs/)

**Ejemplo de aplicación en BA**
 Ayuda al usuario a navegar dentro de un sitio

**Comment by aloyber** [comment]
**Requerimiento:** Se necesita compatibilizar la información brindada en el Storybook, UI KIT y web de estándares para el componente de navegación. Además se requiere agregar el componente de pestañas para escalar el uso y funcionalidad.

- Se requiere hacer un cambio de nombre del componente a: Navegación y pestañas
- Se requiere agregar el componente de pestañas: simples / con contenedor
- Se requiere agregar una variable para las pestañas de ancho fijo / ancho variable
- Se requiere agregar diferentes tamaños de pestañas
- Se requiere hacer una modificación de la nomenclatura de las variables del componente de navegación para una mejor comprensión por parte de los usuarios de Obelisco
- Se requiere diferenciar en UI KIT los componentes de Paginación y Migas de pan para mostrarlos como componentes independientes

---

Se deja una imagen de referencia en cuanto a como se encuentra organizado y que se espera:

![Image](https://user-images.githubusercontent.com/65788688/219699124-93f70044-d0d6-4947-bd3d-a2cd353af5f1.png)

**Comment by aloyber** [comment]
Se agregó una branch en UI KIT para separar las páginas de Miga de Pan y Paginación de Navegación. Además se agregaron los respectivos componentes de Pestañas y se renombró el componente de Navegación a "Navegación y pestañas"
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/BnExXyHGaQePEwoeeacfN5/UI-KIT---Obelisco?node-id=659%3A8209&t=RUplhDQz77wOR5d5-1

**Comment by aloyber** [comment]
Se realizaron algunas modificaciones en los padding internos del componente "Navegación vertical"

Antes:
![Image](https://user-images.githubusercontent.com/65788688/219733485-cb50a7e6-3a60-4f44-9351-d9f04ca7c335.png)

- La relación entre la navegación de 1er nivel al tener ícono y la navegación de 2do nivel no es armoniosa y presenta confusión y desentendimiento en cuando a la percepción de la persona usuaria y genera un gran esfuerzo en entender que la segunda esta dentro de la primera.
- Asimismo pasa exactamente algo similar entre la 2da y la 3era navegación


Despues:
![Image](https://user-images.githubusercontent.com/65788688/219733610-69590e0f-96eb-4634-95da-9e32d2692407.png)

- Con la corrección de los padding internos del 2do y 3er nivel se arregla este error, generando al usuario una mejor percepción sobre cual pertenece a una agrupación de un nivel superior y cual no.
- **Padding izquierdo interno** de navegación en segundo nivel: 44px
- **Padding izquierdo interno** de navegación en tercer nivel: 72px

**Comment by aloyber** [comment]
Para los casos en donde la página requiere más pestañas o se necesita adaptar a un nuevo tamaño de navegador, las pestañas deben ser desplazables. Aparecen flechas izquierda y derecha para ayudar a navegar al usuario a través de pestañas que no son visibles en la página.

![Image](https://user-images.githubusercontent.com/65788688/219865524-c07705c6-e3ef-4d30-9b22-1dd5ab41bd3c.png)

**Comment by aloyber** [comment]
@victoriajustina @ncorralesruiz dejo el acceso a la ficha para una revisión de contenido https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/kYo54WHoHw3V95BTcHTuDF/Fichas?node-id=154%3A813&t=p8okRwR85htclUXC-1

**Comment by davisLjr** [comment]
![Image](https://user-images.githubusercontent.com/98839538/224114205-569ee52e-659c-4e54-b964-096f0a7acdba.png)

Creo que deberiamos agregar en pestañas una seccion para mostrar los que tienen icono tanto en simple como en los que tienen contenedor, tambien para mostrar las pestañas con desplazamiento

**Comment by davisLjr** [comment]
Definir en ficha que se puede usar el componente tabs con botones

**Comment by davisLjr** [comment]
Definir si el boton de inicio y fin se debe deshabilitar, desaparecer o quedar cuando llega al primer elemento o al ultimo

**Comment by davisLjr** [comment]
- [ ] Definir si se usara font-weight o text-shadow para cuando el elemento en pestañas este activo

- [ ] Ancho fijo: definir min width en diseño.

- [ ] Definir espaciados entre texto y el icono en la navegacion vertical, horizontal y pestañas seria ideal que sea el mismo en todos, mantiene armonia entre los diferentes tipos de navegacion.

- [ ]

**Comment by davisLjr** [comment]
Segun el figma de Analisis de componentes, se extienden las nuevas tipografias a los componentes, tambien se cambia el padding de la navegacion vertical y el box-shadow de pestañas pasa de ser externo a ser interno. 



![Image](https://github.com/gcba/estandares/assets/98839538/8050aa02-30ed-45f1-9d7c-6c163525ba7e)



![Image](https://github.com/gcba/estandares/assets/98839538/e84d0bfb-d7bf-4d0b-a268-147c954fa391)

El icono se confirmo con el equipo de diseño que este tendra una medida de 20 x 20 px, de manera que debe ser ajustado en UI-KIT.

Los estilos tipograficos para navegacion vertical, horizontal y pestañas en tamaños grande y mediano son los siguientes : 


![Image](https://github.com/gcba/estandares/assets/98839538/8e5af9fe-2719-43e3-82b1-1e3d30be434c)

Y para los tamaños pequeños "sm" : 


![Image](https://github.com/gcba/estandares/assets/98839538/7ee08812-a09e-4abb-88ea-1a149d1ba5dd)

**Comment by Diehault** [comment]
¡Hola! Reabrimos el ticket para actualizar con los últimos cambios que surgieron sobre la página de "Navegación y pestañas" dentro del UI Kit.

### Actualizaciones
- En el hilo de empatar lo que tenemos hoy en día disponibilizado en Storybook y lo que hace parte de nuestro UI Kit, actualizamos el tamaño de los íconos de todas las navegaciones ("Navegación vertical" y "Navegación horizontal").

### ¿Qué se hizo?
- Anteriormente, el ícono de las navegaciones era de 24x24 px., lo que cambió a 20x20 px. para empatarlo con el tamaño de ícono que tenía el componente en Storybook. Consideramos este cambio porque el nuevo tamaño proporciona mayor balance entre el texto y el ícono dentro del contenedor de la navegación.

### ¿Cómo se ven los componentes actualmente?

#### Navegación vertical
![Image](https://github.com/gcba/estandares/assets/144037453/bad60d9d-ab7e-41a7-b32a-d69d83af14aa)
_Recorte del tamaño del ícono visto desde el DevMode de Figma._

#### Navegación horizontal
![Image](https://github.com/gcba/estandares/assets/144037453/db20b534-a9a5-4ef5-af09-3332e0bcdb65)
_Recorte del tamaño del ícono visto desde el DevMode de Figma._

Con esto, logramos que se disponibilice el mismo componente y medidas para las herramientas de desarrollo y diseño.

**Comment by marusaad** [comment]
¡Hola! 🐱

Actualizamos el componente aprovechando la actualización general de la guía tipográfica.

### ¿Qué hicimos?

- Actualizamos la plantilla del componente en el UI kit.
- Actualizamos los estilos tipográficos del componente.
- Actualizamos la nomenclatura de las propiedades del componente y la jerarquía de las mismas.
- Cambios sobre el tamaño “Chico” de todos los componentes en la página: todos los componentes que tienen el tamaño “Chico” en la página tenían las siguientes propiedades de texto: tamaño de letra: 16px / Interlineado: 22px  Al cambiarlo a la variante de estilo correspondiente (Titulares S: 16px/20px), todos los componentes de este tamaño “Chico” perdieron altura y espacio como botones. Para equilibrar/balancear el cambio del interlineado con respecto al tamaño anterior, sumamos 4px de padding vertical (arriba y abajo), quedando así un padding vertical final de 8px.

### ¿Qué cosas consideramos como evolutivos?
Se recomienda revisar y volver a analizar este componente a nivel ux y accesibilidad. 



![Image](https://github.com/user-attachments/assets/aac37e39-a204-4de6-a1b3-e5317a802a22)

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] El componente tiene una modulación definida para mobile, tablet y desktop.
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Acordamos con el equipo de Desarrollo que, a partir del breakpoint de 768px hacia abajo, el organismo de "Menú vertical", compuesto por varias instancias del componente Navegación vertical, tendrá el mismo comportamiento que en mobile, ocupando el 100 % del width del contenedor mayor.
Arreglado | 
Eliminado | Eliminamos la variante _"Deshabilitado"_ del componente Navegación horizontal.
Obsoleto | 
Cambiado | El width de las pestañas de ancho fijo pasó a 253px, coincidiendo con la grilla.

## ✏️ Notas

- **[EV]**: pensar en el menú vertical compuesto por varias navegaciones como un organismo, algo que ya sucede naturalmente pero no está dentro del sistema de diseño.
- **[EV]**: revisar el comportamiento de las Pestañas para tablet y mobile.
- **[EV]**: pensar en el comportamiento de las navegaciones cuando hay pestañas/navegaciones subordinadas.

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA).

## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Actualizamos el componente incluyendo la colección de variables con la nueva paleta de colores.<br>Sumamos un ícono al lado izquierdo del componente Pestañas con sus respectivas propiedades booleanas y de swap.
Arreglado | 
Eliminado | Eliminamos la variante Deshabilitada del componente Pestañas.
Obsoleto | 
Cambiado | Cambiamos los íconos del componente Navegación y del componente Pestañas, a la izquierda con el "add" y a la derecha con un "arrow".

## ✏️ Notas
- **[EV]:** debemos revisar el espacio tapeable de la variante "Chica" de los componentes, que está por debajo de los 40 px. recomendados. Ahora mismo quedaría en 32 px. para que quede igual en todos los componentes, que usan 32 px. para la variante "Chica".
- **[EV]:** la variante _mobile_ para el Paginado Numerado no cumple con ninguno de los criterios de usabilidad y accesibilidad, por lo que estamos trabajando en una versión temporal que cubra las necesidades del componente y el producto.
