### ISSUE TITLE
Barra de progreso

### ISSUE THREAD

**Issue by aloyber** [gcba/estandares#236]
**Nombre en Obelisco:** Barra de progreso
**Tipo de componente:** Molécula
**Ejemplo en bootstrap:** https://getbootstrap.com/docs/5.3/components/progress/
**Ejemplo de aplicación en BA:** Visualizar el estado de una operación

**Comment by aloyber** [comment]
**Requerimiento:** Se necesita compatibilizar la información brindada en el Storybook, UI KIT y web de estándares para el componente de accesos.

- Se requiere cambiar la nomenclatura de las variables para una mejor comprensión

---

Se deja una imagen de referencia en cuanto a como se encuentra organizado y que se espera:
![Image](https://user-images.githubusercontent.com/65788688/218266760-e95571fe-2d20-47e3-ab69-5b71320030ff.png)

**Comment by paulajoglar** [comment]
Se creó un branch en el UI kit para trabajar el componente
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/28xf3UMJJ2qeHhRrVaAVh7/UI-KIT---Obelisco?node-id=2798%3A12566&t=FAC1PhNZoMGzrIq3-0

**Comment by paulajoglar** [comment]
¿En que trabajamos?
Se modificó la estructura del componente para que se adapta a los diferentes tamaños
Se cambió la nomenclatura
Se sumaron tres estados en el avance de la barra para indicar el avance del proceso

Antes

![Image](https://user-images.githubusercontent.com/106768801/222722650-7c02fe7a-59da-4172-abe2-42d4721b09a8.png)

Después


![Image](https://user-images.githubusercontent.com/106768801/222722720-da36b1f9-7c57-4779-8d8d-fdc0589dda7c.png)
![Image](https://user-images.githubusercontent.com/106768801/222722719-21d3d4e8-2369-41c7-b6ea-6d3caeb728ce.png)

**Comment by camilagaldo** [comment]
- Se realizó una revisión de la brunch y se dejaron comentarios para seguir avanzando. 
- Si bien hay un esbozo de la ficha, se mantiene en este parte del proceso porque requiere seguir trabajando sobre el componente.

@paulajoglar

**Comment by NatiOertel** [comment]
@victoriajustina dejo el acceso a la ficha para una revisión de contenido:

https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/me67uDBH1pmTRAYQwmIsyj/Fichas?node-id=534-812&t=YE88Qo7gFmnoV7CQ-0

**Comment by marusaad** [comment]
Se actualizaron los estilos tipográficos de la etiqueta del componente.

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 


### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [ ] El componente se ajusta a la grilla 4px.
- [ ] <s>El componente tiene una medida definida para mobile, tablet y desktop. </s> **[No incluye medida para dispositivos]**
- [ ] <s>El componente tiene una modulación definida para mobile, tablet y desktop. </s> **[No incluye modulación para dispositivos]**
- [ ] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [ ] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Cell
Arreglado | Cell
Eliminado | Cell
Obsoleto | Cell
Cambiado | Ajustamos el tamaño del componente a 4 columnas: 348px. A nivel producción, el componente responde al tamaño del contenedor mayor, no tiene un tamaño determinado.

## ✏️ Notas

- **[EV]**: Evaluar si es necesario incluir en el UI Kit la variante para distintos dispositivos.

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento


### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## ✏️ Notas
Se actualizaron los colores del componente con las nuevas variables y se actualizaron los colores de la plantilla del UI Kit.
