### ISSUE TITLE
Paginado

### ISSUE THREAD

**Issue by aloyber** [gcba/estandares#238]
Nombre en Obelisco: Paginado
Tipo de componente: Molécula
Ejemplo en bootstrap: https://getbootstrap.com/docs/5.3/components/pagination/
Ejemplo de aplicación en BA: Indicar que existe una serie de contenido relacionado en varias páginas

**Comment by aloyber** [comment]
**Requerimiento:** Se necesita compatibilizar la información brindada en el Storybook, UI KIT y web de estándares para el componente de paginado.

- Se requiere cambiar el nombre del componente a "Paginado"
- Se requiere cambiar la ubicación de donde se encuentra en UI KIT a una página separada para que se pueda encontrar de una manera mas rápida (no se espera encontrar dentro de la página de Navegación)
- Se requiere cambiar la nomenclatura de como esta dispuesta en Storybook

---

Se deja una imagen de referencia en cuanto a como se encuentra organizado y que se espera:
![Image](https://user-images.githubusercontent.com/65788688/219959563-c2a07e25-a384-4fc2-ba4e-ba65f4803803.png)

**Comment by aloyber** [comment]
Se creó una branch en UI KIT para actualizar el componente https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/BnExXyHGaQePEwoeeacfN5/UI-KIT---Obelisco?node-id=1950%3A12810&t=RAXuDgnmee91cDnE-1

---

¿En que se trabajó?

Antes:
![Image](https://user-images.githubusercontent.com/65788688/219959772-bf4b3f59-676e-462c-8d47-386f6fc50c51.png)

Después:
![Image](https://user-images.githubusercontent.com/65788688/219959780-036bb197-0678-4b86-aff1-6f1b3b907da0.png)
![Image](https://user-images.githubusercontent.com/65788688/219959803-225b94e5-c662-4f27-a337-438c3a450594.png)

- Se cambiaron las propiedades del componente en UI KIT
- Se cambio el nombre del componente

**Comment by aloyber** [comment]
@ncorralesruiz @victoriajustina Se deja la ficha actualizada para hacer revisión de contenido https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/DLk0gEtwMpBEYOq46UfcEE/Fichas?node-id=176%3A812&t=IH44sGhWGHML7956-1

- Se trabajo en una mejora y actualización de la ficha con más puntos de usabilidad y haciendo una mejor descripción del contexto de uso

**Comment by NatiOertel** [comment]
Se adjunta un ejemplo del componente en otro sistema de diseño de referencia: https://atlassian.design/components/pagination/examples

**Comment by victorianastasi** [comment]
Se trabajo sobre la propuesta mencionada en dispositivos de escritorio y móviles: 


![Image](https://user-images.githubusercontent.com/60082396/225980599-3ab08432-5635-47f2-9744-f67d50b3b606.png)


![Image](https://user-images.githubusercontent.com/60082396/225980844-914c4f5a-b56f-4c6a-9c8c-9aa6312b5127.png)

**Comment by paulajoglar** [comment]
Se creo en el UI KIT la versión mobile.

![Image](https://user-images.githubusercontent.com/106768801/228885652-4f19d3a3-ba30-4120-a7cb-62b02457a0a9.PNG)

**Comment by victorianastasi** [comment]
Se modifica componente en Storybook en rama _fix_pagination_ y se modifica ficha en Estándares, en rama _actualizacion_ficha_paginado_

**Comment by Diehault** [comment]
¡Hola! 📎

Actualizamos el componente aprovechando la actualización general de la guía tipográfica. Encontramos evolutivos a tener en cuenta a futuro para tomar el componente.

### ¿Qué hicimos?
- Actualizamos la plantilla del componente en la librería del UI kit.
- Actualizamos las propiedades del componente y su nomenclatura.
- Actualizamos los estilos tipográficos del componente.
- Cambiamos la iconografía que quedó fuera de versión por íconos de la librería de Material Design Icons.

### ¿Qué encontramos y consideramos evolutivos?
- El espacio tapeable/clickeable de los botones que hacen parte del componente es menor (actualmente es de 32px) al tamaño recomendado (entre 40px y 44px), por lo que en la versión Mobile puede verse afectada la usabilidad. Habría que revisarlo y determinar si nos parece correcto el tamaño actual.

### ¿Qué dejamos anotado en la página del componente en el UI kit?
![Image](https://github.com/user-attachments/assets/d6c77629-28ff-464a-86a6-8ca57afdbb8e)

### ¿Cómo se ve la ficha del componente en la librería del UI kit?
![Image](https://github.com/user-attachments/assets/6a38ee1d-1588-4268-b8b4-17bc49ea5b73)

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#212 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] El componente tiene una modulación definida para mobile, tablet y desktop.
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | v.0
-- | --
Agregado |  
Arreglado | asda<br> Es
Eliminado | Cell
Obsoleto | Cell
Cambiado | Para dispositivos Desktop modificamos el tamaño de los contenedores de los números, así como también de los controladores, de 35x40px  →  48x44px

## ✏️ Notas

- **[EV]**: 

### Para dispositivos Mobile
- El componente actual no cumple con los criterios mínimos de accesibilidad.
- Revisar la disposición del componente y evaluar otras alternativas que refuercen la usabilidad del componente.

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Incluimos el estado “Deshabilitado” en el componente base (.Ítems-Paginado). <br> Se definieron variantes por tipo y dispositivo: Numerado, Descriptivo y Único para Desktop, Tablet y Mobile. <br> Establecimos max-width para cada dispositivo y establecimos medidas y alineaciones default. 
Arreglado | Aplicamos auto-layout al componente total y también dividimos en otro auto-layout los botones de número de página. 
Eliminado | Eliminamos la variante "numerada" para mobile porque implicaba muy poca área tappeable, generando problemas de usabilidad y accesibilidad. Para este dispositivo sólo existirá la variante Descriptivo. 
Obsoleto | 
Cambiado | 

## ✏️ Notas

La actualización de color de este componente incorporó algunas **mejoras de usabilidad a modo de parche** hasta tomar el componente para un análisis completo. Se marcó el componente con la etiqueta "en revisión" para indicar que debe ser tomado más adelante porque presenta problemas constructivos y falta research en cuanto a usabilidad y accesibilidad. A nivel código, se maquetan las variantes numerado y descriptivo de forma idéntica para que al pasar al breakpoint de mobile se vea como una variante única. Desarrollo continuaría teniendo las 2 variantes.
