### ISSUE TITLE
Desplegables

### ISSUE THREAD

**Issue by NatiOertel** [gcba/estandares#239]
Nombre en Obelisco: Desplegable
Tipo de componente: Molécula
Ejemplo en bootstrap: https://getbootstrap.com/docs/5.3/components/dropdowns/
Ejemplo de aplicación en BA: Filtros desplegables

**Comment by NatiOertel** [comment]
**Requerimientos:**

**Comment by NatiOertel** [comment]
Se creó un branch en el UI KIT para trabajar el componente:
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/rin6WGTM7POZgLsoGvzsQN/UI-KIT---Obelisco?node-id=870%3A7997&t=hlfoeKhEK6Kkvs7G-0

**Comment by NatiOertel** [comment]
¿En qué trabajamos?

- Se eliminó la variable booleana "Mostrar_cheuron" y se la reemplazo por la variable "Mostrar_icono"
-  Se agregó una variable para elegir el ícono que mostrará el desplegable
- Se definió

**Comment by camilagaldo** [comment]
- Se realizó una revisión de la brunch del UI Kit y se dejaron comentarios para analizando en conjunto. Son mini comentarios porque viene re encaminado, tmb ahí quedaron comentarios de la ficha.

@NatiOertel

**Comment by NatiOertel** [comment]
Se retoma el análisis del componente, teniendo en cuenta que el mismo cuando se despliegue debe mostrar otro componente, llamado opciones, el cual también requiere de un análisis para conformar los desplegables.

**Comment by NatiOertel** [comment]
Se analizaron ejemplos de desplegables y el funcionamiento de los mismos en otros sistemas de diseño para contemplar las necesidades básicas del componente en relación a su contexto de uso y las necesidades que pueden surgir a futuro.

Ejemplos:

![Image](https://github.com/gcba/estandares/assets/106767361/9020c402-c6c0-4565-99c4-83e6f0d20461)


![Image](https://github.com/gcba/estandares/assets/106767361/af13233b-862c-4859-89ff-e9e459657b06)
![Image](https://github.com/gcba/estandares/assets/106767361/17893d40-fc2c-4738-9d29-e1d0868d37a5)


![Image](https://github.com/gcba/estandares/assets/106767361/53160372-3e8a-4be5-95ba-fc403fe08386)

![Image](https://github.com/gcba/estandares/assets/106767361/09d50911-b4d7-47b9-90ae-64915b7d2ef0)


![Image](https://github.com/gcba/estandares/assets/106767361/aa85605f-a552-4de9-9a52-623f88cc705f)

![Image](https://github.com/gcba/estandares/assets/106767361/48bd36f5-7cc9-438a-916f-c9f1b39d8bd4)


![Image](https://github.com/gcba/estandares/assets/106767361/39d110ae-25b9-4b57-991c-2f94daf12254)

**Comment by NatiOertel** [comment]
**Requerimientos:** Se necesita compatibilizar la información brindada en el Storybook, UI KIT y web de estándares para el componente de desplegable.

- Se requiere analizar ejemplos y el funcionamiento del componente.
- Se requiere crear en Storybook pestañas para desplegables sin borde y con borde.
- Se requiere eliminar de Storybook las pestañas "Desplegable solo ícono" y "Desplegable enlace", ya que las mismas pueden describir otro tipo de componente.
- Se requiere sumar en el apartado Organismos de Storybook una pestaña llamada "Desplegables combinables" y dentro otras 2 pestañas más que muestren la combinación de desplegables con botones y con navegación horizontal.
- Se requiere modificar la tipografía de los desplegables que conforman el organismo "Filtro desplegable" por Nunito 16px en el UI KIT.
- Se requiere modificar la tipografía de los desplegables (molécula) para que todos tengan Nunito regular.
- Se requiere corregir la ortografría del cuarto desplegable que conforman el organismo "Filtro desplegable" por "Todos los días" en el UI KIT.
- Se requiere definir el contenido que desplegará el componente, pudiendo ser opciones de selección única, opciones de selección múltiple y enlaces.

**Comment by NatiOertel** [comment]
Se analizaron ejemplos de desplegables y el funcionamiento de los mismos en otros sistemas de diseño para contemplar las necesidades básicas del componente en relación a su contexto de uso y las necesidades que pueden surgir a futuro.

**Sistemas de diseño consultados:**
Carbon Design System: https://carbondesignsystem.com/
Spectrum: https://spectrum.adobe.com/

**Ejemplos:**

![Image](https://github.com/gcba/estandares/assets/106767361/a2260708-92fa-4e0a-83cd-77dc78e37fde)


![Image](https://github.com/gcba/estandares/assets/106767361/d6ff9cd4-1daa-4251-85be-a36f05ba39e6)
![Image](https://github.com/gcba/estandares/assets/106767361/1ec5d178-f1bd-4a20-a41a-b0a8235d295f)


![Image](https://github.com/gcba/estandares/assets/106767361/553258fa-3563-4a68-8d4d-eb8db03e95bf)
![Image](https://github.com/gcba/estandares/assets/106767361/1f9a640d-3454-4701-ad04-869b00f9d970)


![Image](https://github.com/gcba/estandares/assets/106767361/bc910b2b-bbba-4035-afff-5408ce52bc82)
![Image](https://github.com/gcba/estandares/assets/106767361/9f2017d9-38a4-4929-9ca3-86a9b8e2ca39)


![Image](https://github.com/gcba/estandares/assets/106767361/6b86c18b-6fb6-42f4-8ad7-69658024b2bf)


![Image](https://github.com/gcba/estandares/assets/106767361/b6a84aa0-769b-482b-877b-4439e412c99a)
![Image](https://github.com/gcba/estandares/assets/106767361/f31424eb-4ed7-4859-8495-f7ce3e724995)
![Image](https://github.com/gcba/estandares/assets/106767361/b5d7edff-c708-432d-b76e-087d98f85aea)


![Image](https://github.com/gcba/estandares/assets/106767361/e68393fd-43a6-49a4-bbff-d7021f5c2203)


![Image](https://github.com/gcba/estandares/assets/106767361/0c571412-6d4c-4b4f-b6da-97094044ff9d)


![Image](https://github.com/gcba/estandares/assets/106767361/f18635ad-9fbb-46ea-bc10-67f930f01337)


En base a este análisis se determinó que:

- Los desplegables pueden mostrar opciones de selección única y selección múltiple. Avanzamos con esto.
- Los desplegables de tipo Caja combo necesitan un análisis más profundo respecto a su funcionalidad y dependiendo las necesidades que vayan surgiendo, se sumarían después al UI KIT.
- Los desplegables deben tener el mismo alto que otros componentes, como botones o navegación horizontal.
- El componente Opciones debería estar en la página de desplegables. Por lo tanto, se elimina la página del componente en el UI KIT, así como también en storybook y la web de estándares.
- Los radio button y checkbox que queden sueltos como moléculas quedan únicamente en Formularios.

Por otro lado, surgió la posibilidad de sumar otro componente de manera individual, el cual es menú desplegable. Este componente se comporta como un desplegable, pero su funcionalidad está más relacionada a la navegación de un sitio. Se continuará con su análisis más adelante.

**Comment by NatiOertel** [comment]
Se creó un branch en el UI KIT para trabajar el componente:
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/rin6WGTM7POZgLsoGvzsQN/UI-KIT---Obelisco?node-id=870%3A7997&t=hlfoeKhEK6Kkvs7G-0

**Comment by NatiOertel** [comment]
¿En qué trabajamos?

**Desplegables:**

- Se eliminó la variable booleana "Mostrar_cheuron" y se la reemplazo por la variable "Mostrar_icono".
- Se agregó una variable para elegir el ícono que mostrará el desplegable.
- Se agregó una variable booleana para mostrar el ícono de los desplegables.
- Se renombró el estado "desplegable" por "expandido".
- Se renombró la variable "Borde" por "Estilo".
- Se ajustó el padding y el tamaño del ícono y del cheuron del desplegable chico para que tenga un alto de 30 px y coincida con el alto de los botones chicos y navegación chica al ser combinados.
- Se ajustó la separación que existe entre las opciones para mejorar la visualización del componente cuando este expandido. Este valor era 4px y ahora es 5px.
- Se le designó la tipografía Nunito 18 regular a los desplegables grande y mediano, y Nunito 16 regular a los desplegables chicos.
- Se cambió el nombre de la página “Filtros” en Organismos por “Desplegables”.

**Opciones:**

- Se definió que las opciones que se muestran en el estado desplegable del componente sean opciones de selección única y opciones con checkbox para selección múltiple.
- Se eliminó el estado activo de las opciones para desktop porque ese estado hace referencia a botones.
- Se agregó el estado deshabilitado.
- Se eliminó el estado en_foco de las opciones para mobile ya que dicho estado no corresponde a ese dispositivo.
- Se eliminaron las opciones con y sin ícono debido a que no es una buena práctica utilizar dicho atributo dentro de un desplegable.
- Se agregó un ícono de check a la derecha de las opciones de selección única para identificarlas cuando tengan estado seleccionado.
- Se volvió a construir el componente para que se pueda customizar a elección a través de sus variables
- Se elimina la página opciones del UI KIT debido a que en formularios ya contamos con las moléculas de opciones sueltas (radio button y checkbox).
- Se agregaron tres tamaños de opciones: grande, mediano y chico, para que coincidan con el tamaño del desplegable cuando el mismo esté desplegado.


**Antes:**

IMAGENES


![Image](https://github.com/gcba/estandares/assets/106767361/415a49f6-34a4-42df-99db-ebc672fe7798)




**Después:**

![Image](https://github.com/gcba/estandares/assets/106767361/6e8b7364-260f-41d0-9759-a603bc01a5dd)


![Image](https://github.com/gcba/estandares/assets/106767361/c09b3c0e-a5bb-4a9a-bf81-fc3dbdd64516)


![Image](https://github.com/gcba/estandares/assets/106767361/798a2e65-1a45-44fe-b43b-a97299285d42)

![Image](https://github.com/gcba/estandares/assets/106767361/7d9d9a78-7701-4712-a961-60a30deda16b)
