### ISSUE TITLE
Ajustar buenosaires.gob.ar/estandares

### ISSUE THREAD

**Issue by julianrod** [gcba/estandares#24]
Entender si debe redirigir directamente a gh-pages o si queda en buenosaires.gob.ar y linkea a la nueva documentación.

**Comment by Vpappacena** [comment]
Objetivo: Rediseñar  la web de estándares. La web debe explicar para qué existe ese espacio, cuál es el servicio que brinda experiencia digital. Y  poder permitir que cada persona que construya un producto dentro del ecosistema de diseño encuentra lo que necesita para construirlo
