### ISSUE TITLE
Iconografía

### ISSUE THREAD

**Issue by paulajoglar** [gcba/estandares#249]
Nombre en Obelisco: Iconografía
Tipo de componente: átomo
Ejemplo de aplicación en BA: botones, accesos, etc.

**Comment by paulajoglar** [comment]
Se creo un branch para trabajar los tamaños de la iconografía descriptiva ya que difería de las con ícono. 
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/3ycB93U0kXB6at7F8DKLZ2/UI-KIT---Obelisco?node-id=618-8341&t=TDt2D2wjNuRNarKP-0

**Comment by Diehault** [comment]
¡Hola! 🦛

Muevo este ticket para la columna de "Archivado" porque tiene información sobre algo que se trabajó sobre iconografía, pero no es el ticket sobre el que estuvimos cargando información recientemente. Como hay 2 tickets para una misma página, decidimos tomar el que tenía información más reciente para seguir cargando información y este lo dejamos en el archivo.
