### ISSUE TITLE
Listas - Lista de pasos

### ISSUE THREAD

**Issue by lautarorodriguez96** [gcba/estandares#250]
Paso de tramite
Nuevo componente
Armar propuesta como componente y no como un organismo.
Link: https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/UI-KIT---Obelisco?node-id=618%3A8344&t=M0RtjuyCsM6RxM43-0

**Rama en la que se realizo el componente:** feat_tramites

Observacion: Solamente por el momento se va a maquetar el color grisulado, sacando el color azul y verde. 

![Image](https://user-images.githubusercontent.com/70086268/219031098-e5ee8e2b-a5eb-4246-b018-05d38be6c89b.PNG)

**Comment by JuaneRambosio** [comment]
**✏ EL COMIENZO**
Junto con Maru Saad, el día Viernes 16/06 comenzamos un análisis de los componentes que se encuentran en la página: “Listas / Pasos” y buscamos referencias de otros Sistemas de diseño.
En este análisis evidenciamos que hay componentes que deberían ser variables de otros (creados en sus respectivas páginas como por ejemplo “Desplegables”, “Accesos”, entre otros.)
También vimos que hay algunos componentes similares pero que cambian su contexto de uso, funcionalidad y estados. 


**🔦 PRÓXIMOS PASOS**
En función de ésta tarjeta: “Paso de trámite” decidimos avanzar con este componente, el cuál iremos armando la propuesta.

![Image](https://github.com/gcba/estandares/assets/134321929/d11f9542-9635-4f74-9f27-5a90b3a7a03e)

**Comment by marusaad** [comment]
Hoy Miércoles 21/06 con @JuaneRambosio arrancamos a trabajar en la propuesta de Paso de trámite. 

En principio, estamos pensando una nueva nomenclatura y organización de la página Listas/Pasos. 

Además, consideramos trabajar en las siguientes variables de "Paso del trámite":
- Tamaño (grande, mediano, chico) que incluye tanto al círculo como al texto
- Con relleno y con trazo
- Con número y sin número 
- Se mantiene el trabajo sólo en Grisulado como estipula el requerimiento.

**Comment by JuaneRambosio** [comment]
Junto a @marusaad estuvimos realizando las propuestas de las (por ahora nomenclada) "Progresión de pasos" en sus versiones: Mobile y desktop con las variantes:
**- Con relleno:** grande/mediana/chica
**- Con trazo:** grande/mediana/chica
**- Con relleno y número:** grande/mediana/chica
**- Con trazo y número:** grande/mediana/chica

Por otro lado, estuvimos generando algunas preguntas para debatir con el equipo de Desarrollo respecto a:
- Posibilidad de unir el círculo con el rectángulo
- Posibilidad de una variante del componente que sea del "último ítem" (que no tenga el rectángulo)
- Posibilidad de variar el trazo según la variante

![image](https://github.com/gcba/estandares/assets/134321929/7280fe03-befd-4722-a250-47987b0ddc4b)

**Comment by marusaad** [comment]
💫 Seguimos trabajando esta semana junto a @JuaneRambosio en el componente de progresión de pasos, y encaramos los siguientes temas: 

⏰ **PROGRESIÓN DE PASOS (Por ahora, EX “Pasos del trámite”)**
Durante la semana estuvimos trabajando junto al equipo de desarrollo en analizar varias cuestiones, entre ellas:
- Distancias entre cada Instrucción
- Distancias entre el círculo y el título
- Alineación del número dentro del círculo y el título
- Tamaños del rectángulo que acompaña el círculo según tamaño del componente
- Agregar stroke para algunos círculos y variación del tamaño según tamaño de éste
- Componentizamos todos y a partir de ésto y el feedback del equipo de desarrollo tuvimos y tenemos que evaluar de pensar otras variables: ya sean con enlace, subpasos en formato lista (ver próximos pasos)
- Comenzamos a relevar algunas buenas prácticas de otros sistemas de diseño para añadir en la Ficha.


📝 **DEFINICIONES**
- El círculo y el rectángulo quedan unidos (antes tenían una pequeña separación). La definición fue hecha en función del relevamiento sobre otros sistemas de diseño en los que se muestran de esta manera.

🔦 **PRÓXIMOS PASOS**
- Necesitamos una branch de la Ficha con acceso a Juane y Maru
- Nomenclar/Renombrar: Page, componente, otros componentes dentro de la Page
- Evaluar que iría dentro de esta Page: lista informativa, etc.
- Tomar decisiones respecto a algunas definiciones tales como:
              - Todos los pasos deben tener un título y una bajada con una breve descripción. No pueden haber pasos que tengan sólo título.
              - Instrucciones/Bullet con enlace, subpasos. En caso de que tengamos que usar Enalces ese componente hoy en día está hecho pero en una Brunch
- Diseñar Ficha:
              - Buscar en otros design systems las buenas y malas prácticas
              -  Usos de cada tamaño y variante. (Ej. Tamaño depende de cantidad de pasos, cantidad de texto, público usuario, etc)
              -  Uso de la lista del componente de paso (que van pegados con 0px de espaciado) 

🤔  **OTRAS CUESTIONES**
- Ver si podemos configurar que el paso por default al arrastrar desde assets sea Desktop/Grande/Con relleno/Sin número
- Dejamos para ver en la Daily del Lunes algo charlado con el equipo de desarrollo sobre el requerimiento en función de la UX en el Inicio del trámite (aplica también para el “Template de trámites“ que estuvo trabajando Juane
- ¿Cómo debería ser el proceso para levantar algún requerimiento que encontremos sobre la marcha? Ejemplo: En la Daily del 30/Junio vimos que el componente “Bloque: Iniciar trámite” no está hecho para Mobile.

<img width="205" alt="Captura de Pantalla 2023-06-30 a las 16 35 36" src="https://github.com/gcba/estandares/assets/136834096/f8fdd306-6da8-4115-af1b-7a07bf6be245">

<img width="225" alt="Captura de Pantalla 2023-06-30 a las 16 35 54" src="https://github.com/gcba/estandares/assets/136834096/0b502569-122c-4ec5-bc51-aaa7c00a1760">

<img width="690" alt="Captura de Pantalla 2023-06-30 a las 16 36 11" src="https://github.com/gcba/estandares/assets/136834096/c6ed3f5d-97d0-4e29-bc08-43c7b403bca4">

**Comment by marusaad** [comment]
Con @JuaneRambosio continuamos avanzando sobre la ficha del componente Lista de pasos. 

- **Análisis de lo que entraría en esta “Page”:**

Estuvimos analizando todos los componentes que estaban actualmente en “Lista / Pasos” y vimos que la mayoría corresponden a otros componentes, variables de esos componentes o son organismos. Dejamos todo ésto en una “section” llamada “No está relacionado”.

![No está relacionado](https://github.com/gcba/estandares/assets/136834096/49aa99c4-5dad-47cf-90ee-6c2a4509e868)

- En función de este análisis los componentes que quedaran dentro de la nueva “Page” que llamaremos **“Listas”** serán: 
      - Lista de pasos
      - Lista con íconos (éstos quedarán en el backlog para tomar llegado el momento de priorizarlo, pero es necesario dejarlo asentado para que se sepa que se va a encontrar acá). Respecto al backlog de la lista de ítems, adjuntamos imagen por si se precisan algunos textos y definiciones a futuro. 
      
![Backlog](https://github.com/gcba/estandares/assets/136834096/3576e93f-8f98-4cfd-b97a-0d90189b2b2c)
- Finalizamos con el relevamiento y análisis de otros sistemas de diseño respecto al uso que se le da al componente y en función de eso avanzamos con la Ficha (_pendiente de validación_) 

- Barra de progreso: queda como un componente separado

- Paso a paso: queda en el backlog pendiente de análisis. 


![Lista de pasos](https://github.com/gcba/estandares/assets/136834096/750f2b71-7ad4-4b94-80cb-3498f98b54a3)

**Comment by marusaad** [comment]
Con @JuaneRambosio dimos los últimos toques al componente Lista de pasos. 

**COMPONENTE**
- Resolvimos el problema del último paso (sin línea y sin bottom padding inferior de 24px) quitando la propiedad booleana "Mostrar línea" para reemplazar por una nueva propiedad llamada "Orden", y sus valores son "Por defecto" (primeros pasos y pasos intermedios) y "Último paso". 
- Creamos una branch en el UI Kit que se llama "Listas" donde actualmente está "Lista de pasos" (a futuro en esta page también iría el componente de "Lista de ítems"). El resto del análisis y componentes quedó en la branch "Listas / Pasos" en la page "Listas / Pasos (análisis)".
- Se tomó la decisión de que el componente "Paso a paso" esté por fuera de "Listas". 

**FICHA**
- Quedaba definir la nomenclatura de la page y de la ficha en sí. Decidimos nombrar a la dos "Listas". 
- En un futuro, en esta ficha, se sumará el componente "Lista de ítems". 

Queda pendiente a validar por **La doble C** @camilembo @camilagaldo 😎. 
Aguardamos cualquier tipo de feedback 



![Image](https://github.com/gcba/estandares/assets/136834096/8b7a00e9-372c-4a61-b052-82698fa0627d)

**Comment by JuaneRambosio** [comment]
Hola! con @marusaad estuvimos trabajando en los temas:

- **Sobre los tamaños de los componentes según dispositivo:** El componente Mobile lo hicimos "responsive" ya que tenemos *2 grillas posibles para este dispositivo (360px y 412px) de todas formas el componente siempre tiene que ocupar la totalidad de las columnas.

![Image](https://github.com/gcba/estandares/assets/134321929/b62ed3d5-19a3-4601-9c4b-165239ca90e1)

* *Sobre grilla: No coinciden las grillas de la web de estándares y lo que está en el UI-KIT. Tampoco vemos que exista una ficha para grilla. Lo levantamos por si necesitamos crear una tarjeta.

![Image](https://github.com/gcba/estandares/assets/134321929/66d0c662-867e-4895-933e-0bcc570fd994)

- **Sobre el componente por contraste**

![Image](https://github.com/gcba/estandares/assets/134321929/e8ada422-e733-473c-98f1-04c7d1c50f07)


Esperamos validación. @camilembo

**Comment by camilembo** [comment]
Genialísimo! Lo pasamos a para maquetar.
Ya creé una tarjeta de grilla en backlog para que lo tomemos así empatamos las grillas en todos lados. Le pregunté ayer a Lauti a ver ellos cómo tenían la grilla así estamos todos en la misma, me confirma hoy (creo) cuántas columnas tienen en mobile ellos en desarrollo.

**Comment by JuaneRambosio** [comment]
Pasé el análisis que hicimos con @marusaad al [archivo de figma pertinente](https://www.figma.com/file/mqy6dUBWeK47l1CMIYCdkX/Documentaci%C3%B3n-de-componentes?type=design&node-id=412%3A1264&mode=design&t=ViAa4EKu1JfaFXSj-1) (_Documentación de componentes>Listas_)

**Comment by camilagaldo** [comment]
Se realizó el merge en el UI Kit el 27/07/2023

**Comment by camilembo** [comment]
Tenemos que ajustar y agregar instancia de texto en el componente :)

**Comment by marusaad** [comment]
- Se incorporaron instancias de texto para los títulos del paso y sus descripciones dentro del UI Kit. 
- Se incorporó descripción del componente y link a documentación



![Image](https://github.com/gcba/estandares/assets/136834096/3dfcd03b-d0f5-4530-9954-c7b5d296c646)


@camilembo con esto ya puede pasarse a completado

**Comment by camilembo** [comment]
Gracias Maru!
Merge de estos ajustes hecho el 29/09 :)

**Comment by marusaad** [comment]
¡Hola! 🦀

Se actualizaron los estilos de texto del componente con la nueva escala tipográfica y incorporó la nueva plantilla para el UI Kit separando los componentes base.


![Image](https://github.com/user-attachments/assets/f273c078-9d74-48bb-bd73-45f7094e517e)

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [ ] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] <s>El componente tiene una modulación definida para mobile, tablet y desktop</s>. **No aplica para este componente**
- [x] <s>El componente tiene su handoff para desarrollo y está marcado como ready for dev</s>. **No aplica para este componente**
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | Width de la variante desktop a 728px.

## ✏️ Notas

- **[EV]**: se puede sumar una variante tablet, como para tener un tamaño predeterminado por dispositivo. Sin embargo, no es algo que consideremos necesario/obligatorio, porque se compra como texto en dispositivos móviles, al 100 %.

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado |  Se actualizó el color del componente con la nueva paleta de colores.

## ✏️ Notas
Actualizamos los colores de la plantilla del componente con la nueva colección de variables.
