### ISSUE TITLE
Definir detalles formales (sombras)

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#26]
- Construir los estándares del uso de los detalles formales teniendo en cuenta la usabilidad y accesibilidad del producto

**Comment by Fcunsolo** [comment]
[Pendiente revisión]
Comparto aproximación a detalles formales rectores del Sistema de Diseño Obelisco.

@aloyber @mathiassassone1 @Vpappacena 
[DETALLES-FORMALES-20200717.pdf](https://github.com/gcba/estandares/files/4939559/DETALLES-FORMALES-20200717.pdf)

**Comment by Jinik** [comment]
Lo escribí un poco en #31, pero habría que tener en cuenta acá el tema la elevación de como hover para contenedores.

**Comment by Fcunsolo** [comment]
[Pendiente revisión]
Comparto actualización de detalles formales rectores del Sistema de Diseño Obelisco.

@aloyber @mathiassassone1 @Vpappacena
[DETALLES-FORMALES-20200814.pdf](https://github.com/gcba/estandares/files/5077343/DETALLES-FORMALES-20200814.pdf)
