### ISSUE TITLE
Desplegable de selección

### ISSUE THREAD

**Issue by NatiOertel** [gcba/estandares#261]
# Desplegable de selección
**Nombre en Obelisco**
Desplegable de selección

**Tipo de componente**
Molécula

**Referencias de Bootstrap**
[Dropdown](https://getbootstrap.com/docs/4.6/components/dropdowns/)

**¿Qué tenemos en Obelisco actualmente?**
[Desplegables de selección en Estándares](https://gcba.github.io/estandares/componentes/desplegables/desplegables_seleccion/)

**Comment by NatiOertel** [comment]
**Requerimientos:** Se necesita compatibilizar la información brindada en el Storybook, UI KIT y web de estándares para el componente de desplegable.

Se requiere analizar ejemplos y el funcionamiento del componente.
Se requiere crear en Storybook pestañas para desplegables sin borde y con borde.
Se requiere eliminar de Storybook las pestañas "Desplegable solo ícono" y "Desplegable enlace", ya que las mismas pueden describir otro tipo de componente.
Se requiere sumar en el apartado Organismos de Storybook una pestaña llamada "Desplegables combinables" y dentro otras 2 pestañas más que muestren la combinación de desplegables con botones y con navegación horizontal.
Se requiere modificar la tipografía de los desplegables que conforman el organismo "Filtro desplegable" por Nunito 16px en el UI KIT.
Se requiere modificar la tipografía de los desplegables (molécula) para que todos tengan Nunito regular.
Se requiere corregir la ortografría del cuarto desplegable que conforman el organismo "Filtro desplegable" por "Todos los días" en el UI KIT.
Se requiere definir el contenido que desplegará el componente, pudiendo ser opciones de selección única, opciones de selección múltiple y enlaces.

**Comment by NatiOertel** [comment]
Se comienza el análisis del componente, teniendo en cuenta que el mismo cuando se despliegue debe mostrar otro componente, llamado opciones, el cual también requiere de un análisis para conformar los desplegables.

**Comment by NatiOertel** [comment]
Se creó un branch en el UI KIT para trabajar el componente:
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/rin6WGTM7POZgLsoGvzsQN/UI-KIT---Obelisco?node-id=870%3A7997&t=hlfoeKhEK6Kkvs7G-0

**Comment by camilembo** [comment]
Se revisó el componente de desplegable y se llegó a las siguientes conclusiones:
- La variante “seleccionado” en la opción de selección única no debería tener el número entre paréntesis ya que no se puede seleccionar más de una opción. 
En base a este punto se definió crear una propiedad booleana para poder activar o desactivar el número en el caso que corresponda.


![Image](https://github.com/gcba/estandares/assets/137331016/95af0459-1db6-4cec-b859-005af12b2355)


- Se definió que el contenido que tenga el desplegable debe ser corto y conciso. El ancho máximo de este componente será de 4 columnas, si el contenido excede este ancho se verá truncado el texto cortando la última palabra y agregando tres puntos que denoten la continuidad de dicha información.

- se modificó la ficha en base a estos cambios también.


![Image](https://github.com/gcba/estandares/assets/137331016/46e1814e-00a2-40c6-9576-2c6c1d4a273e)

**Comment by Diehault** [comment]
¡Hola! Actualizo con lo último que se estuvo viendo para el componente. 😸

### Actualizaciones
- Cambiar las propiedades de "adaptación" del contenido porque, con las propiedades actuales, el componente se rompía al duplicarlo desde los assets de la librería de Figma.
- Cambiar el componente de "caja-seleccionable", que actualmente hace de checkbox, por el nuevo componente "Casilla de verificación".

### ¿Qué se ha hecho hasta ahora?
- Actualizamos las propiedades del contenedor de opciones del desplegable para que no se rompiera al duplicarlo desde los assets de la librería de Figma.

![Image](https://github.com/gcba/estandares/assets/144037453/a2c13375-5a42-4a3e-984c-03ad6539c395)
_Así se deberían ver todos los ítems seleccionables dentro de un desplegable de selección._

Por ahora, se pausó el trabajo del componente para continuar con las guías de estilos del sistema de diseño, en pro de lanzar un versionado grande con cambios significativos.

Link a la branch del componente: https://www.figma.com/design/ToGlPBzfp1gKDmaCwKWtXS/branch/UK6uuC9GKvo39PpYqZRnRF/UI-KIT---Obelisco?m=auto&node-id=9833-20025&t=UQ6WBFgg8CGrKFtu-1.

**Comment by Diehault** [comment]
¡Hola! 🐊

Actualizo con la información sobre lo último que trabajamos en los desplegables de selección.

### ¿Qué se hizo?

- **Actualizamos la plantilla del componente en el UI Kit:** actualizamos la ficha técnica del componente en el UI Kit con el nuevo formato.
- **Renombramos propiedades internas del componente (instancias, variantes, etc.):** corregimos el cómo estaban escritas las propiedades internas del componente y el orden en el que aparecían. También, cambiamos el nombre del componente y de su componente base para encontrarlo en la librería del UI Kit con mayor facilidad.

### ¿Cómo se ve ahora la branch de Desplegable de selección?

![Image](https://github.com/gcba/estandares/assets/144037453/668a87df-32f5-4d47-b4eb-ad396102123d)
Link a la branch: https://www.figma.com/design/ToGlPBzfp1gKDmaCwKWtXS/branch/UK6uuC9GKvo39PpYqZRnRF/UI-KIT---Obelisco?m=auto&node-id=21446-2501&t=zNH38Rm0bXSEtaN6-1.

Esta actualización va de la mano con la actualización anterior, donde cambiamos las propiedades del autolayout del componente para evitar que se rompa cuando lo importan desde la librería de assets del UI Kit.

**Comment by marusaad** [comment]
¡Hola! 👋

Actualizamos el componente aprovechando la actualización de los estilos tipográficos. 

## ¿Qué hicimos?

- Actualizamos los estilos tipográficos
- Cambiamos los íconos-componente viejos provenientes de la page de iconografía por los íconos de la librería de Material Design. 
- Cambiamos el ícono default de "person" a "info", para estar en línea con los íconos predeterminados/agnósticos que mostramos en los demás componentes y que no se confunda el desplegable de usuario de la navegación con el de selección. 
- Se ajustó la nomenclatura y orden las propiedades
- Se creó la variante "Tipo" (De selección única/de selección múltiple) para empatarnos con desarrollo y seguir nuestra lógica constructiva. 
- Se ajustaron los anchos de las diferentes capas del botón de fixed a hug para que el contenedor abrace al texto llegando a un ancho máximo de 340px (4-col) en línea con la ficha y Storybook. 

## Evolutivos
Se debe revisar este componente a nivel ux y accesibilidad. 

- Analizar los tamaños, ¿hacen falta 3? ¿Cuáles son los casos de uso de cada uno? 
- ¿Es posible a nivel desarrollo y tecnologías que este botón use autocomplete? 
- ¿Qué buenas y malas prácticas tiene el componente? ¿Cuáles son los casos de máxima?
- ¿Cómo es su navegación por teclado? 
- Analizar los max-width por breakpoint con desarrollo



![Image](https://github.com/user-attachments/assets/e682169a-6cf5-4435-9c15-08049fa84681)

**Comment by marusaad** [comment]
Se realizó una corrección ágil en el padding-bottom y padding-top de las variantes de opción y botón de desplegable de tamaño chico, ya que al momento tenían 3px de padding (ahora tienen 4px) tanto arriba como abajo y no se ajustaban a las grillas 4x4 de Obelisco.  Esta corrección se realizó en la branch de tipografía.

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] El componente tiene una modulación definida para mobile, tablet y desktop.
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | v.0
-- | --
Agregado | Variantes por dispositivo desde el componente mayor de Desplegable de Selección. <br> Variante tablet. <br> Variante "Única" para los desplegables cerrados, ya que se comporta igual en todos los dispositivos.
Arreglado | 
Eliminado | Variantes por dispositivo del componente base .Opciones-Desplegable-Selección.
Obsoleto | 
Cambiado | Width de la variante desktop a 348px.

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Se agregó la variante “Presionado” al componente base (.Opciones-Desplegable-Selección).
Arreglado | Se ajustó a 8px (0.5rem) el espaciado entre opciones de selección.
Eliminado | 
Obsoleto | 
Cambiado |  

## ✏️ Notas
Actualizar los colores de la plantilla del componente con la nueva colección de variables
