### ISSUE TITLE
Switch on/off

### ISSUE THREAD

**Issue by NatiOertel** [gcba/estandares#262]
**Nombre en Obelisco:** No existe
**Descripción:**  Se utiliza para cambiar rápidamente entre dos estados posibles.
**Tipo de componente:** Molécula
**Ejemplo en boostrap:** https://getbootstrap.com/docs/5.3/forms/checks-radios/#switches
**Ejemplo de aplicación en BA:** No hay
**Necesidad solicitada por:** Subsidios

- [x] Construcción nuevo componente
- [ ] Actualización componente existente

**Comment by JuaneRambosio** [comment]
Prueba!

**Comment by NatiOertel** [comment]
Se comienza el análisis del componente teniendo en cuenta el requerimiento solicitado por Subsidios.

Observamos el contexto de uso que se le va a dar al componente en uno de los flujos de navegación de bloqueos / habilitación de tarjetas de SADE. El mismo está por fuera de una tabla con información y, además, dentro de cada fila de la misma. 

Por un lado, el que está por fuera de la tabla funciona como un switch "padre", ya que su objetivo es activar o desactivar los switchs de las filas **al mismo tiempo.** Y por el otro, los switchs que están dentro de la tabla permiten que se aplique una acción a una fila puntual de la misma.

Esta tabla posee una columna llamada "Estado tarjeta" que posee dos estados: Bloqueado y Pendiente de bloqueo / Pendiente de habilitación, según la acción que se haya seleccionado en el campo "Filtrar acción" del formulario que se encuentra arriba de la tabla. Dichos estados están representados con el componente Etiqueta de Obelisco (https://gcba.github.io/Obelisco/?path=/story/componentes-etiqueta--multiple).

Se dejan imágenes de referencia del flujo de navegación de Subsidios:

![Image](https://github.com/gcba/estandares/assets/106767361/109fc485-8a5e-4fef-b39e-2b2036c94082)![Image](https://github.com/gcba/estandares/assets/106767361/d3059a40-45e1-49e1-a728-d77877d9cfbb)

**Comment by NatiOertel** [comment]
Se analizaron ejemplos de switchsy el funcionamiento de los mismos en otros sistemas de diseño para contemplar las necesidades básicas del componente en relación a su contexto de uso y las necesidades que pueden surgir a futuro.

**Sistemas de diseño consultados:**
Carbon Design System: https://carbondesignsystem.com/
Spectrum: https://spectrum.adobe.com/

**Ejemplos:**

![Image](https://github.com/gcba/estandares/assets/106767361/d30cb262-f972-4e61-a559-f0431f4f52ca)

![Image](https://github.com/gcba/estandares/assets/106767361/8a5dc9e2-5746-4342-b483-2c288409f806)

![Image](https://github.com/gcba/estandares/assets/106767361/16f8a506-9930-4f41-b896-937e0e6dc6bc)


![Image](https://github.com/gcba/estandares/assets/106767361/185617a8-0026-482a-86b3-0596c3842dbf)


![Image](https://github.com/gcba/estandares/assets/106767361/e36909e9-4475-4a67-8452-935e89aee9d2)


![Image](https://github.com/gcba/estandares/assets/106767361/580de93b-85e7-4089-bf33-39119fe08aaf)


![Image](https://github.com/gcba/estandares/assets/106767361/91c845d7-3086-48f5-96d8-a151fe2a81b5)


En base a este análisis se determinó que:

- Se avanza con la creación del componente.
- El caso de Subsidios requiere un análisis UX más detallado para poder determinar si necesitan utilizar un switch u otro componente.
- Los switchs no necesariamente deben estar dentro de Formularios.

**Comment by NatiOertel** [comment]
Se creó un branch en el UI KIT para trabajar el componente:
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/FjL7pjix93AIzizJwoLIPa/UI-KIT---Obelisco?type=design&node-id=7928-12542&t=kLhhDoXnY7rElN4b-0

**Comment by JuaneRambosio** [comment]
La **Ficha de Switch** se estará trabajando en el siguiente Link: https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/Az3gH6dM7HtnAeLpQYCaaS/Fichas?type=design&t=Cf9o7y8dKTn2OeKv-0

**Comment by JuaneRambosio** [comment]
Se solicita revisión de @camilagaldo respecto al componente.

**Comment by camilagaldo** [comment]
Se modificó un detalle de la disposición de los switch en un apartado de la ficha, dejo la captura.
Sugiero que revisemos nuevamente el "Prendido" y "Apagado" como label del switch, ya que entiendo que puede ser redundante 


![Image](https://github.com/gcba/estandares/assets/122482595/a2079408-4b17-47e3-b7c7-1074931d6616)

**Comment by marusaad** [comment]
📝 En el día de hoy con @JuaneRambosio estuvimos trabajando en la ficha de Switch, y nos dimos cuenta de que faltaba una nueva variable y en función de eso la ficha tuvo que cambiar nuevamente.

**Componente V2. Switch**

- Añadimos una nueva versión “Sin label” y “Tamaños”. Ya que cuando poníamos la opción “Sin label” nos cambiaba a la versión “chica”.

- También renombramos los colores, ya que decía “Celeste” y “Gris” prestando a confusión. En este caso los cambiamos a la nomenclatura similar a botones “Primario” y “Secundario”, ya que el cambio cromático se relaciona con la jerarquía. 



![Image](https://github.com/gcba/estandares/assets/136834096/25cda7bd-38e5-48db-b559-153092eebf4c)



**Ficha V2. Switch**
Volvimos a renombrar y reestructurar toda la ficha en función de los cambios del componente Switch


![Image](https://github.com/gcba/estandares/assets/136834096/9b5f2f5f-41bd-4b04-ac69-a05901356ee0)

**Comment by marusaad** [comment]
¡Hola! 🔮

Dejamos un update sobre el componente a partir de la revisión de tipografía con la escala actualizada.

### ¿Qué hicimos?

- Actualizamos la plantilla del componente en la librería del UI kit.
- Actualizamos los estilos tipográficos del componente.
- Actualizamos la nomenclatura de las diferentes propiedades del componente.

### ¿Cómo se ve la página del componente en el UI kit?


![Image](https://github.com/user-attachments/assets/abb08d72-9870-4387-a7d9-521866db480a)

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] El componente tiene una modulación definida para mobile, tablet y desktop.
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | 

## ✏️ Notas

- Este componente no tuvo cambios durante la migración.

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado |
Obsoleto | 
Cambiado | 

## ✏️ Notas
Actualizamos los estilos de color con las nuevas variables.
