### ISSUE TITLE
Definir el uso de los espaciados

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#27]
Construir los estándares del uso de los espaciados teniendo en cuenta la usabilidad y accesibilidad del producto

**Comment by mathiassassone1** [comment]
Dejo la delimitación de espaciados. Falta revisión en detalle entre cada componente.

@Vpappacena @aloyber @Fcunsolo @techlowiec 
[Espaciado.pdf](https://github.com/gcba/estandares/files/4887142/Espaciado.pdf)

**Comment by Vpappacena** [comment]
@mathiassassone1 @aloyber @Fcunsolo @techlowiec , 
Tendríamos que probar el uso de  espaciado en contexto para validar tamaños.
