### ISSUE TITLE
Pie de página (footer)

### ISSUE THREAD

**Issue by camilembo** [gcba/estandares#270]
Nombre en Obelisco: Pie de pagina
Descripción:
Tipo de componente: Organismo
Ejemplo en boostrap:
Ejemplo de aplicación en BA:
Necesidad solicitada por: 

Creación de una sección previa al pie de página que funcione como un medio para que las personas usuarias dejen feedback respecto del activo digital visualizado

**Comment by camilembo** [comment]
Se construyó una sección, que acompañará al pie de página, compuesta de una pregunta y 2 acciones (principal y secundaria). Esta información variará según el contenido del activo digital al cual se está aplicando.

Se creó en Figma como una propiedad booleana la cual se podrá activar o desactivar según necesidad dentro del componente de Pie de página.


![Image](https://github.com/gcba/estandares/assets/137331016/ac5a8b60-746a-4051-87f5-c1beb605b49f)



![Image](https://github.com/gcba/estandares/assets/137331016/62233a80-ac3f-44e3-8556-b48ec9be52e5)

**Comment by camilembo** [comment]
Por otro lado se creó una brunch con la ficha de este componente (Pie de página) en donde se actualizó el contenido sumando al pie de página el "indicador de utilidad" 
Link a la ficha en Figma: https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/lNnOhq5myz4wKUn50uPRh1/Fichas?type=design&node-id=1589%3A813&mode=design&t=seJUSkuZjfgDkaHk-1



![Image](https://github.com/gcba/estandares/assets/137331016/55e6d910-27cb-4300-ace5-cfe4f48c7318)

**Comment by camilagaldo** [comment]
Se realizó el merge en Figma el día 26/07/2023

**Comment by marusaad** [comment]
Se reabre la tarjeta por nuevo requerimiento relacionado a generar una divisón entre el indicador y el fondo (porque los dos pueden ser de fondo secundario)

**Comment by marusaad** [comment]
✍️ Se actualizó el componente de Pie de página y su ficha. 

**Indicador**
Se creó el componente _Indicador_ que estará anidado dentro del footer. De esta forma será más fácil aplicar los cambios en futuras iteraciones. 

- Tiene una sola variante de dispositivo (Desktop/Mobile). 
- El componente se encuentra oculto en la librería, porque es de uso interno sólo para anidarlo al footer. 
- Se agregó un stroke superior para dividirlo de páginas con fondo secundario.

**Pie de página**
Se actualizó el componente eliminando variantes innecesarias y problemas de construcción.

- Se conservó la variante de dispositivo (Desktop/Mobile).
- Se eliminaron las demás variantes porque se aplicaron propiedades booleanas.



![Pie de página](https://github.com/gcba/estandares/assets/136834096/1df96ee1-df1e-4892-9de0-989064c44a52)
![Pie de página - Variantes](https://github.com/gcba/estandares/assets/136834096/53bea03c-6ffc-4600-85c0-7383e2b84dbe)

![image](https://github.com/gcba/estandares/assets/136834096/afd588d6-733b-4661-a1a5-c473b400563b)


**Ficha**
Se actualizó la información de la [ficha](https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/behv4qHguJ7Dy5p1qR7R7v/Fichas?type=design&node-id=1589%3A812&mode=design&t=FnI50PSISlZ0WsdQ-1) y se incorporaron nuevas imágenes a partir de los cambios realizados. 
Dejamos en rojo una parte de la ficha que sabemos si sería necesario que aparezca como clarificación @camilembo. Queda a la izquierda la ficha vieja para comparar.  

- Se cambió el nombre de la sección _Pie de página institucional_ a _Información gubernamental_, para no generar confusiones futuras con el _Bloque institucional_.

![Pie de página (Footer)](https://github.com/gcba/estandares/assets/136834096/7c68f35e-5851-4707-ab58-79bb65635e5e)

**Comment by camilembo** [comment]
Se modificó la info en la ficha

![Image](https://github.com/gcba/estandares/assets/137331016/d0b52af4-d82a-4f35-9da9-f4562eaa128f)

**Comment by camilembo** [comment]
MERGE HECHO EL 02/01/2024

**Comment by marusaad** [comment]
Actualizar los textos de la ficha de Pie de página para que se entienda mejor cuándo se usa cada variante.

**Comment by marusaad** [comment]
Se actualizó el texto de la ficha de Pie de página según el requerimiento. Se especificó el uso de cada variante y se aclararon algunos textos de Usabilidad. 

@camilembo queda para revisión

![Pie de página (Footer)](https://github.com/gcba/estandares/assets/136834096/53243b96-c049-479b-9bac-78589a7f0210)

**Comment by camilembo** [comment]
Yo lo veo bien chiques! mañana en el seguimiento que tenemos a la mañana lo pueden mostrar y ya le damos un cierre. Después de eso si todo está ok, lo comparten el canal de discord con desarrollo? :)

**Comment by Diehault** [comment]
¡Hola! 🦔

Actualizamos el componente aprovechando la actualización general de la guía tipográfica. Encontramos algunas cosas que consideramos como evolutivos a tener en cuenta.

### ¿Qué hicimos?
- Cambiamos los antiguos componentes "enlaces" dentro de las diferentes secciones del componente Pie de página (footer) por el nuevo componente Enlace.
- Actualizamos los estilos tipográficos del componente.
- Cambiamos las variantes en conflicto del viejo componente Botón por instancias del nuevo componente Botón.

### ¿Qué cosas encontramos y creemos que pueden ser evolutivos?
- Todos los productos digitales del GCBA incluyen el versionado del producto dentro del Pie de página (footer); esto también sucede en la página web de BA. Esto podría ser parte del componente, considerando que es una práctica común, y habría que evaluar la mejor manera de incluirlo.

### ¿Qué dejamos anotado en la página del componente en el UI kit?
![Image](https://github.com/user-attachments/assets/b407450e-fc5d-4613-820a-9c03787a66a3)

### ¿Cómo se ve la página del componente en la librería del UI kit?
![Image](https://github.com/user-attachments/assets/00bb33fd-55b0-482c-ad0e-de765c775b49)

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [ ] El componente se ajusta a la grilla 4px.
- [ ] El componente tiene una medida definida para mobile, tablet y desktop.
- [ ] El componente tiene una modulación definida para mobile, tablet y desktop.
- [ ] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [ ] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Se creó la variante tablet, con 36px de padding para los contenedores.
Arreglado | Los contenedores del footer ahora están en fill y los contenedores con enlaces en wrap para que pasen a la siguiente linea. 
Eliminado | -
Obsoleto | -
Cambiado | Se estableció el padding vertical entre las líneas de enlaces en 16px. <br> Se cambó el padding lateral de los contenedores de “Información útil” y legales de 141px a 129px para que se adapten al margen de la nueva grilla en Desktop. <br> Se cambó el padding lateral del Indicador para Desktop de 141px a 129px correspondiéndose con la nueva grilla. En mobile no se realizó ningún cambio porque la grilla continúa igual. 

## ✏️ Notas
Ninguna nota.

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Se creó una variable en la capa funcional específica para el divisor del footer.  
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | Se cambiaron las variantes de botón del indicador. Ahora se utilizan 2 botones iguales y de la misma jerarquía para evitar la creación de sesgos. Se eligió la variante secundario/outlined que tiene menos peso visual y es menos invasivo. 

## ✏️ Notas
Actualizamos los colores con las nuevas variables tanto en los componentes base como en el organismo en general.
