### ISSUE TITLE
Template - Trámites

### ISSUE THREAD

**Issue by camilembo** [gcba/estandares#272]
# Plantilla de trámites

**Nombre en Obelisco**
Plantilla de trámites (ex plantilla iniciar trámite / requisitos para iniciar un trámite)

**Tipo de componente**
Plantilla (_Template_)

**Ejemplo en Bootstrap**
No existe 

**Ejemplo de aplicación en BA**

**Detalle**
Esta plantilla se pensó para ser utilizada para mostra los requisitos de un trámite que se quiera realizar en WBA

**Comment by JuaneRambosio** [comment]
Se trabajó en el diseño de la Plantilla "Inicio del trámite" para versión Desktop y Mobile.

**Objetivo de la plantilla:** Ser la pantalla de inicio de cualquier trámite

**Qué debe contener la plantilla:**

- Descripción del trámite que sintetice para qué la persona deberá realizarlo
- Modalidad
- Requisitos para poder iniciarlo
- CTA para "Iniciar el trámite"
- Pasos que deberá realizar la persona posteriormente a "Iniciar trámite" desde el CTA
- Costos del trámite
- Una serie de colapsables en caso de necesitar añadir información extra y/o extensa
- Más información para tener de un vistazo respecto al trámite
- Lista de links de descargar de material pertinente
- Información complementaria (en caso de ser necesaria)
- Organismo responsable, dirección, días y horarios
- Pie de página

**↓ Ejemplo de pantalla ↓**

![Image](https://github.com/gcba/estandares/assets/134321929/d8215541-e1d0-4f1d-aa90-7e4ac0799aa5)

**A CONSIDERAR**

Mientras se trabajó la plantilla aparecieron **2 cuestiones** a considerar y ya cargadas en **"Backlog"**
- El componente con el CTA "Iniciar trámite" en versión desktop está correcta, pero en versión Mobile no existe

![Image](https://github.com/gcba/estandares/assets/134321929/54fecc4a-f22a-4afb-9c6b-47c227eb4440)

- El componente "Colapsables" en versión Mobile no se adapta al ancho máximo.

![Image](https://github.com/gcba/estandares/assets/134321929/f5266b6a-2ad2-4b81-a2b7-6464b0af768a)

**Comment by JuaneRambosio** [comment]
Esperando validación de los componentes:
- Lista de pasos
- Bloque iniciar trámite
- Desplegables
Para luego reemplazarlos en la plantilla.

**Comment by camilembo** [comment]
@Diehault tenemos que reemplazar en el template todas las listas que se crearon como componentes.
Link a la brunch con las listas: https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/C30D8HpS0MlPvLe5ZoBxCP/UI-KIT---Obelisco?type=design&node-id=10502%3A21630&mode=design&t=pRekgKUxNHVtFRzf-1

**Comment by Diehault** [comment]
¡Hola! Trabajé los templates únicos para trámites en una branch llamada [Template Trámites](https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/m6Kajp7wBwR10m73YUw3gc/UI-KIT---Obelisco?type=design&node-id=598%3A11418&mode=design&t=AbTdAyheppPAHBLy-1).

### ¿Qué se hizo?

- Actualicé las listas que había en el template para la versión **mobile** y la versión **desktop**
- Revisamos las listas y su funcionamiento específicamente para el template de trámites
- Incorporé el componente **Bloque de Inicio de trámite** con su versión con fondo en el template para la versión **mobile** y la versión **desktop**

### Muestra de los templates

![Template - Inicio de tráite (único) - Mobile](https://github.com/gcba/estandares/assets/144037453/caf75fd4-4f1b-4c7f-a6a6-27794c6a2712)
![Template - Inicio de tráite (único) - Desktop](https://github.com/gcba/estandares/assets/144037453/b1d8fe72-0d7a-4d69-bcec-301b1252330e)

**Comment by Diehault** [comment]
¡Hola! ¿Cómo estamos? Dejo una actualización de lo que estuvimos trabajando y subiendo de a poco. 🥸​

### ¿Qué se hizo?

- Empecé un documento de lineamientos para mejorar la usabilidad del template en cualquiera de sus contextos
- Actualicé el template de trámites según el documento de lineamientos que estamos generando. Cambiamos la máxima de algunas secciones y cómo se muestran

### Muestra de los templates

![Image](https://github.com/gcba/estandares/assets/144037453/02d6f48e-44d8-411b-98ac-e226319afdc1)
![Image](https://github.com/gcba/estandares/assets/144037453/fdb79705-9be4-44d2-99f3-d4ccd4ccd2a1)

Sumo además una imagen de lo que hasta ahora es el template de trámites para dejar registro del avance, pero se trata de un trabajo en progreso que seguimos revisando para dejar listo lo más pronto posible.

### Lineamientos del template de trámites

![Image](https://github.com/gcba/estandares/assets/144037453/7750868b-c84d-44e5-b5bd-227f03ca41f0)

**Comment by Diehault** [comment]
¡Hola! Actualizo nuevamente:

### ¿Qué se hizo?

- El template ya quedó y los lineamientos también
- Pasamos los lineamientos a un documento de Google Docs y está ahora en el Drive de Sistema y Estándares. Por acá les dejo el link: https://docs.google.com/document/d/1Y2z5ory91IsgtSvSn_B_ck9vXfwPM5y36ukKR7nA_LM/edit?usp=sharing

Cambio y fuera. 🕵🏼‍♂️​

**Comment by marusaad** [comment]
Actualizamos todos los estilos de texto de la plantilla de acuerdo a la nueva escala tipográfica.

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] El componente tiene una modulación definida para mobile, tablet y desktop.
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | Cambiamos el margen de 141px a 129px en desktop, coincidiendo con la grilla. <br> Cambiamos el width del contenedor del cuerpo de la página a 728px, coincidiendo con 8 columnas de la grilla. <br> Cambiamos el tamaño del aside a 348px width, para que coincidiera con 4 columnas de la grilla.

## ✏️ Notas

- **Versión tablet**: no hay una versión tablet definida para la plantilla, pero sí definimos que la plantilla tomaría el comportamiento de mobile, donde todo el contenido está armado en 1 sola columna.

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA).

## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Actualizamos la plantilla incluyendo la colección de variables con la nueva paleta de colores.
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | Cambiamos los componentes que estaban sobreescritos para que tomen cualquier actualización de ahora en adelante.

## ✏️ Notas
- N/A.
