### ISSUE TITLE
Bloque de trámite

### ISSUE THREAD

**Issue by camilembo** [gcba/estandares#274]
Nombre en Obelisco: bloque_iniciar_tramite 
Descripción:
Tipo de componente: Está dentro de Organismos - Trámites
Ejemplo en boostrap: 
Ejemplo de aplicación en BA: 
Necesidad solicitada por: diseño

Hay que evaluar si este componente amerita que tenga un tamaño fijo en desktop y otro en mobile o si puede ser un componente adaptable a distintas grillas y necesidades

**Comment by marusaad** [comment]
Con @JuaneRambosio creamos una nueva branch para trabajar sobre el componente llamada "Bloque iniciar trámite". 

- Ajustamos las variantes para que el componente tenga tamaño fijo para Desktop y para Mobile. En Mobile, el componente no existía así que lo creamos con sus variantes con un ancho de 328px. Para los títulos y subtítulos utilizamos los estilos de Mobile. 
- Encontramos que en la variante "Con barra de progreso" contenía dos barras, una de ellas oculta. Decidimos eliminarla ya que no cumple ninguna función. 
- Modificamos la nomenclatura de las propiedades para que se entiendan con más claridad. 

Queda pendiente analizar en qué ficha iría este componente, como así también si hay algún otro que podría pertenecer a la misma tipología. 

**Propiedades**

_Tipo_

- Por defecto (título + botón)
- Con descripción (título + descripción+ botón)
- Con barra de progreso (título + barra de progreso + botón) 

_Dispositivo_

- Desktop (340px de ancho, estilo de texto de Desktop, padding 24px)
- Mobile (328px de ancho, estilo de texto de Mobile, padding 16px)


![Image](https://github.com/gcba/estandares/assets/136834096/a76537b7-68a5-48ca-b1ee-e2180433c506)


![Image](https://github.com/gcba/estandares/assets/136834096/9fbd2731-8c8c-480d-99eb-e4730489be61)


Queda pendiente para revisión @camilembo

**Comment by camilembo** [comment]
Lo veo bárbaro!! 
2 cosillas nada más:
- Saquemos el "versión 2.0" del header que estamos usando para las mesas de trabajo de los componentes (para este y el resto de componentes que hagamos) 
- Y mañana hablamos con desarrollo a ver si ellos lo tienen así en estos tamaños, si ellos lo tienen ok en el storybook lo dejamos como listo porque solo era problema nuestro de diseño, sino lo pasamos a listo para maquetar.

**Comment by JuaneRambosio** [comment]
Listorti! @camilembo 

![Image](https://github.com/gcba/estandares/assets/134321929/6fe4d63b-857a-4280-82e7-7b0dec1ead2d)

**Comment by camilagaldo** [comment]
Realizado el 21/07/2023 el merge en Figma.

Sobre el tema de la ficha, entendemos que probablemente entre en lo que venimos analizando de panel/tarjetas

**Comment by camilembo** [comment]
Se reabre la tarjeta para trabajar una variable del bloque con background de color #f3f6f9

**Comment by Diehault** [comment]
¡Hola! Estuve trabajando en la actualización del componente "Bloque de Iniciar trámite" dentro de una nueva branch llamada [Bloque de Iniciar trámite](https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/gi1KTQLkHpyZSzOOeVJXJV/UI-KIT---Obelisco?type=design&node-id=11214%3A29443&mode=design&t=IWNsQmuuVqmBxVs9-1) en el UI Kit.

### ¿Qué se hizo?

- Agregué una nueva variante al componente para registrar la opción **solo con borde** y sumar la opción **con fondo**.

### Muestra del componente

![image](https://github.com/gcba/estandares/assets/144037453/132aa419-d2e7-40f5-9920-411367792710)

### Muestra de las propiedades

![image](https://github.com/gcba/estandares/assets/144037453/411fc041-0b04-4818-98e0-d3547062fb82)
![image](https://github.com/gcba/estandares/assets/144037453/704b0868-9d00-46bd-92a6-5538b5c7161a)

**Comment by camilembo** [comment]
Estamos ok con esto Die! 
Seguramente volveremos a abrir esta tarjeta cuando analicemos panel y veamos si es parte de eso como para hacer la ficha, queda en stand by eso pero estamos ok para usarlo en el template de trámites :D

**Comment by Diehault** [comment]
¡Hola! Sumo los colores de cómo quedaría entonces el componente:

- Con borde
Borde: #E6EBF0

- Relleno
Borde: #E6EBF0
Relleno: #F3F6F9

**Comment by marusaad** [comment]
A partir del relevamiento de panel, surgieron preguntas sobre funcionar el componente de bloque iniciar trámite con el destacado lateral. 

Desde desarrollo comentaron que la fusión sería complicada porque tienen distintas clases y eliminarlo al estar en uso puede traer problemas, por lo que se decidió conservar al bloque iniciar trámite como independiente del destacado. 

- Se cambió el nombre del componente de "Bloque iniciar trámite" a "Bloque de trámite" 
- Se pasó de la sección de organismos a la sección de componentes en Storybook (porque el componente es una molécula)
- Se armó una ficha para el componente en la cual se establecen las diferencias de uso con el destacado. En resumen, el bloque de trámite sólo se usaría en el template de trámites. 

Dejamos captura de la ficha que construimos con @Diehault en Análisis de componentes para luego incorporar en la branch que se cree de fichas de bloque de trámite. @camilembo 




![Image](https://github.com/gcba/estandares/assets/136834096/0100611b-9170-4cd0-94cc-cc8de91fc938)

**Comment by Diehault** [comment]
¡Hola! 🤠 Hacemos una actualización del componente en Figma porque había un problemilla con el componente "Botón", que no era el correcto y utilizábamos uno que ya no existe más.

### Requerimiento
- Cambiar el componente "botón_ancho" por el componente "Botón".
- Actualizar la ficha del componente en nuestro UI Kit.

### ¿Cómo se veía antes?
![Image](https://github.com/gcba/estandares/assets/144037453/d897f229-d475-47f7-9a9d-e573379a5c7b)

### ¿Cómo se ve ahora?
![Image](https://github.com/gcba/estandares/assets/144037453/8f3a170b-c248-4d76-b3c0-9e0dece810b3)

**Comment by marusaad** [comment]
Se actualizaron los estilos de texto del componente según la nueva escala tipográfica.

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [ ] El componente se ajusta a la grilla 4px.
- [ ] El componente tiene una medida definida para mobile, tablet y desktop.
- [ ] El componente tiene una modulación definida para mobile, tablet y desktop.
- [ ] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [ ] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | v.0
-- | --
Agregado | Comportamiento Tablet definido.
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | Width de la variante desktop a 348px.

## ✏️ Notas

- **[EV]**: sumar la modulación de Tablet en la ficha del componente.

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA).

## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Actualizamos el componente incluyendo la colección de variables con la nueva paleta de colores.
Arreglado | Incorporamos la barra de progreso como componente, que antes era algo customizado dentro del componente Bloque de trámite y no usábamos el átomo correcto.
Eliminado | 
Obsoleto | 
Cambiado | 

## ✏️ Notas
- N/A.
