### ISSUE TITLE
Encabezado (Header)

### ISSUE THREAD

**Issue by camilagaldo** [gcba/estandares#275]
**Nombre en Obelisco:** Encabezado de página
**Tipo de componente:** Organismo
**Ejemplo de aplicación en BA:** cualquier página de https://buenosaires.gob.ar/inicio/

**Requerimientos:**
- Compatibilizar componente en UI Kit, Storybook y Estándares teniendo en cuenta el funcionamiento para dispositivo mobile, especificamente el menú desplegable y el buscador.
-  Renombrar las secciones de la navegación horitonzal del encabezado de forma genérica

**Especificaciones**
Al momento de solicitar este requerimiento, ya se estaba analizando el componente Encabezado de página. De este requerimiento se desprenden los siguientes:
- Se debe crear un requerimiento o incluir en desplegables para revisar el menú desplegable
- Se suma al requerimiento vigente de encabezados el análisis de la nomenclatura del componente Encabezado de página.
- Se debe sumar al requerimiento vigente de enzabezados la mejora de la ficha para estándares, ya que en esta instancia no se revisó en profundidad.

**Comment by camilagaldo** [comment]
Se creó la brunch del ui kit para trabajar sobre el componente:
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/2HkeQSSIeiNL7G1po6I2B1/UI-KIT---Obelisco?type=design&node-id=1022-9648&mode=design&t=zBrXg9dJvFPWBisM-0

**Comment by camilagaldo** [comment]
Se modificó el nombre de las secciones para que sean genéricas

Antes:

![Image](https://github.com/gcba/estandares/assets/122482595/524b6f5f-889b-4e8d-8353-21d48e530138)


Después:

![Image](https://github.com/gcba/estandares/assets/122482595/8d1858d9-2a7c-4623-a0f0-49a5714a624d)

**Comment by camilagaldo** [comment]
Versión Mobile:

(1) Se unificó la versión mobile para cuando el usuario está o no logueado y queda una predeterminada que es de la siguiente forma:

![Image](https://github.com/gcba/estandares/assets/122482595/63c5f1ce-70fe-49e9-8152-6c64650207b0)


(2) Se incluyó el desplegable con las secciones para cuando esté en estado desplegado y se definió que el cerrar sesión sea una sección dentro del mismo.

- Antes:

![Image](https://github.com/gcba/estandares/assets/122482595/2a96498a-2ad2-4262-8949-c110d3df36e2)

- Despues:

![Image](https://github.com/gcba/estandares/assets/122482595/33e89e0a-0ad3-4d2d-ac23-ae7cff01618e)

(3) Se modificó el comportamiento para cuando se selecciona el buscador

- Antes:

![Image](https://github.com/gcba/estandares/assets/122482595/3d9faed7-6cf3-43a0-ae14-4ac242dfe3ec)

- Después

![Image](https://github.com/gcba/estandares/assets/122482595/d2e229ca-7c27-442f-9706-c1413967ba6e)

**Comment by camilagaldo** [comment]
Se creo la brunch para la ficha: https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/HGMZAZeDgm6uokWfjeuHWe/Fichas?type=design&node-id=4310-20961&mode=design&t=YsTf3za6EUBw7duM-0

**Comment by camilagaldo** [comment]
@camilembo a Diseño le queda pendiente lo siguiente
(1) revisar si está creado el requerimiento para menú desplegable.
(2) incluir mejoras en el encabezado de página para el requerimiento que esta vigente.

@lautarorodriguez96 una vez que esté ok esto, hacemos el merge y actualizamos los encabezados de página de las entregas al proveedor de perfil ciudadano.

**Comment by camilagaldo** [comment]
Se realizó el merge el 26/07/2023

**Comment by camilagaldo** [comment]
En función de lo que vimos con el equipo de Desarrollo, se realizaron las siguientes modificaciones:

(1) Se incluyó la opción para notificaciones activas tanto desktop como mobile

- Antes
![Image](https://github.com/gcba/estandares/assets/122482595/3f195298-294c-44db-92fd-d71f5f03fe0f)
![Image](https://github.com/gcba/estandares/assets/122482595/a9ea5a57-66a1-486b-9672-02abc91cb27d)


- Después
![Image](https://github.com/gcba/estandares/assets/122482595/8499ed02-5f6c-47e4-acf0-dd9c094ab5c0)
![Image](https://github.com/gcba/estandares/assets/122482595/0c7f1556-7a2d-437b-8858-f60214c215eb)


(2) Para mobile, se diferenció la sección de cerrar sesión

- Antes
![Image](https://github.com/gcba/estandares/assets/122482595/db7a2533-6772-4b00-99b9-423a1e786963)

- Después
![Image](https://github.com/gcba/estandares/assets/122482595/7d128f02-7bd4-4863-bf86-539d01332dad)


(2) Para mobile, se reemplazo el exit por un back.

- Antes
![Image](https://github.com/gcba/estandares/assets/122482595/e03a044f-2b82-4899-9cd8-b222534f7e20


- Después
![Image](https://github.com/gcba/estandares/assets/122482595/a85f3f5c-ec40-41df-8590-0b67a9f5995c)

**Comment by camilagaldo** [comment]
Se realizó el merge de UI Kit en Julio 2023

**Comment by camilembo** [comment]
Se reabre esta tarjeta el 04/09/2023 para trabajar el organismo de Encabezado de pagina con sus variantes "secciones visibles" y "desplegable de navegación"

**Comment by marusaad** [comment]
Se cambió la nomenclatura del organismo (de Encabezado de página a Header). Se creó una branch exclusiva para el componente. Los otros encabezados quedaron como "encabezados".

**Comment by marusaad** [comment]
👩‍🔧 **Se comenzó el análisis UX del componente**

- Se relevó el componente header de otros design systems, como también el comportamiento de los buscadores dentro del header. 
- Se mapearon usos dentro de la web de Buenos Aires. Se conversó con desarrollo sobre las diferencias que existen hoy en el header en las páginas de Angular y de Drupal. Se decidió diseñar con vista a Angular con el máximo de posibilidades y se adaptará a las posibilidades de Drupal. 
- Se comenzaron algunas exploraciones de la construcción del componente, especialmente del comportamiento posible del buscador como un botón expandible. 

![image](https://github.com/gcba/estandares/assets/136834096/7f749080-0363-4975-a58d-468c09b6c7e0)
![image](https://github.com/gcba/estandares/assets/136834096/af5adb4d-4bc5-4c5e-836c-62e3f57fd842)
[Link al prototipo de cómo funcionaría](https://www.figma.com/proto/mqy6dUBWeK47l1CMIYCdkX/An%C3%A1lisis-de-componentes?type=design&node-id=743-2555&t=GQKjKmZbrZnpRAZe-1&scaling=min-zoom&page-id=668%3A75&mode=design)

📢 Algunos temas para ver en la daily del lunes
- Vicky se llevó ver si es posible el comportamiento "colapsable hacia el costado" del buscador
- Tema "cruz de cerrar": si el buscador va a estar abierto siempre, entonces se puede pensar que la cruz se coloque dentro del buscador y borre el texto ingresado. Si el buscador va a estar oculto y se va a desplegar, la cruz va a servir para cerrar el buscador completo. Estas son dos prácticas que se repiten a través de design systems diferentes, y también se diferencian entre mobile y desktop. 
- ¿Por qué el botón de accedé a tu cuenta es fantasma? 
- Desplegable de navegación abierto en convivencia con el header
- ¿Es necesario que tenga el margen de la grilla desktop?

![Análisis UX](https://github.com/gcba/estandares/assets/136834096/97b98209-295d-42a3-9896-bf44a5703b1c)
![Mapeo de casos en BA](https://github.com/gcba/estandares/assets/136834096/ee855bf8-dd15-42c9-8ea9-056bbdee4f02)

**Comment by marusaad** [comment]
👷‍♀️ **Se comenzó la construcción del componente** 

🖥 DESKTOP
**Sin logueo**
Es el Header que aparece siempre que no se inicie sesión. Las secciones se pueden ocultar y quedan como opcionales, aunque hoy en día no son necesarias. Esto sucede porque las secciones se relacionan con el perfil del usuario logueado (notificaciones, mis turnos, cerrar sesión) y no con secciones de, por ejemplo, la home (Ej. "trámites", "áreas de gobierno"). En ese caso se deberá evaluar nuevamente la arquitectura y construir el Header acorde a la misma. 

 **Con logueo**
Al acceder a la cuenta aparece en el Header un menú desplegable. El botón incluye un ícono y el nombre del usuario. El desplegable se activa y muestra diferentes secciones con opción o no de que sean en cascada. Esta situación se dividió en 2 (_menú activo/menú inactivo_) solamente por cuestiones de construcción en Figma. 

📱 MOBILE
**Sin logueo**
El Header cuenta con un botón para acceder a la cuenta y un botón que al hacer click despliega como drawer la barra de búsqueda, que consiste en un input de búsqueda y un botón secundario mediano con ícono que dispara la búsqueda. 

**Con logueo**
Al acceder a la cuenta aparece en el Header un menú desplegable con el ícono de perfil. El desplegable se activa y muestra diferentes secciones con opción o no de que sean en cascada. 

También se comenzó a trabajar el handoff que incluye los componentes base, las variantes y una demo para ver los prototipos 

![Variantes](https://github.com/gcba/estandares/assets/136834096/da5d7f6f-9507-4830-a618-6743fa451402)
![Componentes base](https://github.com/gcba/estandares/assets/136834096/5409bff6-e8d3-4f14-9561-bc685f44e2a6)
![Header](https://github.com/gcba/estandares/assets/136834096/c754b390-fb36-4f43-ba06-db47d4797e1c)
![Demo](https://github.com/gcba/estandares/assets/136834096/426ed2b9-2a70-4bac-b476-51f8a6eb3ddd)

**Comment by marusaad** [comment]
Se terminó la construcción del componente. 
@camilembo queda para revisión
Se recomienda ver el component set en Dev Mode abriendo el Playground



![Header (4)](https://github.com/gcba/estandares/assets/136834096/41ff130a-cbb4-4879-bb40-039acf38404f)

**Comment by marusaad** [comment]
Se sube la ficha para revisión @camilembo 
También se pueden dejar comentarios en Figma! 

![Header (6)](https://github.com/gcba/estandares/assets/136834096/f613a166-925e-4b04-8c39-9c73980b434c)

**Comment by marusaad** [comment]
Para este componente se diseñaron alrededor de 5 variantes luego de conversar con desarrollo. Las mismas tuvieron que ver con las posibilidades técnicas que tenemos hoy en día con nuestra versión de Bootstrap que posee funcionalidades limitadas, y con el requerimiento de incorporar más enlaces de navegación con subsecciones para que sea un componente escalable. 

Para ver todas las versiones y comentarios sobre por qué se descartaron, ver el archivo de [Análisis de componentes](https://www.figma.com/file/mqy6dUBWeK47l1CMIYCdkX/An%C3%A1lisis-de-componentes?type=design&node-id=668-75&mode=design&t=xZdYWQ1rU3o1orVO-0) en Figma. 


La última versión implica un header que tendrá 1 o 2 líneas según la cantidad de enlaces a secciones de la web. 


![Image](https://github.com/gcba/estandares/assets/136834096/d7e51f4b-e67d-4bc3-8256-fc7bb194bc08)



![Image](https://github.com/gcba/estandares/assets/136834096/218363d1-1a32-4e8b-ace3-d6e1b1b1c891)



@camilembo acá está la ficha actualizada para su revisión


![Image](https://github.com/gcba/estandares/assets/136834096/c8feef80-7062-4500-b84f-9fb49eedc3cb)

**Comment by Diehault** [comment]
¡Hola! 🤠

Con el nuevo **requerimiento** de generar 2 variantes para el Header desktop según las versiones de 1 línea y 2 líneas, simplificamos el componente y construimos las 2 variantes.

### Nuevo Header (desktop)
![Image](https://github.com/gcba/estandares/assets/144037453/ace6329b-9af1-43cc-9309-f44e2d17ce38)

Con esto, el componente que antes era un "master component" con todas las propiedades editables, ahora es un componente con 2 variantes que comparte propiedades para ambas variantes.

### Nueva composición del Header desktop
![Image](https://github.com/gcba/estandares/assets/144037453/cdcf94cb-c73f-425b-af3f-de866669079b)

El Header en mobile quedaría compuesto de la misma forma.

### Header mobile
![Image](https://github.com/gcba/estandares/assets/144037453/56a2e6c9-1902-4743-b760-cdb4d64b8f10)
![Image](https://github.com/gcba/estandares/assets/144037453/9c99d381-a7da-4d92-a771-ed4d3bf8d3d8)

**Comment by marusaad** [comment]
Se incorporó a la ficha un **apartado de accesibilidad** para el enlace oculto de "Saltar al contenido de la página". 

Hoy en día el enlace en Storybook dice "Ir al contenido principal". Se convino con desarrollo que se cambiará el texto más adelante cuando vean el fix. 


![Image](https://github.com/gcba/estandares/assets/136834096/4ebd1b0c-57ee-4598-9e40-b6b7d3091e73)



![Image](https://github.com/gcba/estandares/assets/136834096/0b7ae7c3-828b-46d4-a20c-29ceea8bb155)


@camilembo queda para revisión

**Comment by Diehault** [comment]
Para completar el hand-off, puntualmente en referencia al desplegable de perfil, dejamos este resumen de especificaciones para cada uno de los estados del componente.

![Image](https://github.com/gcba/estandares/assets/144037453/74687248-0751-46fc-a030-c6a97f07e7b1)

**Comment by Diehault** [comment]
¡Hola! 😎​ Dejo la actualización del Encabezado teniendo en cuenta los requerimientos de diciembre.

### Requerimientos

- Actualización del template del componente.
- Sumar un identificador de aviso para las notificaciones de la persona usuaria.

### ¿Cómo quedó el componente en el UI Kit?

![Image](https://github.com/gcba/estandares/assets/144037453/87fd2ad8-9f04-4e78-a0a2-367dfd97f50c)

### Propiedades del componente

![Image](https://github.com/gcba/estandares/assets/144037453/f427eb98-69d8-4cab-a2de-bb3fe5f69012)
![Image](https://github.com/gcba/estandares/assets/144037453/dbe4262a-8e70-41f2-b976-21900d335e06)

Al ajustar el template del componente en el UI Kit también sumamos lo que faltaba del desplegable de perfil, sobre sus estados.

**Comment by Diehault** [comment]
¡Holas! 🦭​ Según lo que charlamos en la última weekly de Obelisco el día de ayer, actualizamos la ficha del componente para sumar entre el menú interno de navegación el apartado de "Accesibilidad".

En la [branch de Encabezado (header)](https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/2ELs5wAWhbMJUqoijXpw58/Fichas?type=design&node-id=5272%3A177&mode=design&t=hzr94rOovgeRWjXD-1) dentro de las fichas encontrarán este cambio.

### Imagen de la ficha con el cambio
![Image](https://github.com/gcba/estandares/assets/144037453/a39d94f6-2149-4478-b091-3e360789ea30)

**Comment by Diehault** [comment]
¡Hola! 🐔

Actualizamos el componente aprovechando la actualización general de la guía tipográfica.

### ¿Qué hicimos?
- Actualizamos los estilos tipográficos del componente.
- Cambiamos la iconografía que quedó fuera de versión por íconos de la librería de Material Design Icons.
- Actualizamos los componentes base del componente final. Antes utilizábamos componentes traídos de la página de Análisis y convivían con las moléculas armadas dentro del UI kit.
- Reorganizamos y actualizamos la nomenclatura de las propiedades del componente.

### ¿Qué dejamos anotado en la página del componente?
![Image](https://github.com/user-attachments/assets/cabfecac-f68f-42f7-8918-46e4560dcbab)

### ¿Cómo se ve la página del componente en la librería del UI kit?
![Image](https://github.com/user-attachments/assets/5628145c-c189-41d0-b484-72c6631262a6)

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [ ] El componente se ajusta a la grilla 4px.
- [ ] El componente tiene una medida definida para mobile, tablet y desktop.
- [ ] El componente tiene una modulación definida para mobile, tablet y desktop.
- [ ] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [ ] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Sumamos una variante tablet entre los siguientes componentes base: .Navegación-Header, .Subsección-Header; Variante Tablet del Encabezado (header)
Arreglado | -
Eliminado | -
Obsoleto | -
Cambiado | -

## ✏️ Notas

- **[EV]**: -

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | 

## ✏️ Notas

Actualizamos los estilos de color en los componentes base y en el organismo en general.

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Qué
Actualizar y generar la nueva ficha del organismo para la web de Obelisco v.2.

### Por qué
Por el proceso de migración de fichas de Obelisco v.1 a Obelisco v.2, que involucra la actualización de fichas y la actualización de la plantilla de presentación.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación
- [ ] El componente está adaptado a la nueva plantilla de presentación de Obelisco v.2.
- [ ] El componente pasó por un proceso de actualización a nivel de contenidos (descripciones, usos, especificaciones, etc.).


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Incluimos pestañas de "Guía de uso", "Especificaciones" y "Accesibilidad".
Arreglado | Actualizamos el contenido de la ficha según las nuevas secciones de la plantilla de presentación.
Eliminado | 
Obsoleto | 
Cambiado | 

## ✏️ Notas
- **Archivo de fichas v.2:** creamos un archivo para la fichas de Obelisco v.2, conservando el antiguo archivo de fichas v.1. Esto es para registrar el progreso y evidenciar los cambios de una versión a otra. [Acá está el link](https://www.figma.com/design/ysBh7PNXf9HYfrrlMsvMmn/Fichas---Obelisco-V2?node-id=154-10784) para el encabezado (_header_).
