### ISSUE TITLE
Enlace roto para descarga de Figma UI Kit

### ISSUE THREAD

**Issue by damvaz** [gcba/estandares#281]
Página: https://gcba.github.io/estandares/herramientas_y_recursos/ui_kit/

Cuando se intenta descargar el recurso de Figma, **ocurre un error de descarga**, ya que el archivo no se encuentra.

Por favor, **corregir el enlace** para que apunte a la ubicación correcta del archivo.

Muchas gracias.

**Comment by camilagaldo** [comment]
Solucionado
