### ISSUE TITLE
Lista de enlaces

### ISSUE THREAD

**Issue by camilembo** [gcba/estandares#285]
Nombre en Obelisco: Lista de enlaces
Tipo de componente: Molécula
Ejemplo en bootstrap: //
Ejemplo de aplicación en BA (template trámites) : https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/m6Kajp7wBwR10m73YUw3gc/UI-KIT---Obelisco?type=design&node-id=792%3A14241&mode=design&t=rjwhjPi3XqwGskrF-1

Dispositivos: desktop y mobile
Variantes: con título y sin título para la lista como organismo.

**Comment by marusaad** [comment]
Se construyó el componente Lista de enlaces. El organismo se construyó con 7 ítems de enlace. Se muestran por default 4, y 3 quedan ocultos. 

Dispositivos 

- Desktop: el espaciado entre ítems es de 16px
- Mobile: el espaciado entre ítems es de 20px para separar correctamente los objetivos táctiles

Título (propiedad booleana) 
- Mostrar título
- Ocultar título



![Image](https://github.com/gcba/estandares/assets/136834096/c09c8f79-99f9-430a-964b-4e09755fea3c)

**Comment by marusaad** [comment]
Ficha lista para revisión @camilembo 



![Image](https://github.com/gcba/estandares/assets/136834096/ffb655d7-ec93-48dc-91cf-ad9548b574a9)

**Comment by camilembo** [comment]
Se hizo **merge** el día 21/09/2023

**Comment by camilembo** [comment]
Tenemos que ajustar y agregar instancia de texto en el componente :)

**Comment by marusaad** [comment]
¡Hola! 🦀

Se actualizaron los estilos de texto del componente con la nueva escala tipográfica y incorporó la nueva plantilla para el UI Kit separando los componentes base.

![Image](https://github.com/user-attachments/assets/fa21e76a-3cc7-40d9-8050-00b1e7cced54)

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [ ] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] <s>El componente tiene una modulación definida para mobile, tablet y desktop</s>. **No aplica para este componente**
- [x] <s>El componente tiene su handoff para desarrollo y está marcado como ready for dev</s>. **No aplica para este componente**
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | Width de la variante desktop a 728px.

## ✏️ Notas

- **[EV]**: se puede sumar una variante tablet, como para tener un tamaño predeterminado por dispositivo. Sin embargo, no es algo que consideremos necesario/obligatorio, porque se compra como texto en dispositivos móviles, al 100 %.

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado |
Obsoleto | 
Cambiado | 

## ✏️ Notas

Se actualizaron los estilos del color del componente y se resetearon los enlaces para que se vean con los nuevos estilos.
