### ISSUE TITLE
Definir el componente Botón

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#29]
Trabajar ne la construcción de la familia de botones que cumpla con los estándares de usabilidad y accesibilidad

- [x] Relevar
- [x] definir casos y usos para el ecosistema de productos de gcba
- [x] armar los botones con los usos y funciones definidas para la primera versión

**Comment by aloyber** [comment]
Adjunto la primer versión del componente botón. Se dispone lo siguiente:
- Tipos de botón
- Estados de botón
- Tamaños de botón

[BOTONES.pdf](https://github.com/gcba/estandares/files/4833637/BOTONES.pdf)
@Fcunsolo @Vpappacena
