### ISSUE TITLE
Mapa

### ISSUE THREAD

**Issue by marusaad** [gcba/estandares#292]
Nombre en Obelisco: Mapa
Descripción: Componente de mapa que se encontraba anteriormente en Panel
Tipo de componente: Molécula/Organismo
Ejemplo en boostrap: 
Ejemplo de aplicación en BA: [Información instituciona](https://buenosaires.gob.ar/jefedegobierno)l | [Lateral (Noticias)](https://buenosaires.gob.ar/reservasecologicas/reservaecologicacostanerasur/fauna) | [Interactivo](https://buenosaires.gob.ar/educacion/escuelas/mapa-de-establecimientos-educativos)
Necesidad solicitada por: Diseño

Revisar el componente de mapa, que anteriormente era parte de Panel

**Comment by marusaad** [comment]
Se inició el relevamiento de los mapas que aparecen en la página de Buenos Aires. 
Detectamos 2 tipos de mapa, que clasificamos de la siguiente manera:

_MAPA "CÓMO LLEGO"_
Era el mapa incorporado al componente de panel. Indica una dirección puntual en el mapa, dando contexto sobre la ubicación. Presenta un botón primario que llega al Mapa Interactivo de Buenos Aires en una nueva pestaña para indicar cómo llegar. 
Se encuentra en: 

- Páginas de área N1 en bloque institucional al final de la página
- Páginas de noticias al lateral del cuerpo
- Página de "Mis turnos" en perfil ciudadano con el turno agendado

_MAPA INTERACTIVO_
Es un mapa embebido de USIG en el cual se pueden navegar diferentes ubicaciones sobre un mismo tema (por ejemplo, ver todos los centros de atención para X situación). Puede contener marcadores con diferente iconografía y color, y los resultados se pueden mostrar con tarjetas flotantes (con o sin botón), o como cajón. También pueden o no contener filtros y su disposición varía en el mapa. 
Se encuentra en:
- En Página Simple a 12-col
- En Página Simple a 8-col
- En Nivel 2 a 4-col (institucional)
- En Nivel 3 a 6-col (dentro de panel)
- En Página libro a 8-col

En la siguiente etapa del relevamiento queremos entender cómo es el vínculo entre las áreas y USIG para solicitar la construcción de mapas interactivos temáticos, y ver si podríamos llegar a trabajar en conjunto para aplicar estilos de obelisco y buenas prácticas/lineamientos.

**Comment by Diehault** [comment]
¡Hola! 🥸​

Avanzamos sobre el componente y trabajamos ya en la [branch de mapa](https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/34eashNuzYAwpdJ6KBc9Vg/UI-KIT---Obelisco?type=design&node-id=659%3A7701&mode=design&t=dqK9aJIXY4h7adu6-1) del UI Kit lo que sería el nuevo mapa.

Por ahora, y según lo que fuimos relevando durante la etapa de análisis, solo tenemos el mapa de "¿Cómo llego?" en cuenta, ya que los demás mapas, como el que tiene un buscador, realmente no funcionan como deberían. Aún se está trabajando el componente, pero dejamos un registro del avance hasta ahora.

### ¿Cómo se ve el mapa ahora?
![Image](https://github.com/gcba/estandares/assets/144037453/fe88c431-e6e4-477b-9749-d938ced252a0)

**Comment by marusaad** [comment]
**Conversamos con desarrollo sobre algunas cuestiones:** 

Si se incorpora el mapa de buenos aires como iframe, se incluye toda la ui con una barra de búsqueda (que no anda) y los resultados como tarjetas/tooltips. 

Si no queremos que se vea esto, tendríamos que usar google maps porque el mapa interactivo no permite sacarle la UI. Sería polémico que el iframe sea de google maps, y que el botón de "cómo llego" lleve al mapa interactivo porque son dos url distintas. Por ahora quedó así. 

Sobre por qué en drupal se ve el mapa de bs as de otra manera, es porque tienen configurado el servicio para que se le haga un "print" al iframe que corresponde a la dirección, pero no saben cómo ni de dónde viene ese servicio.



![Image](https://github.com/gcba/estandares/assets/136834096/90b4891d-01c1-4552-833e-b01e13a3f046)


Por otro lado, completamos la **sección de accesibilidad de la ficha del componente**


![Image](https://github.com/gcba/estandares/assets/136834096/c5fb9138-8fa0-4662-844b-5673b9db017e)

**Comment by Diehault** [comment]
¡Hola! 🦫

Actualizamos el componente aprovechando la actualización general de la guía tipográfica.

### ¿Qué hicimos?
- Actualizamos los estilos tipográficos del componente.
- Actualizamos la plantilla del componente en el UI kit.

### ¿Cómo se ve ahora la página del componente en la librería del UI kit?
![Image](https://github.com/user-attachments/assets/ec950a55-4b79-4e8a-a3c8-93eb5c686ac3)

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] El componente tiene una modulación definida para mobile, tablet y desktop.
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Variante tablet, que ocupa el 100 % del width de la pantalla del dispositivo.
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | Width de la variante desktop a 348px. <br> Width de la variante dentro del "bloque institucional" pasó a 538px.

## ✏️ Notas

- **Variante tablet**: el alto de la imagen del mapa cambia en la variante tablet para mantener la proporción y el ratio de las otras variantes. El height de la imagen del mapa en tablet es de 240px.

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | Se asignaron las nuevas variables de color al componente.
