### ISSUE TITLE
Tablas

### ISSUE THREAD

**Issue by camilembo** [gcba/estandares#298]
Nombre en Obelisco: Tablas
Tipo de componente: Organismo
[Ejemplo en Bootstrap](https://getbootstrap.com/docs/4.6/content/tables/)
Necesidad solicitada por: Contenido/Desarrollo/Diseño

**Comment by marusaad** [comment]
Comenzamos el análisis UX del componente de tablas.

**Mapeamos los usos dentro de NBA y encontramos varios usos:** 

- Tabla estándar (cada columna tiene un encabezado)
- Tabla cuadro de doble entrada (cada columna y cada fila tiene un encabezado) 
- Directorio (tabla estándar con información a modo de directorio, por ejemplo, direcciones, teléfonos, horarios)

También listamos elementos/componentes que hay dentro de las tablas en NBA:

- Enlaces
- Botones/enlaces sin estilos de obelisco (por ejemplo en Nunito Bold color negro) 
- Imágenes

**Relevamos otros sistemas de diseño**

_Elementos/componentes dentro de tablas que nos parecieron interesantes_

- Filas expandibles
- Etiquetas
- Barras de herramientas con buscador, CTA, desplegables
- Ordenamiento de columnas
- Paginado

_Tipos de comportamientos responsivos_
- Scroll horizontal con posibilidad de fijar columnas
- Stacked o apilamiento, en la cual 

**Conversamos con desarrollo sobre los principales desafíos de tablas hoy**

- Las tablas en mobile no son responsivas. En storybook aparece la posibilidad de scroll horizontal pero no en Drupal
- A nivel diseño, no hay lineamientos específicos para el uso de otros componentes y encabezados en las tablas
- Según desarrollo, no hay muchas posibilidades técnicas de incorporar funcionalidades a las tablas


![Image](https://github.com/gcba/estandares/assets/136834096/9e4aac38-ce78-4422-99d5-c74e0748e424)



![Image](https://github.com/gcba/estandares/assets/136834096/78bbd8e5-b8b8-48a8-876a-1296ce5ffd0f)

**Comment by marusaad** [comment]
Luego del análisis del componente, comenzamos su construcción. 

### Pruebas y versiones del componente 
#### Versión 1 (tabla responsiva) 
Probamos construir una tabla que tuviese celdas que se adaptaran a un ancho máximo y un ancho mínimo según el tamaño de la tabla, y según el tamaño del dispositivo (desktop o mobile). En esta versión, intentamos con un ancho mínimo específico para cada una de las celdas, que hacía mucho más fácil el responsive de la tabla, pero tuvimos problemas con la alineación.

Como las celdas de encabezado debían tener un ancho mínimo predeterminado para que el texto no se rompiera y cupiese suficiente información, no coincidían con las celdas de contenido que tenían elementos mucho más pequeños, como etiquetas o números. Por esto, descartamos la opción de tener un componente donde se ajustara el contenido según el tamaño de la tabla, donde no se visualizaba correctamente el contenido y no se alineaba la información entre celdas y columnas.

#### Versión 2 (tabla construida por columnas) 
Para solucionar el problema de la alineación, probamos construir una tabla por columnas, entendiendo que facilitaría la organización de las celdas de contenido con respecto a las celdas de encabezado. Sin embargo, esta versión complicaba el consumo del componente y hacía mucho más difícil la personalización, como el poder contar con un modelo de tabla con un patrón de cebra, por lo que no seguimos con esta idea.

Si bien solucionábamos el problema de la alineación y respondía el componente correctamente al tamaño del dispositivo (desktop o mobile), era un componente mucho más complejo de manejar y con propiedades de muchísimas capas. 

#### Versión final (tabla construida con filas de tamaño fijo) 
Volviendo a la versión de una tabla con filas, pensamos en adaptar el comportamiento que vimos en nuestro benchmark de otros sistemas de diseño, donde las tablas tenían filas de tamaño fijo y cuidaban que el contenido se visualizara correctamente. Para esto, a cada una de las celdas le colocamos un ancho mínimo, dándole espacios con mayor o menor importancia a las celdas de contenido según su tipo, y fijando el tamaño de la fila al tamaño más grande de la tabla (una tabla a 12 columnas según la grilla de Obelisco).

Cuando la tabla tiene un tamaño menor a 12 columnas, las filas mantienen su tamaño fijo y lo que sucede es que aparece una barra de desplazamiento (scrollbar) para poder ver el contenido que queda oculto. Este comportamiento se da en desktop en cualquier momento donde el contenido de la tabla empieza a "desaparecer", y funciona de la misma manera para mobile/tablet, donde siempre hay contenido oculto y una barra de desplazamiento (scrollbar). Con esto, una tabla podría tener scroll horizontal. 

### Tamaños
Construimos tres variantes de tamaño para el componente. Al 100%, que ocupa 12 columnas de la grilla de Obelisco en desktop; al 75%, que ocupa 8 columnas de la grilla de Obelisco en desktop; y un tamaño único para dispositivos móviles que ocupa todas las columnas disponibles de la grilla mobile de Obelisco. 

### Evolutivos

- Tanto la variante _indeterminate_ del checkbox como la posibilidad de tener uno en las celdas de encabezado para seleccionar todas las filas al mismo tiempo, son propiedades que se pueden incorporar con JavaScript. 
- Tabla responsive con comportamiento _stacked_ (apilado) para dispositivos móviles o con tamaños específicos de celdas para mobile. 
- Posibilidad de filas expandibles cuando se incluyan más funcionalidades
- Posibilidad de ordenar el contenido en las celdas de encabezado
- Construir un organismo que incluya la tabla con un buscador, filtros, paginado, CTAs y desplegables para mostrar x cantidad de resultados por página. 

Todo el registro visual y las notas están en [Análisis de componentes 2024](https://www.figma.com/file/PTv4gTxQhnSgBjnda5lBsD/An%C3%A1lisis-de-componentes-%7C-2024?type=design&node-id=2-535&mode=design&t=oMVaj9czBZypvtXE-0)



![Image](https://github.com/gcba/estandares/assets/136834096/7dec7da9-90e0-4fdf-ac2a-7af96d199b1c)





![Image](https://github.com/gcba/estandares/assets/136834096/db99056d-a413-4140-93eb-b89c98449280)






![Image](https://github.com/gcba/estandares/assets/136834096/6920d4b4-e11d-4142-b83c-d41e21dc1eb4)

**Comment by Diehault** [comment]
¡Hola! 🐧

Este mensaje no es para reabrir el ticket, sino para documentar la decisión final que habíamos tomado en su momento junto al equipo de Desarrollo sobre los estados de la tabla como organismo y sus elementos internos. Al día de hoy, en Storybook se encuentra la versión correcta de la tabla, pero no se vio impactado el cambio ni en la ficha, ni en el UI Kit; debemos actualizar desde Diseño nuestros recursos y la web de Estándares.

### ¿Qué sucedió? (Hablamos específicamente sobre los estados de las filas)

La razón por la que quedó como está en Storybook es porque las filas o elementos que no son accionables no tienen estados, no son "focuseables" ni interactivos. También, como la tabla es responsiva y tiene la barra, se focuseaba completa como organismo, y no era posible que saltara de ese focus del organismo al de las filas, para luego igual tener focus sobre los elementos internos, era todo un choclo de focuses, digamos.

### ¿Qué queda pendiente por hacer?

- [ ] **Actualizar el UI Kit:** eliminar los estados específicos sobre las filas, ya que son solo los accionables internos los que tienen alguna interacción.
- [ ] **Actualizar la ficha en la web de Estándares:** eliminar el contenido y ejemplos referentes a los estados de las filas, que están visibles hoy día en la ficha.

**Comment by marusaad** [comment]
UI Kit y Ficha actualizados:


![Image](https://github.com/gcba/estandares/assets/136834096/789a85b5-f74c-4a1f-8043-26c7d8b6c23b)

**Comment by Diehault** [comment]
¡Hola! 🐑

Actualizamos el componente aprovechando la actualización general de la guía tipográfica.

### ¿Qué hicimos?
- Actualizamos las moléculas internas que hacen parte del organismo.
- Actualizamos los estilos tipográficos dentro del organismo (para las celdas que contienen texto plano).
- Eliminamos de los componentes base las filas con estados (.EstadosFila), ya que no son las filas las que tiene estados en sí, sino las moléculas internas. Esto se charló con el equipo de Desarrollo y se comprobó con lo que disponibilizamos desde Storybook.

### ¿Cómo se ve ahora la página del componente en la librería del UI kit?
![Image](https://github.com/user-attachments/assets/9bd7d43b-0cfb-4d8e-9e53-8254ab1d1282)

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [ ] El componente se ajusta a la grilla 4px.
- [ ] El componente tiene una medida definida para mobile, tablet y desktop.
- [ ] El componente tiene una modulación definida para mobile, tablet y desktop.
- [ ] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [ ] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Sumamos la variante para dispositivos Tablet, con un width de 696px (100% del ancho).
Arreglado | -
Eliminado | -
Obsoleto | -
Cambiado | **Ajustes al tamaño fijo de las filas (componente base .fila)** El nuevo width para la variante al 100% de 1108px. <br> El tamaño de la variante al 75 % cambió a 728px de width.

## ✏️ Notas

- **[EV]**: Revisar la ficha del componente

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto |
Cambiado | Cambiamos el botón que va dentro de la tabla por un $btn-tertiary-outlined. En base a las nuevas guidelines para el uso de las variantes de los botones, definimos que en la tabla debe haber botones terciarios (en vez de primarios) porque las acciones de la tabla son repetitivas. 

## ✏️ Notas
**Determinamos que el enlace por defecto viene como enlace de texto.** El componente enlace no es suficientemente customizable para incluirlo dentro de la tabla, por lo que optamos por una decisión igual al componente Tarjetas. Esto estará así hasta que Figma haga efectiva la personalización de los subrayados.
