### ISSUE TITLE
Definir uso de la tipografía Nunito y Open Sans

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#30]
Mostrar los usos y variable de las tipografías

- [x] Tamaño
- [x] Variables
- [x] Interletra
- [x] Interlinea

**Comment by mathiassassone1** [comment]
Dejo la propuesta de uso de la tipografía, mostrando su uso compositivo y en grilla.

@Vpappacena @aloyber @Fcunsolo
[Tipografía.pdf](https://github.com/gcba/estandares/files/4871455/Tipografia.pdf)
