### ISSUE TITLE
Estilos de Color

### ISSUE THREAD

**Issue by camilembo** [gcba/estandares#300]
# Estilos de color
**Nombre en Obelisco**
Paleta de colores

**Tipo de componente**
Guía de estilo

**Referencias de Bootstrap**
[Theming Bootstrap](https://getbootstrap.com/docs/4.6/getting-started/theming/#color) | [Utilities: Colors](https://getbootstrap.com/docs/4.6/utilities/colors/)

**¿Qué tenemos en Obelisco actualmente?**
[Estilos de color en Estándares](https://gcba.github.io/estandares/gu%C3%ADas_de_estilos/paleta_de_colores/) | [UI Kit](https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/UI-KIT---Obelisco?type=design&node-id=618%3A8338&mode=design&t=mgB0TjQKBEktnNOu-1) | [Excel con Desarrollo](https://docs.google.com/spreadsheets/d/1g3CYWFPcesvJZkq3yxyl6-JXpD2jrOHsTBkcFNKOlug/edit#gid=1942446526)

## Requerimientos

- Revisar que los colores disponibles desde diseño (UI Kit) y desde desarrollo (Storybook) coincidan.
- Evaluar la accesibilidad y contraste de todos los colores teniendo de referencia los casos de uso actuales.
- Reestructurar la arquitectura de la paleta de colores (trabajar el paso de estilos puros dentro del UI Kit a variables compartidas con desarrollo).
- Revisar la nomenclatura de la paleta de colores, teniendo en cuenta el cómo vienen de Bootstrap y nuestra capacidad de intervención.
- Proyectar el uso de colores en productos digitales por fuera del entorno de NBA o Gobierno, dentro de lo que podría ser la personalización/customización de Obelisco como sistema de diseño (entenderlo como patrones de diseño para internos y externos).
- Estructurar los estilos de manera tal que ajustar los colores sea lo menos complicado posible. Tener en cuenta la posibilidad de cambios a futuro en la imagen del GCBA que puedan impactar en Obelisco.

**Comment by marusaad** [comment]
En la branch de actualización de Tipografía dentro del UI Kit, se trabajó sobre la page de color incorporando la nueva plantilla. Se colocó en la page la etiqueta "En revisión". 


![Image](https://github.com/user-attachments/assets/23ffb0c6-8e3d-45cf-8945-ab910e513f8a)

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA).

## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Sumamos la arquitectura de colores por capas, con 3 capas definidas: primitiva, semántica y funcional.<br>Visibilizamos las rampas de colores de todos los colores que usamos en Obelisco.<br>Identificamos cada una de las variables de color y de dónde vienen.<br>Definimos los colores y variantes de colores que pueden usarse en combinación con los colores de texto.<br>Sumamos el uso que tiene cada color en la capa semántica y en la capa funcional.
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | 

## ✏️ Notas
- **Definición de combinación de colores:** anotamos qué colores pasan los criterios de accesibilidad según WCAG 2.2, con la combinación de colores para AA y AAA utilizando los colores de texto.
- **Colección de variables:** para implementar la aquitectura de colores por capas utilizamos las colecciones de variables. Similar al trabajo con tipografía y grillas, definimos diferentes colecciones para separar la capa primitiva de la semántica y de la funcional, y viceversa. Este esquema nos permite modular e independizar la vinculación de colores de su valor y su función final.
