### ISSUE TITLE
Casilla de verificación (checkbox)

### ISSUE THREAD

**Issue by marusaad** [gcba/estandares#302]
# Casilla de verificación (Checkbox)

**Nombre en Obelisco**
Casilla de verificación (checkbox)

**Tipo de componente**
Átomo | **Molécula** | Organismo | Plantilla

**Links**
[UI Kit](https://www.figma.com/design/ToGlPBzfp1gKDmaCwKWtXS/UI-KIT---Obelisco?m=auto&node-id=21857-9937&t=p1qG5ar7TIdEIzEM-1) | [Estándares](https://gcba.github.io/estandares/componentes/control-de-formulario/) | [Storybook](https://gcba.github.io/Obelisco/?path=/story/formulario-checkbox--casilla-multiple) 

**Ejemplo en Bootstrap**
[Checkbox](https://getbootstrap.com/docs/5.3/forms/checks-radios/)
 
**Requerimiento**
- Actualizaciones pequeñas del componente en estilos, estados, iconografía y accesibilidad. 
- Empatar UI Kit con Storybook

**Comment by marusaad** [comment]
Se realizaron actualizaciones de diseño en el componente _casilla de verificación_. 

- Se nomenclaron nuevamente las propiedades del componente.
- Se incorporaron los estados sobre, foco y deshabilitado para cuando el componente tiene tildada la casilla de verificación. 
- Se agregó una propiedad de texto y una propiedad booleana a la etiqueta.
- Se revisaron espaciados y anchos máximos.
- Se eliminó la variante de "validación" con el checkbox en rojo por el momento. 
- Se actualizó la iconografía del check. 

_Evolutivos_

- Estado indeterminado: sólo se puede hacer con Javascript
- Armado de organismo de "lista de casillas de verificación" que dé cuenta de espaciados, títulos y subtítulos de una lista de checkboxes. 
- Error: ver qué sucede (si es que sucede) cuando hay un error al tildar la casilla. ¿Es necesario un mensaje?



![Image](https://github.com/gcba/estandares/assets/136834096/d9452bfb-69b7-439c-8521-e602876ff6a5)



![Image](https://github.com/gcba/estandares/assets/136834096/648ef919-5e94-4a0c-ae7c-36e344d7dd35)


Queda para revisión @camilembo

**Comment by camilembo** [comment]
Se hace merge de la page Formularios que contiene la Casilla de verificación en el UI Kit para poder construir la tabla de forma completa
02/02/2024

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] El componente tiene una modulación definida para mobile, tablet y desktop.
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | 

## ✏️ Notas

- Este componente no tuvo cambios durante la migración.

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Agregamos el estado "Error" que se aplica con la propiedad de Selección=Destildado
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado |  Se actualizó el color del componente con la nueva paleta de colores.

## ✏️ Notas
Actualizamos los colores de la plantilla del componente con la nueva colección de variables.
