### ISSUE TITLE
Formularios

### ISSUE THREAD

**Issue by marusaad** [gcba/estandares#309]
# Formularios

**Nombre en Obelisco** 
Formularios

**Tipo de componente** 
Molécula

**Ejemplo en Bootstrap**
 [Forms](https://getbootstrap.com/docs/4.6/components/forms/) | [Input Group](https://getbootstrap.com/docs/4.6/components/input-group/)

**Ejemplos de aplicación en BA** 
[Ayuda escolar](https://ayudacuotaescolar.buenosaires.gob.ar/inscripcion/) | [Formulario de contacto](https://buenosaires.gob.ar/vicejefatura/bienestar-integral/formulario-de-contacto) | [Formulario de consultas](https://buenosaires.gob.ar/jefaturadegabinete/desarrollo-urbano/formulario-de-consultas-desarrollo-urbano) | [Datos de contacto](https://buenosaires.gob.ar/formulario-de-datos-de-contacto) | [Inscripción BA te acompaña](https://buenosaires.gob.ar/formulario-de-inscripcion-ba-te-acompana) | [Acogimiento familiar transitorio](https://buenosaires.gob.ar/inscripcion-al-sistema-de-acogimiento-familiar-transitorio) | [Inscripción escolar 2024](https://inscripciones.buenosaires.gob.ar/#)

## Requerimientos

- Revisar el componente y sus variantes
- Chequear accesibilidad
- Tener en cuenta las posibilidades en Drupal y Angular 
- Construir lineamientos para el agrupamiento y uso de los formularios
- Analizar posibilidad de construir patterns

**Comment by marusaad** [comment]
¡Hola! 🧙

Aprovechando las actualizaciones que se hicieron con el trabajo de la nueva guía tipográfica para Obelisco, también actualizamos la página de "Formularios" dentro del UI kit.

### ¿Qué hicimos?
Todos los formularios están basados en el componente base de “main_form”, a pesar de que había 2 componentes base más en la página: “Label” (la etiqueta de los forms) y un número para calendarios. Dentro de la página no se utilizaban los otros dos componentes base, que ya no aparecen más, por lo que fueron eliminados. Dejamos el componente base de “main_form”, porque es un buen abordaje el tratarlo de esta forma.

- Actualizamos la plantilla de la página de "Formulario" dentro del UI kit.
- Actualizamos toda la iconografía cambiando los íconos-componente custom que estaban dentro de la page de iconografía por los de la librería de Material Design. 
- Existían 2 campos de buscador, uno que no tenía estados ni propiedades, y otro que es el que quedó visible. Eliminamos el otro componente porque era redundante. En su momento hablamos sobre este buscador, sobre todo por tema del componente “Encabezado (header)". 

### Evolutivos
- Se debe analizar en profundidad esta page especialmente en términos constructivos, para mejorar la experiencia de consumo de los mismos. 
- Revisar y empatar nomenclaturas del componente entre la web de Estándares, Storybook y el UI Kit.
- Añadir todos los estados a cada input y las propiedades faltantes. 
- Empatar estados de el input de radio con la casilla de verificacación para que se comporten correctamente. 
- Pensar este componete como patrón. Profundizar en usos y buenas prácticas en la ficha para estandarizar su uso. 

### ¿Cómo se ve ahora la página en el UI kit?

![Image](https://github.com/user-attachments/assets/abb514f8-771c-44d4-a311-14c2bd9153a0)

**Comment by marusaad** [comment]
### Evolutivos de agosto 2024 respecto a Formularios y en base a la migración a Bootstrap 5 
- Es necesario analizar y disponibilizar una variante del input de buscador deshabilitado desde diseño ya que podría utilizarse en Backoffice 
- Es necesario analizar si abrir las posibilidades a obelisco como sistema de código abierto para que se puedan swapear los íconos de mensajes semánticos que se dan en los campos de éxito y de error. Por ahora los dejamos para que sólo sean esos porque para la migración estamos incluyendo mejoras ágiles.

**Comment by marusaad** [comment]
De cara a la migración a Bootstrap 5 se realizaron **mejoras ágiles** sobre el componente de casilla de verificación (checkbox) con el objetivo de estandarizar su comportamiento con el botón de radio. 

Para esto se creó el componente base _.Checkbox_ a partir del cual se construye la molécula de casilla de verificación. 

![2](https://github.com/user-attachments/assets/0df2dab0-c53c-4f15-acf3-4bd1c6dece02)


- Se incorporaron íconos de Material Design (antes contaba con íconos custom como SVGs) 
- Se eliminó el gap de 4px entre el contenedor que engloba al input y la etiqueta para mejorar ópticamente los espaciados
- El input tiene un padding de 8px en todos los lados

**Evolutivos y puntos de dolor**
- Analizar la accesibilidad del componente especialmente en el tamaño de los inputs. 
- Analizar la creación de un organismo de lista para utilizar en formularios con un placeholder, texto de asistencia y lista de opción de selección múltiple como se muestra en [Storybook](https://gcba.github.io/Obelisco/?path=/story/formulario-checkbox--casilla-multiple) 
- Analizar la creación de una variante de casilla de verificación de error
- Actualizar especificaciones en la ficha y usos 
- Especificar que para los casos en los que se precise una casilla al final de un formulario (por ejemplo aceptar términos y condiciones), se permita que la etiqueta tenga un ancho máximo mayor. Esto se puede tomar cuando se vean los formularios como patrones o se realice un template de formularios. 
- Analizar si es necesaria una variante con fondo como se muestra actualmente en [Storybook](https://gcba.github.io/Obelisco/?path=/story/formulario-con-fondo--casilla-de-seleccion) (no la tenemos en el UI Kit)

![Tabla](https://github.com/user-attachments/assets/faa8053d-30e3-4f35-ab46-83fb340df05f)

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] El componente tiene una modulación definida para mobile, tablet y desktop.
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Sumamos una variante tablet con 336px width de los siguientes campos de formulario: campo de texto simple, campo de selector, campo de fecha, campo numérico, campo de búsqueda, campo de área de texto.
Arreglado | Cambiamos el width del campo numérico en desktop a 158px, para que coincidiera con la grilla.
Eliminado | 
Obsoleto | 
Cambiado | Cambió a 348px el width de los siguientes campos de formulario en su versión desktop: campo de texto simple, campo de selector, campo de fecha, campo de búsqueda, campo de área de texto. <br> El width del campo numérico en mobile pasó a 156px, coincidiendo con la grilla.

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado |  Se incluyeron propiedades de swap y booleanas en el componente base .Input-Completo que eran necesarias para la adaptación del componente en los diferentes campos de texto. Incorporamos: 7 variantes booleanas y 3 variantes de swap. <br> Se incorporaron textos de ejemplo como placeholders dentro de los inputs faltantes. <br> Se incluyó el divisor que se utiliza en el componente buscador dentro del componente base .Input-Completo, para utilizar siempre el componente base y no depender de otra estructura en este caso. <br> Se incorporó la variante de buscador con botón de búsqueda. 
Arreglado | Se arregló el padding interno de los inputs del formulario. Tenían una altura fija de 48px y padding superior de inferior impar de 13px. Se cambió a 12px y se continuó dejando la altura fixed en 48px.  
Eliminado | Se eliminó la estructura vieja del componente y se incorporó la estructura estándar basada en el componente base .Input-Completo en el componente de input de búsqueda. 
Obsoleto | 
Cambiado | Se actualizaron os estilos del componente input de búsqueda para identificar lo que sucede mientras la persona está escribiendo (estado en foco/activo). <br> Se actualizó el buscador de tipo predeterminado. <br> Se cambió la antigua variante de “Tipo” por el nombre de “Color” y asignar la variante “Tipo” para identificar el buscador con botón accionable y el buscador predeterminado. 

## ✏️ Notas
Se asignaron las variables correspondientes de color al componente y a la plantilla del UI Kit. 

## ✏️ Evolutivos
Revisar la construcción del componente de TextArea para que se acomode a la grilla 4x4. 
Trabajar los usos de cada variante de color para poder mostrarlos en la ficha actualizada.
