### ISSUE TITLE
Armar el componente Cards

### ISSUE THREAD

**Issue by aloyber** [gcba/estandares#31]

**Comment by Fcunsolo** [comment]
[Pendiente revisión]
Comparto el boceto del componente Cards.

@aloyber @mathiassassone1 @Vpappacena 
[Web - 1366 x 768 - 12 columnas – CARDS.pdf](https://github.com/gcba/estandares/files/4921144/Web.-.1366.x.768.-.12.columnas.CARDS.pdf)

**Comment by Fcunsolo** [comment]
[Pendiente revisión]
Actualización de Componente Cards [2020-07-17]

@aloyber @mathiassassone1 @Vpappacena 
[CARDS-20200717.pdf](https://github.com/gcba/estandares/files/4939531/CARDS-20200717.pdf)

**Comment by Jinik** [comment]
Van algunos comentarios basados en lo que hablamos ayer, pero también de algunas experiencias pasadas.

Para muchos de los comentarios voy a usar de referencia [la página de ANDIS en Argentina.gob.ar](https://www.argentina.gob.ar/andis) que se compone básicamente de diferentes listados de tarjetas, lo cual no es ideal.

## Cliqueable o no

Un poco sobre lo que hablamos ayer, es importante definir si las tarjetas van a interactuar como bloque o van a tener diferentes elementos internos que sean interactivos.

También podrían definirse dos estados diferentes que sean visualmente notorios.
En poncho hacíamos eso, se usa otro color de fondo y se remueven bordes y sombras, de esa forma queda como un panel "deshabilitado". Me fijé recién y no está en la documentación 🤦 .

![image](https://user-images.githubusercontent.com/1561463/87858983-5919b600-c908-11ea-9348-66e3bb8bfb2e.png)

En la imagen se pueden ver:
1. Panel deshabilitada
2. Panel cliqueable
3. Panel con hover

El sistema del gobierno de Australia [hace algo similar](https://designsystem.gov.au/components/card/).
Incluso, como otra idea, se podría usar la línea de color del costado que tienen algunas para definir esa diferencia.

En [Argentina.gob.ar](https://www.argentina.gob.ar/justicia) podríamos llegar a tener los dos tipos juntos, por ejemplo en las listas de secretarías y subses en las páginas de ministerios.

![image](https://user-images.githubusercontent.com/1561463/87859568-76e91a00-c90c-11ea-9f23-de510361482e.png)


## Comportamiento en listas

Algo a tener en cuenta es cómo se define el tamaño de cada tarjeta y cómo se comportan en el contexto de tener varias tarjetas en una grilla con diferentes contenidos y largos de textos.

Comentario al margen, **los textos usados en estos diseños son más que ideales**, es muy difícil que se pueda realmente llegar a contenidos con 1 o 2 palabras de título y 3 de descripción como en los `indicadores simples`.

Respecto a los espacios, este es un caso super extremo, pero es [un caso real en argentina.gob.ar hoy](https://www.argentina.gob.ar/andis).



![image](https://user-images.githubusercontent.com/1561463/87859257-15c04700-c90a-11ea-9cc6-6dfc444d1e20.png)

**Comment by Vpappacena** [comment]
Para avanzar con este elemento CARD  tenemos que:  extender la revisión en otros productos de GCBA para entender que tipo de componente están necesitando los productos digitales que todo lleva a utilizar CARD. 
Entender la necesidad y como se utiliza hoy,  como para trabajar si este componente se divide en más componentes para poder cubrir la necesidad de los productos.

**Comment by aloyber** [comment]
Subo actualización del componente
@Vpappacena @mathiassassone1 @Fcunsolo 
[CARDS-20200717.pdf](https://github.com/gcba/estandares/files/5105108/CARDS-20200717.pdf)

**Comment by victoriajustina** [comment]
Hola @aloybe, 

Tenemos tres grupos principales de tarjetas. Las de Programas y servicios, las de Eventos y las de Institucionales. En esta página se describen las funcionalidades de cada una de ellas: https://www.buenosaires.gob.ar/estandares/contenidos-digitales/componentes/tarjetas

Te dejo por acá algunos ejemplos: 

Programas y servicios: 
https://www.buenosaires.gob.ar/culturaencasa/que-ver
https://www.buenosaires.gob.ar/usinadelarte
https://www.buenosaires.gob.ar/cultura/usina-del-arte/el-aula-cursos-y-talleres

Eventos e Institucionales (con icono): https://www.buenosaires.gob.ar/gobierno/institutodeformacionpolitica

Institucionales (con icono): https://www.buenosaires.gob.ar/cultura/museos

Avisame cualquier cosa, 

Saludos, 

Vicky

**Comment by aloyber** [comment]
Analizamos el trabajo previo que habíamos realizado para el componente de tarjetas y pudimos sacar algunas conclusiones:

- Queremos darle versatilidad a las áreas en cuanto a la construcción de las tarjetas donde puedan utilizar diferentes átomos, con un orden determinado de aparición.
- Los componentes no solo pertenecen a la web de buenos aires, sino a todos sus productos
- Simpleza
- Buscamos un comportamiento general para que sea adecuado a todos los productos de buenos aires.

Determinamos dos tipos de card:

- Con contenedor. Puede componerse por imágenes; íconos; overline; título; subtítulo; descripción; caption; botones (en ese orden). Las tarjetas no podrán tener todos estos átomos, sino que se especificarán reglas de uso y cantidad de columnas que pueden ocupar, con una cantidad máxima de texto. La tarjeta tendrá una sombra que indique el comportamiento de realizar click o tap.

- Sin contenedor. Puede componerse por íconos; título; descripción; enlace (en ese orden). Podrán tener todos esos átomos y se especificarán reglas de uso y cantidad de columnas que pueden ocupar, con una cantidad máxima de texto. La tarjeta al ser sin contenedor, no será accionable. El enlace tomará el protagonismo para realizar una acción determinada.

[Tarjetas.pdf](https://github.com/gcba/estandares/files/5312584/Tarjetas.pdf)
@Vpappacena @nirougi

**Comment by Vpappacena** [comment]
-Probar con texto reales según temas de la ciudad.  
-Ver como funciona cuando son más lineas 
- Que sucede con la morfología cuando la información no son exactamente iguales.

**Comment by aloyber** [comment]
[Web 1920 – 4.pdf](https://github.com/gcba/estandares/files/5520172/Web.1920.4.pdf)

@Vpappacena subo el pdf que estuvimos trabajando donde hay ejemplos de como se comportan las tarjetas cuando la info no es exactamente igual. Hay tarjetas con imágenes, títulos y texto. Se hizo la prueba en una mesa de trabajo de un proyecto en particular.
