### ISSUE TITLE
Etiquetas

### ISSUE THREAD

**Issue by LuCostas** [gcba/estandares#310]
# Etiqueta

**Nombre en Obelisco**
Etiqueta

**Tipo de componente**
Molécula

**Links**
[UI Kit](https://www.figma.com/design/ToGlPBzfp1gKDmaCwKWtXS/UI-KIT---Obelisco?node-id=826-7974) | [Branch](https://www.figma.com/design/EJPbdgHGQ6hJRfrBOJ5ieR/Grillas-2.0?node-id=826-7974) | <s>Ficha Figma</s> | [Estándares](https://gcba.github.io/estandares/componentes/etiquetas/) | [Storybook](https://gcba.github.io/Obelisco/?path=/story/componentes-etiqueta--simple) | <s>Informe</s> | <s>Excel</s>

**Ejemplo en Bootstrap**
[Badge](https://getbootstrap.com/docs/5.3/components/badge/)

**Ejemplos de aplicación en BA**
[Home](www.buenosaires.gob.ar)

**Comment by Diehault** [comment]
¡Hola! 🐙

Actualizamos el componente aprovechando la actualización general de la guía tipográfica.

### ¿Qué hicimos?
- Actualizamos la plantilla del componente en la librería del UI kit.
- Actualizamos los estilos tipográficos del componente.
- Actualizamos la nomenclatura de las diferentes propiedades del componente.

### ¿Cómo se ve la página del componente en el UI kit?
![Image](https://github.com/user-attachments/assets/d408d4ca-0562-49e3-8234-14572b6c06c2)

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Tickets relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] <s>El componente tiene una medida definida para mobile, tablet y desktop</s>. **[no aplica para este componente]**
- [x] <s>El componente tiene una modulación definida para mobile, tablet y desktop</s>.  **[no aplica para este componente]**
- [x] <s>El componente tiene su handoff para desarrollo y está marcado como ready for dev</s>. **[no aplica para este componente]**
- [x] El componente está documentado. 


## 🕰️ Changelog
No se realizaron cambios en esta revisión. 

## ✏️ Notas
No hay ninguna nota para mostrar.

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [ ] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [ ] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA).

## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Actualizamos el componente incluyendo la colección de variables con la nueva paleta de colores.
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | 

## ✏️ Notas
- El componente Etiquetas tiene un grupo dentro de la capa funcional de la nueva arquitectura de variables, donde se encuentran los colores asignados que solo se utilizan dentro de este componente. La lógica de colores es igual a la lógica del componente Alertas, con los mismos valores para fondos y bordes según el tipo (valor semántico).
