### ISSUE TITLE
Calendario

### ISSUE THREAD

**Issue by LuCostas** [gcba/estandares#313]
Nombre en Obelisco: Calendario
Tipo de componente: Organismo
Ejemplo en bootstrap: [Tablas](https://getbootstrap.com/docs/5.1/content/tables/#overview). El calendario es una tabla. 
Ejemplo de aplicación en BA: [Calendario interreligioso](https://buenosaires.gob.ar/cultos/calendario-interreligioso) | [Calendario 2024](https://buenosaires.gob.ar/espaciopublicoehigieneurbana/calendario-2024)    

**Requerimiento**
- Empatar componente entre Storybook y UI Kit
- Chequear usabilidad y accesibilidad del componente

**Comment by marusaad** [comment]
¡Hola! 🦥

Actualizamos el componente aprovechando la actualización general de la guía tipográfica.

### ¿Qué hicimos?

- Se cambiaron los estilos de texto de los componentes base _.Día_ y _.Referencias_ de Nunito a Open Sans en Cuerpo/M. Se realizó este cambio porque Titulares/S tiene un interlineado de 20px y al incorporarlo cambiarían todas las  medidas del organismo. 
- Se cambiaron los estilos tipográficos para el encabezado del calendario (Titulares/L) y los días de la semana (Curepo/S) según la nueva escala. 
- Se cambiaron los estilos tipográficos para las referencias (Cuerpo/S) y el gap entre cada una (antes era 4px, ahora es 8px)
- Corregimos propiedades

### ¿Cómo se ve la página del componente en el UI Kit?

![Image](https://github.com/user-attachments/assets/04c3c66b-d92f-4362-8cb0-a0c224e78a45)

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 


### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [ ] El componente se ajusta a la grilla 4px.
- [ ] El componente tiene una medida definida para mobile, tablet y desktop.
- [ ] El componente tiene una modulación definida para mobile, tablet y desktop.
- [ ] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [ ] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | -
Arreglado | Actualmente, el Calendario funciona internamente con la propiedad “fill” para el armado de las columnas, lo que hace que en Mobile la distancia entre ítems/días/números no sea siempre un número entero. En Tablet, al ajustar el tamaño a 3 columnas de la grilla, sí quedan números enteros de espaciado que coinciden con la grilla de 4px.
Eliminado | -
Obsoleto | -
Cambiado | Viendo cómo se comportan los espacios en Mobile, y teniendo en cuenta que la diferencia de tamaño no es mucha con lo que debería ocupar en Calendario en Tablet, podríamos únicamente cambiar el width general del Calendario y todos los elementos internos se adaptarían.

## ✏️ Notas

- **[EV]**: -

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | Cambiamos el color del fondo secundario a $blue/50.

## ✏️ Notas

Creamos un grupo dentro de la capa funcional de variables exclusivamente para el organismo Calendario.
