### ISSUE TITLE
Barra de desplazamiento (scrollbar)

### ISSUE THREAD

**Issue by Diehault** [gcba/estandares#314]
**Nombre en Obelisco:** barra de desplazamiento.
**Tipo de componente:** átomo.
**Necesidad solicitada por:** Diseño.

### Requerimiento

Actualizar el componente en el UI Kit (construcción del componente y plantilla).
Unificar la barra de desplazamiento que aparece en Storybook con la que está en el UI Kit.

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Tickets relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [ ] El componente se ajusta a la grilla 4px.
- [ ] El componente tiene una medida definida para mobile, tablet y desktop. **[no aplica para este componente]**
- [ ] El componente tiene una modulación definida para mobile, tablet y desktop. **[no aplica para este componente]**
- [ ] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [ ] El componente está documentado. 


## 🕰️ Changelog
No se realizaron cambios en esta revisión. 

## ✏️ Notas
No hay ninguna nota para mostrar.
