### ISSUE TITLE
Listas - Lista informativa

### ISSUE THREAD

**Issue by LuCostas** [gcba/estandares#315]
Nombre en Obelisco: Lista informativa
Tipo de componente: Molécula
Ejemplo en bootstrap: 
Ejemplo de aplicación en BA: https://buenosaires.gob.ar/tramites/consulta-de-usos
Requerimiento: Construir componente de lista informativa (molécula) y una lista de ítems con subtítulo (organismo)
- Dispositivos: desktop y mobile
- Variantes: con check para requisitos y con bullet para información / con título y sin título para la lista como organismo.

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] El componente tiene una modulación definida para mobile, tablet y desktop.
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | Width de la variante desktop a 728px.

## ✏️ Notas

- **[EV]**: se puede sumar una variante tablet, como para tener un tamaño predeterminado por dispositivo. Sin embargo, no es algo que consideremos necesario/obligatorio, porque se compra como texto en dispositivos móviles, al 100 %.

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado |  Se actualizó el color del componente con la nueva paleta de colores.

## ✏️ Notas
Actualizamos los colores de la plantilla del componente con la nueva colección de variables.
