### ISSUE TITLE
Desplegable de navegación

### ISSUE THREAD

**Issue by LuCostas** [gcba/estandares#316]
# Desplegable de navegación

**Nombre en Obelisco**
Desplegable de navegación

**Descripción**
Este tipo de desplegables permite acceder a opciones de navegación y funcionalidades adicionales de manera organizada, desplegándolas de forma vertical u horizontal.

**Tipo de componente**
Átomo | **Molécula** | Organismo | Plantilla

**Links**
[UI Kit](https://www.figma.com/design/ToGlPBzfp1gKDmaCwKWtXS/UI-KIT---Obelisco?m=auto&node-id=11970-29458&t=NKlXrVPsDVFIJD18-1) | [Ficha Figma](https://www.figma.com/design/Pi8vXNQiMDtCNvV1aTCQX7/Fichas?m=auto&node-id=4533-75&t=eaK5PJa16YhVHY77-1) | [Estándares](https://gcba.github.io/estandares/componentes/desplegables/desplegables_navegacion/) | [Storybook](https://gcba.github.io/Obelisco/?path=/story/componentes-desplegables-de-navegaci%C3%B3n--dropdown-icons)

Ejemplo en Bootstrap
Ejemplos de aplicación en BA

**Requerimiento**
Generar un desplegable que pueda ser utilizado de manera independiente o que esté presente dentro del Header. Tiene como fin que el usuario pueda navegar un sitio.

**Comment by Diehault** [comment]
¡Hola! 🚗

Actualizamos el componente Desplegable de navegación aprovechando la actualización general de la guía tipográfica.

### ¿Qué hicimos?
- Actualizamos la plantilla del componente en el UI kit.
- Actualizamos los estilos tipográficos del componente.
- Cambiamos la iconografía que quedó fuera de versión por íconos de la librería de Material Design Icons.
- Actualizamos la nomenclatura de las propiedades del componente y la jerarquía de las mismas.

### ¿Qué cosas consideramos como evolutivos?
- Hay frames y capas dentro del componente que pueden simplificarse, renombrarse o pensarse de otra forma para hacer más sencilla la estructura.
- Se pueden sumar medidas mínimas y máximas, como para ajustar y hacer más flexible el funcionamiento del componente, ya que no siempre tiene el mismo tamaño y depende del contexto.

### ¿Cómo se ve la página del componente en el UI kit?
![Image](https://github.com/user-attachments/assets/8411211f-ea38-45a5-89b4-ad7d45413b02)

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#212 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [ ] El componente se ajusta a la grilla 4px.
- [ ] El componente tiene una medida definida para mobile, tablet y desktop.
- [ ] El componente tiene una modulación definida para mobile, tablet y desktop.
- [ ] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [ ] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | v.0
-- | --
Agregado |  Se creo la variante Tablet. Se le asigno un ancho máximo de 336 px. (3-col en la nueva grilla) al desplegable y a las opciones de navegación (tanto las predeterminadas como las opciones en cascada).
Arreglado | En desktop, al desplegable y las opciones (tanto del tipo predeterminadas como en cascada) se les asignó un ancho máximo de 348px (en la grilla desktop nueva 4-col). <br> En Mobile, se le asignó al desplegable un ancho máximo de 328px, en la grilla Mobile nueva 2-col (100%).
Eliminado | Cell
Obsoleto | Cell
Cambiado | Cell

## ✏️ Notas

- **[EV]**: -

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado |  Se actualizaron los íconos por default del componente para que sean más representativos del contexto de uso. 

## ✏️ Notas
Actualizamos los colores de la plantilla del componente con la nueva colección de variables.
