### ISSUE TITLE
Armar el componente colapsables

### ISSUE THREAD

**Issue by aloyber** [gcba/estandares#32]

**Comment by aloyber** [comment]
Subo la primer versión de colapsables
@Fcunsolo 
[Colapsables.pdf](https://github.com/gcba/estandares/files/4885688/Colapsables.pdf)

**Comment by nirougi** [comment]
Lo veo bien, pero creo que algunos de los detalles que se agregan en la ficha deberían estar en esta tarea que define más cómo es y cómo debería comportarse.

Por ejemplo:
- La sección de estructura sirve más para que nosotros lo integremos al código que para el usuario que lo vaya a usar.
- La parte de tipografía igual, para la persona que lo vaya a usar no le modifica mucho el tipo y tamaño, se define en el código.
- Para la parte de accesibilidad igual, aunque sí tiene más sentido mencionarlo en la ficha como algo importante.

**Comment by Vpappacena** [comment]
@nirougi , me llego estos punto al issu para cuando armemos la ficha del componente
