### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by marusaad** [gcba/estandares#328]
## Logo

**Nombre en Obelisco**
Logo

**Tipo de componente**
Átomo

**¿Qué tenemos en Obelisco actualmente?**
[UI Kit](https://www.figma.com/design/ToGlPBzfp1gKDmaCwKWtXS/branch/Jj1P51x0YSPq0jvjm7Wemx/UI-KIT---Obelisco?node-id=651-8097&t=Se2EmJvBJovFwfnC-0)

**Comment by marusaad** [comment]
Durante la actualización de tipografía se revisó la page, aplicando la nueva plantilla y actualizando los logos según el nuevo manual de marca. 


![Image](https://github.com/user-attachments/assets/11690ce4-bd41-422b-bd9b-e6ed52c2b24b)

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] El componente tiene una modulación definida para mobile, tablet y desktop.
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | 

## ✏️ Notas

- Este componente no sufrió cambios durante la migración.

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento


### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.

## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Se agregó la variante de Fondo oscuro para el logo escudo vertical. De esta forma, todos los logos cuentan con versiones para fondo claro y oscuro. <br> Se agregaron textos descriptivos para el uso de cada tipo de logo, invitando a los colaboradores a consultar el Manual de marca de la Ciudad para más información. 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | Se cambiaron los colores de los logos según el nuevo manual de marca del GCBA. 

## ✏️ Notas
En el caso de este componente, se utilizó el color de fondo hexadecimal del manual de marca del GCBA, ya que nuestra paleta de color tiene algunas diferencias por temas de accesibilidad.
