### ISSUE TITLE
Bloque de información

### ISSUE THREAD

**Issue by Diehault** [gcba/estandares#329]
# Bloque de información
**Nombre del componente**
Bloque de información

**Tipo de componente**
Molécula

**Referencias de uso**
Es un componente proveniente del componente "[Panel chico](https://gcba.github.io/Obelisco/?path=/story/componentes-panel-chico-horizontal--small-panel-horizontal-colors)", al cual ya no le brindamos más soporte, pero sigue estando en Storybook para evitar romper cosas en producción.

## Requerimientos
- Actualizar la plantilla del componente dentro del UI kit.
- Evaluar si el componente cubre alguna necesidad dentro del universo Obelisco y cuál es.
- Implementar el modo "Fuera de versión" sobre el componente para promover el no uso del mismo, ya que es un componente al que no se le dará más soporte desde el sistema de diseño.
- Pensar en una alternativa/solución que cubra la necesidad por la que está hoy día dentro del sistema de diseño.

**Comment by marusaad** [comment]
Actualizamos la imagen del bloque de información por la misma que se utiliza en las tarjetas horizontales para mantener la consistencia entre componentes.
