### ISSUE TITLE
Armar el componente stepper

### ISSUE THREAD

**Issue by aloyber** [gcba/estandares#33]

**Comment by aloyber** [comment]
El componente de stepper lo incluimos en los controles de formulario
@Vpappacena

**Comment by Vpappacena** [comment]
@aloyber @Fcunsolo , trabajaron en el paso paso Horizontal , deberíamos tener en cuenta el formato vertical tambien :)

**Comment by aloyber** [comment]
Lo incluímos en una v2

**Comment by Jinik** [comment]
Algo a tener en cuenta también es el comportamiento en dispositivos móviles donde no solamente debería ser vertical, además no hay tanto espacio como en una computadora.

También tendría en cuenta que este componente viene atado a todo un patrón de separar un formulario en pasos, con ciertos controles de ese comportamiento al final del formulario, con opción de ir para atrás y volver. Yo dejaría este componente para una v2 porque tener el átomo pero no el patrón puede terminar en implementaciones raras.

**Comment by Vpappacena** [comment]
@aloyber , cuando puedas subis el caso del paso a paso a vertical (proyecto educación)

**Comment by nirougi** [comment]
@aloyber @Vpappacena ¿algún avance de este componente?

**Comment by aloyber** [comment]
@nirougi te adjunto el pdf con los componentes..
En el link de adobe se encuentra el archivo para desarollo en la página 7 junto a controles de formularios
https://xd.adobe.com/view/b6ecfadb-037e-446b-a6fc-f0eda5ec3e12-e3bf/screen/8b6cabf9-ada2-40d6-99ef-586da5f1d34f/specs/
[Stepper.pdf](https://github.com/gcba/estandares/files/5202774/Stepper.pdf)

**Comment by nirougi** [comment]
Genial! gracias.

**Comment by Fcunsolo** [comment]
@Vpappacena @nirougi @aloyber @mathiassassone1 

Reabro Issue con la actualización del stepper (desktop / mobile) según las últimas mesas de trabajo.
Este es el componente que va a salir en la V1 de obelisco.

Gracias!

[Stepper.pdf](https://github.com/gcba/estandares/files/5336448/Stepper.pdf)

**Comment by nirougi** [comment]
El focus se hace solo sobre el texto del paso con un recuadro azul.
