### ISSUE TITLE
Ilustraciones temáticas

### ISSUE THREAD

**Issue by Diehault** [gcba/estandares#330]
# Ilustraciones temáticas
**Nombre del componente**
Ilustraciones temáticas

**Tipo de componente**
Átomo

**Referencias del componente**
Son las ilustraciones que aparecen únicamente en la página de inicio en la web de BA, dentro de la sección de "Trámites y servicios".

**Referencia gráfica**
![Image](https://github.com/user-attachments/assets/6202c6c6-7e66-4a50-8a8b-60e91ec4829e)

## Requerimientos
- Actualizar la plantilla del componente dentro de la página del UI kit.
- Actualizar las propiedades del componente y verificar la nomenclatura.

**Comment by Diehault** [comment]
¡Hola! 👀

Actualizamos el componente aprovechando la actualización general de la guía tipográfica para todo el sistema de diseño.

### ¿Qué hicimos?
- Actualizamos la plantilla del componente dentro del UI kit.
- Verificamos las propiedades y la nomenclatura de las mismas.
- Cambiamos el nombre de la página dentro de la librería para que fuese aún más clara la finalidad del componente.

### ¿Cómo se ve ahora la página de "Ilustraciones temáticas"?
![Image](https://github.com/user-attachments/assets/a710a07d-9698-4694-b8f6-b58628a10df6)

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] El componente tiene una modulación definida para mobile, tablet y desktop.
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | 

## ✏️ Notas

- Esta página de componentes no sufrió cambios durante la migración.

**Comment by marusaad** [comment]
# 📢 Nuevo requerimiento


### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## ✏️ Notas
Actualizamos los colores de las ilustraciones según el nuevo amarillo de marca y las variables de la v2.
