### ISSUE TITLE
Pasos de un formulario

### ISSUE THREAD

**Issue by marusaad** [gcba/estandares#331]
# Pasos de un formulario

**Nombre en Obelisco**
Pasos de un formulario (ex Paso a paso)

**Tipo de componente**
Organismo

**Referencias de Bootstrap**

**¿Qué tenemos en Obelisco actualmente?**
[Pasos de un formulario en Estándares](https://gcba.github.io/estandares/componentes/paso-a-paso/)

**Detalles**
Este componente se utiliza para marcar en qué paso se encuentra la persona usuaria cuando realiza un proceso. Generalmente se utiliza dentro del layout propuesto en la ficha para encabezar páginas de formularios con varios pasos. También lo utilizan sistemas externos como TAD.

**Comment by marusaad** [comment]
¡Hola! 🐾

Actualizamos el componente aprovechando la actualización general de la guía tipográfica.

### ¿Qué hicimos?

- Actualizamos el nombre del componente a Pasos de un formulario. Esto ya estaba documentado en Estándares y en Storybook previamente, sólo nos empatamos. 
- Revisamos y cambiamos la nomenclatura de las propiedades
- Renombramos y organizamos las layers internas del componente. 
- Creamos un componente base oculto para el círculo indicador de si el paso está completado o no, con variantes de estado completado/incompleto. 
- Incorporamos la nueva plantilla y añadimos la descripción al componente según la ficha de estándares. }
- Visibilizamos las nested instances.

### Evolutivos
Revisar este componente a nivel conceptual. 

- Si en la ficha se refiere a formularios y también a procesos, ¿no podríamos tener un componente más agnóstico que envuelva a todo, y luego especificar ese uso específico en un template de formularios? Porque por ejemplo, hoy la ficha aclara que los formularios usan ese componente cuando tienen de 3 a 5 pasos, sin embargo en la sección de malas prácticas dice que se pueden utilizar en procesos de hasta 6 pasos. Estaría bueno o explicar dentro de la ficha cuál es la diferencia entre formulario y proceso o sólo mostrarlo de forma general y vincular a una futura plantilla de pasos de formularios. ¿Ya de por sí, bajo esta lógica, el componente debería llamarse de otra manera?


### ¿Cómo se ve la página del componente en el UI kit

![Image](https://github.com/user-attachments/assets/edd47803-ee9b-4c16-b69b-15a0f74137a2)

**Comment by marusaad** [comment]
- Se corrigió la plantilla de variantes del componente en el UI Kit, ya que tenía por error información sobre Accesos. 
- Se cargaron las propiedades. 
- Se cambió el nombre de la propiedad de texto "Título" por "Nombre del paso" para que sea más explicativo. 



![Image](https://github.com/user-attachments/assets/e8cdedf4-537f-4609-914d-15f4b3579306)

**Comment by Diehault** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados
#311 

### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente se ajusta a la grilla 4px.
- [x] El componente tiene una medida definida para mobile, tablet y desktop.
- [x] El componente tiene una modulación definida para mobile, tablet y desktop.
- [x] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [x] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | Sumamos una variante tablet que ocupa el 100 % del dispositivo.
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado | El margen para desktop pasó 129px, coincidiendo con la grilla. 

## ✏️ Notas

- En general, el componente se adapta siempre al 100 % de la pantalla del dispositivo y cambian los márgenes según el breakpoint.

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados 
#300 #309 

### Qué
Actualizar los estilos de color del componente aplicando las variables correspondientes a la v2 de Obelisco.

### Por qué
Porque posiciona al sistema en un nivel de calidad superior al cumplir con los criterios de accesibilidad de la WCAG, y facilita
la adopción, la personalización y la escalabilidad a nivel global.

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [x] El componente aplica las variables semánticas y funcionales para los elementos del mismo.
- [x] El componente cumple con los criterios de contraste y legibilidad de la WCAG (Criterios de accesibilidad AAA)


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | 
Arreglado | 
Eliminado | 
Obsoleto | 
Cambiado |  Se actualizó el color del componente con la nueva paleta de colores.

## ✏️ Notas
Actualizamos los colores de la plantilla del componente con la nueva colección de variables.
