### ISSUE TITLE
Buscador general

### ISSUE THREAD

**Issue by marusaad** [gcba/estandares#334]
# Buscador general

**Nombre en Obelisco**
Buscador general

**Tipo de componente**
Organismo

**Referencias de Bootstrap**
No hay

**¿Qué tenemos en Obelisco actualmente?**
Sólo UI Kit

**Usos en BA**
[Home WBA](www.buenosaires.gob.ar)

**Detalles**
Este componente se utiliza en la sección hero de la Home de WBA. Se diseñó como un buscador de autocomplete, que al ingresar el texto despliega diferentes tipos de opciones como trámites, funcionarios y áreas o programas. Actualmente, en la Home no tiene esa funcionalidad, se condice más con el funcionamiento del buscador de formulrarios donde se tipea el texto de búsqueda y al clickear redirige a una página de resultados, sin mostrar opciones previamente. 

Observamos que hay webs por fuera de buenosaires que dotaron de la funcionalidad prevista al buscador. 
En cuanto a documentación, el organismo no se encuentra en Storybook ni tiene ficha en estándares.

**Comment by marusaad** [comment]
¡Hola! 👩‍💻

Actualizamos los estilos tipográficos del componente y realizamos una revisión ágil. 

### ¿Qué hicimos?
- Actualizamos los estilos de texto en base a la nueva escala tipográfica.
- Trajimos los íconos custom de la page de tipografía a la page del componente como componentes base. 
- Incorporamos la nueva plantilla de componentes determinando los componentes base y las variantes. Se establecieron tres componentes base: _.Ítems-Predictivos_, _.Íconos-BA_ e _.Íconos-Representantes_.
- Se ordenaron y nomenclaron layers y propiedades.
- Colocamos al componente como "en revisión". 

### Evolutivos
Necesitamos realizar un análisis más profundo del componente actual. El componente se diseñó en base a una posible funcionalidad que hoy no está implementada en el buscador de la Home. En cuanto a páginas dentro y fuera de WBA, vemos que hay algunos sitios que copian el componente sin tener instalada la librería de Obelisco y le dan funcionalidad. Un claro ejemplo es [IDECBA](https://www.estadisticaciudad.gob.ar/eyc/) que si bien utiliza Obelisco, toma los estilos del buscador y adiciona las funcionalidades que hacen sentido en base al diseño. 

A su vez, no está disponible actualmente en Storybook, ni tampoco tiene ficha en Estándares. Es necesario alinearnos con desarrollo en este tema. 

Entendiendo que está la oportunidad del rediseño de la home, sería óptimo revisar el componente. 

 ### ¿Cómo se ve la página del componente en el UI Kit?

![Image](https://github.com/user-attachments/assets/de04aaca-301d-4391-ba54-a6850b0f318c)

**Comment by NicoAltamirano** [comment]
# 📢 Nuevo requerimiento

### Issues relacionados


### Qué
Actualizar el componente según el nuevo estilo de grillas de la v.2 de Obelisco. 

### Por qué
Para estandarizar tamaños, modulación y visualizaciones de todos los componentes. 

### Quién lo va a trabajar
Diseñadores

### Quién lo va a revisar
PM + SGOs 

### Criterios de aceptación

- [ ] El componente se ajusta a la grilla 4px.
- [ ] El componente tiene una medida definida para mobile, tablet y desktop.
- [ ] El componente tiene una modulación definida para mobile, tablet y desktop.
- [ ] El componente tiene su handoff para desarrollo y está marcado como ready for dev.
- [ ] El componente está documentado. 


## 🕰️ Changelog
CHANGELOG | Descripción
-- | --
Agregado | -
Arreglado | -
Eliminado | -
Obsoleto | -
Cambiado | **Se ajustó el ancho del componente para mobile, tablet y desktop.** # En desktop pasa a ocupa 8 columnas de ancho. # En tablet ocupa el 100% de las columnas. # En mobile ocupa el 100% de las columnas. 

## ✏️ Notas

- **[EV]**: Ver mejoras en este componente a nivel accesibilidad, usabilidad y construcción en Figma
