### ISSUE TITLE
Armar el componente listas y tablas

### ISSUE THREAD

**Issue by aloyber** [gcba/estandares#34]

**Comment by aloyber** [comment]
Avances del componente de Lista hasta el 07/07/2020
[Lista.pdf](https://github.com/gcba/estandares/files/4891391/Lista.pdf)

**Comment by aloyber** [comment]
Componente de tabla hasta el 16/07/2020
[Tablas-Obelisco.pdf](https://github.com/gcba/estandares/files/4934014/Tablas-Obelisco.pdf)

**Comment by aloyber** [comment]
Para página de libro en v2:

- Utilizar el hover en las diferentes secciones de la misma manera
- Probar el título alineado a la izquierda en la grilla

Para listas en v2:

- Utilizar el hover sin borde

@Fcunsolo

**Comment by aloyber** [comment]
> Componente de tabla hasta el 16/07/2020
> [Tablas-Obelisco.pdf](https://github.com/gcba/estandares/files/4934014/Tablas-Obelisco.pdf)
> @Vpappacena

Se sube actualizada el componente de tabla hasta el 17/07/2020
[Tablas.pdf](https://github.com/gcba/estandares/files/4938830/Tablas.pdf)

**Comment by aloyber** [comment]
> Para página de libro:
> 
> * Utilizar el hover en las diferentes secciones de la misma manera
> * Probar el título alineado a la izquierda en la grilla
> 
> Para listas:
> 
> * Utilizar el hover sin borde
> 
> @Fcunsolo

V1 actualizada para listas y página de libro
[Listas.pdf](https://github.com/gcba/estandares/files/4939332/Listas.pdf)

**Comment by julianrod** [comment]
El último ejemplo de todos los del PDF no me termina de cerrar... Si estoy dentro del libro "nuevo protocolo", dentro de la página "locales y comercios" y leyendo la subpágina "locales gastronómicos", siempre se debe notar claramente esa jerarquía... creo que visualmente no se termina de ver bien el caminito... que "locales y comercios" no tiene el énfasis suficiente.

**Comment by Vpappacena** [comment]
@aloyber @Fcunsolo , avancemos con propuestas en un contexto de uso y ver la versión Mobile, para ajustar la V1 de este componente

**Comment by aloyber** [comment]
Adjunto actualización de página de libro
@Vpappacena @Fcunsolo 
[Listas y tablas.pdf](https://github.com/gcba/estandares/files/5076635/Listas.y.tablas.pdf)
