### ISSUE TITLE
Armar el componente Modals

### ISSUE THREAD

**Issue by aloyber** [gcba/estandares#35]

**Comment by aloyber** [comment]
Dejo la primer versión del componente.
[Modal.pdf](https://github.com/gcba/estandares/files/4938378/Modal.pdf)
@Vpappacena

**Comment by julianrod** [comment]
plantearía cómo se vería un modal sin título, y quizás con una imagen de fondo (o color pleno), teniendo en cuenta que muchas veces se usan para anuncios promocionales de algún tipo.

**Comment by Vpappacena** [comment]
@julianrod  , hola Juli  a que producto digital de GCBA haces referencia para poder plantear la alternativa de uso ?

**Comment by julianrod** [comment]
No lo vi en ninguna web de gobierno.

Fijate el "Large box banner" de esta web de ejemplos: http://preview.codecanyon.net/item/bootstrap-4-modal-responsive-jquery-plugin/full_screen_preview/22396348?_ga=2.95629343.2019423404.1563336641-1696302010.1563199724?ref=puikinsh

**Comment by nirougi** [comment]
¿Queremos fomentar el uso de modals como banners completamente bloqueantes?
[La biblia](https://www.nngroup.com/articles/popups/) dice que no es muy buena idea.

Desde mi punto de vista el modal debería estar limitado a cambios de foco en el contenido **después de una interacción del usuario**. Hay tanto mal uso de este componente en general, desde el punto de vista de UX, que mucha gente ya lo cierra antes de leer cualquier cosa si se le aparece de la nada.

Para este componente estaría bueno plantear los casos en forma de historias de usuario con lo que entendemos que queremos solucionar.

De la referencia de arriba:
> People have grown accustomed to seeing premature popups on websites and usually ignore them or immediately look for the fastest means by which to close the popup to return to their task. Popups that appear before the page loads make the site look desperate and the user experience feel frantic. Additionally, sites who fail to recognize these facts risk low rankings in search-engine results as Google penalizes sites that use practices which make content less accessible to users, especially on mobile.

**Comment by julianrod** [comment]
Tenés razón. Vamos por ese lado.

Yo lo pensé por las apps de gobierno en las que nos solicitaron incorporar popups sobre coronavirus... ¿Qué haríamos en esos casos?

**Comment by nirougi** [comment]
Me parece que usando [alertas](/gcba/estandares/issues/22) tiene más sentido.

**Comment by julianrod** [comment]
OK. Después deberemos contemplar el caso de las aplicaciones móviles, y si las alertas se destacan lo suficiente cuando se quiere transmitir un mensaje de tal importancia. Pero para la v1 estamos bien.
