### ISSUE TITLE
Armar componente barra de progreso

### ISSUE THREAD

**Issue by aloyber** [gcba/estandares#36]
https://github.com/gcba/estandares/issues/33

**Comment by Fcunsolo** [comment]
[Pendiente revisión]
Comparto boceto de componente Barras de Progreso.

@aloyber @mathiassassone1 @Vpappacena 
[BARRAS-DE-PROGRESO-20200717.pdf](https://github.com/gcba/estandares/files/4939578/BARRAS-DE-PROGRESO-20200717.pdf)

**Comment by Jinik** [comment]
¿Cuál sería un caso de uso para esta barra?
Lo veo muy similar al stepper y no termino de entenderlo.

**Comment by Vpappacena** [comment]
> ¿Cuál sería un caso de uso para esta barra? 
> Lo veo muy similar al paso a paso y no termino de entenderlo.

El objetivo es trabajar un componente diferente al del paso a paso para visualizar por ejemplo el estado de un trámite o solicitud realizada por un ciudadano en la plataforma de atención.

**Comment by Jinik** [comment]
Ahh, entiendo.
Lo veo muy específico como para una primera versión igual.

**Comment by Vpappacena** [comment]
@aloyber @Fcunsolo,  revisemos al morfología de la barra de progreso , ya que sera un componente separado del paso a paso definido.

**Comment by Vpappacena** [comment]
@Fcunsolo  , subis la última versión de barra de progreso que vimos el viernes para pasarle a @ghoyos95 . 
Gracias :)

**Comment by mathiassassone1** [comment]
@Vpappacena @ghoyos95 

Dejo versiones de Barra de progres y Stepper.

[Stepper y Barra de progreso.pdf](https://github.com/gcba/estandares/files/5293882/Stepper.y.Barra.de.progreso.pdf)

**Comment by nirougi** [comment]
@mathiassassone1 ¿Para mobile cómo debería ser?
Veo solo la versión desktop y algo que habíamos barajado el viernes era si debería estar la lista completa o el paso actual solamente, entendiendo que el stepper es complejo distribuirlo con los diferentes pasos del formulario.

**Comment by Fcunsolo** [comment]
@Vpappacena @nirougi @aloyber @mathiassassone1 

Reabro Issue con la actualización del componente "Barra de progreso (Desktop / mobile)" para la V1 de Obelisco, según las últimas mesas de trabajo del equipo de experiencia.

- Se definió que el componente debía percibirse distinto que un "stepper" ya que su uso y función son distintos. El separarlos funcional como morfológicamente, hará que se defina con mayor certeza qué componente debe usarse en cada caso.
- Se definió que el componente "barra de progreso" debía tener una jerarquía mucho menor a la propuesta en versiones anteriores (semejante al stepper) dado que solo es un componente de status, y debe convivir con otros elementos informativos de la interfaz. 
-Se definió una tipología vertical en todos los casos (desktop/mobile) para contemplar cualquier tipo de longitud de información sin que el componente colapse, genere saltos de línea y se contamine visualmente.
- Se procuró dejar visible solo aquellos elementos que indiquen estado y ubicación del usuario en el proceso, con la posibilidad de mostrar más detalles con el botón link "más detalles / menos detalles".

Gracias!
[Barra de progreso.pdf](https://github.com/gcba/estandares/files/5336542/Barra.de.progreso.pdf)
