### ISSUE TITLE
Paginación

### ISSUE THREAD

**Issue by nirougi** [gcba/estandares#37]
Considero que la paginación también debería estar en la primer versión de componentes, ya que es un recurso bastante usado en general y que permite tanto en listados como tablas resolver el problema de tener demasiada información que mostrar.

**Comment by Jinik** [comment]
¿Qué te parece @Vpappacena?

**Comment by Vpappacena** [comment]
@mathiassassone1 - subir el caso de paginación. 

@Fcunsolo @aloyber , ver si se ajusta la navegación dela web de estandares a este caso

**Comment by mathiassassone1** [comment]
@Vpappacena @nirougi @techlowiec @lautarorodriguez96 

Subo la primera versión de paginado.

[Paginado.pdf](https://github.com/gcba/estandares/files/5318264/Paginado.pdf)

**Comment by mathiassassone1** [comment]
@nirougi @techlowiec @lautarorodriguez96 

Dejo corrección de color en el componente.

[Paginado.pdf](https://github.com/gcba/estandares/files/5336119/Paginado.pdf)
