### ISSUE TITLE
Armar Ficha de Colapsables

### ISSUE THREAD

**Issue by aloyber** [gcba/estandares#38]
[https://github.com/gcba/estandares/issues/32](url)

Tener en cuenta algunos detalles que se agregan en la ficha deberían estar en esta tarea que define más cómo es y cómo debería comportarse.

Por ejemplo:
- La sección de estructura sirve más para que nosotros lo integremos al código que para el usuario que lo vaya a usar.
- La parte de tipografía igual, para la persona que lo vaya a usar no le modifica mucho el tipo y tamaño, se define en el código.
- Para la parte de accesibilidad igual, aunque sí tiene más sentido mencionarlo en la ficha como algo importante.

**Comment by aloyber** [comment]
Subo primer ficha de colapsables
[FICHA COLAPSABLES 24:07.pdf](https://github.com/gcba/estandares/files/4973234/FICHA.COLAPSABLES.24.07.pdf)

Falta agregar el HTML, si me podes dar una mano con eso @techlowiec genial
@Vpappacena @Jinik @victoriajustina

**Comment by nirougi** [comment]
Personalmente no soy muy fan de los colapsables. Generalmente veo más casos mal implementados que casos donde realmente mejora la experiencia.

Algunos comentarios de **¿Cuándo uso colapsables?**.
En el punto 2 no dejaría tanto a consideración el uso y el punto 3 me da un poco de miedo.
El punto 4, que habla de cuando hay poco espacio, me hace un poco de ruido. Generalmente las páginas se pueden extender infinito verticalmente. ¿cuál sería un caso de ejemplo?

Apuntaría a explicar que en un colapsable **no puede ir el contenido principal de una página**, sino textos accesorios que no sean de importancia para la mayoría de los usuarios. Hay que desalentar el uso para páginas de FAQ o similares.

Pensando principalmente en buenosaires.gob.ar, tendría en cuenta especificar que el contenido de la página siempre debe estar visible y jerarquizado con títulos. Si el contenido es muy largo, usar un índice al inicio con anclas.

Las secciones de Usabilidad y Accesibilidad tienen el mismo texto.
