### ISSUE TITLE
Versión 1.1 de botón.-

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#39]
- En la parte de botones secundarios, definiría que si hay mas de N botones (Creo que el máximo debería ser 4/5) considerar utilizar una lista con enlaces.
- A los enlaces tipo botón los veo muy similares a un enlace común, ¿qué diferencia hay? Entiendo que la gracia de un "botón tipo enlace" es tener un área de clic mayor, en algo que no llama tanto la atención.
- Al botón de éxito le agregaría el caso de acciones que agreguen alguna entidad en la aplicación. Está más orientado a un aplicación web o similar, no para BsAs.
Para los íconos, ¿por qué definimos ponerlos a la derecha? - A mi entender el ícono busca ayudar al usuario a identificar la acción del botón sin tener que leer. Al escanear de izquierda a derecha (en castellano) es más factible que del lado izquierdo se lo identifique antes. Material design no lo tiene escrito, pero en las especificaciones está del lado izquierdo.
- ¿Estamos dejando posibilidad de usar botones que solamente tengan ícono? Yo no estoy muy de acuerdo con esa idea, esta investigación tampoco, pero veo que en la parte de estructura hay un ejemplo. Les parece agregar escrito que no se puede?
- En accesibilidad, para los botones que no están escritos como <button> hay que definir el role=button y tabindex=0 para que se le pueda hacer foco. El aria-label es para agregar un texto extra que el lector va a decir pero no se ve, por ejemplo botones que solo tienen íconos. El aria-labelledby no aplica para botones creo, porque enlaza a otro elemento.
- ¿Vamos a dejar opción a que un boton tenga 2 líneas de texto? Desde le css se puede forzar a que siempre sea una, pero puede traer problemas. Si no lo forzamos, deberíamos tener un ejemplo en estructura para ver bien los espacios y especificar que no se recomienda.

**Comment by Vpappacena** [comment]
@Fcunsolo  @aloyber  @mathiassassone1  . retomar version 1.1 de boton

**Comment by aloyber** [comment]
Se reorganizaron los estados de los componentes principalmente en los botones pequeños y se mejoro el funcionamiento dentro del UI KIT.

Se agrego el botón fantasma:
- Este botón permite ejecutar acciones secundarias y no tiene el peso visual que tiene el botón secundario.
- Tiene un mejor funcionamiento utilizandolo dentro de diferentes componentes (como por ejemplo en tarjetas)

![Botones](https://user-images.githubusercontent.com/65788688/108250736-5c428200-7135-11eb-9608-a8841d2920d1.png)

**Comment by Vpappacena** [comment]
se agrego el boton con icono , el fantasma ya estaba . de dividio en botones primario , pequeños y grande . y los botones anchos fullwidth para mobile

**Comment by Vpappacena** [comment]
@mathiassassone1 @aloyber @SantiBugdadi , ajustar la ficha de adobe para poder materializar en obelisco
