### ISSUE TITLE
Barras de progreso

### ISSUE THREAD

**Issue by nirougi** [gcba/estandares#54]

**Comment by ghoyos95** [comment]
dejo el link al issue en estandares con [la definicion de progress bar](https://github.com/gcba/estandares/issues/36)

independientemente de que me está costando construir las historias de los componentes tal como se encuentra definido, quizás mañana en visibilidad podríamos conversar un poco más en detalle los casos de uso que podría llegar a tener el componente dentro de buenos aires web u otros activos, y la funcionalidad propia del componente. 

Comparto la opinion de que es muy similar a los stepper [definidos en controles de formulario ](https://github.com/gcba/estandares/issues/18), y quizas entender un poco mejor los casos de uso de progress bar (al menos yo no los tengo tan claros), nos podría servir para redefinir la funcionalidad y estructura de este componente de modo que se adapte mejor a la necesidad real, y quizás evitar tener 2 componentes similares. 

lo charlamos si les parece @nirougi @techlowiec

**Comment by ghoyos95** [comment]
estuve buscando sobre casos de uso actuales para progress bar, dejo link que quizas puede llegar a servir: 

https://www.xataka.com/aplicaciones/apps-webs-que-te-hacen-esperar-cuando-realidad-obtienen-resultados-instantes

**Comment by nirougi** [comment]
@ghoyos95 , totalmente de acuerdo con esto que marcas.
¿Creés que podes ver eso con @Vpappacena  y los chicos de diseño como para tener un mayor entendimiento y definir bien los casos?

**Comment by Vpappacena** [comment]
> @ghoyos95 , totalmente de acuerdo con esto que marcas.
> ¿Creés que podes ver eso con @Vpappacena y los chicos de diseño como para tener un mayor entendimiento y definir bien los casos?

@ghoyos95  juntemonos con @aloyber y @Fcunsolo y charlamos la diferencias para que se entiendan mejor las decisiones de diseño

**Comment by ghoyos95** [comment]
@Fcunsolo @aloyber avisenme cuando esten cerradas las nuevas definiciones y las repasamos!
