### ISSUE TITLE
Versión 1.1 de Alertas

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#58]
[https://github.com/gcba/estandares/issues/21](url)

Proxima etapa revisar:

 - Cierre de las alertas. ¿Cuándo se puede cerrar y cuándo no?
-  Alertas por tiempo. ¿Puede haber casos en el que las alertas aparezcan por "x" tiempo y se cierren solas?
- Hacer accesible el cierre. Que no solo esté el ícono de cerrar, sino también la palabra.

**Comment by Vpappacena** [comment]
@Fcunsolo @mathiassassone1 @aloyber , subir las nuevas definiciones de Alertas en relación a las acciones.  el título y bajada y los colores de fondos

**Comment by aloyber** [comment]
Nuevas definiciones de alertas:
- Todas las alertas se pueden cerrar menos la de advertencia. Esto es porque puede ocurrir que se le necesite brindar información al ciudadano de manera alarmante queremos asegurarnos que siempre se mantenga visible.
- Se modificó la manera en que se cierran y se accionan las alertas. Se crearon dos botones donde uno es una acción principal (opcional) y otro es el botón de cierre de la alerta (siempre se pone, excepto en alertas de advertencia).
- La alerta funciona en la grilla completa utilizando 12 columnas y se puede escalar a 8 columnas de ser necesario. El espacio de grupo de botones tiene como máximo una utilización de 4 columnas y una separación del texto de 24px.
- Se modificaron los títulos de las alertas. No tienen más títulos sino que se muestra un destacado al principio de cada oración (opcional) y despues se muestra la descripción de lo que la alerta quiere notificar.
- En mobile los botones se utilizan por debajo del texto.

![Alertas - desktop](https://user-images.githubusercontent.com/65788688/108249185-83984f80-7133-11eb-8164-50a6dd7e2ae9.png)
![Alertas - Mobile](https://user-images.githubusercontent.com/65788688/108249196-85faa980-7133-11eb-8571-1f0206fa6998.png)

**Comment by Vpappacena** [comment]
- Empezar a pensar conceptualmente si una alerta debería tener un botón de cerrar .  
- si debería llevar un botón ?  cuales son las acciones de una alerta?
- Cual es el concepto de alerta ?  un aviso o una notificación? como se diferencia ? 
- Construir una ficha detallaando comportamiento y uso del componente dentro de una pagina
@Fcunsolo @aloyber @mathiassassone1

**Comment by mathiassassone1** [comment]
@nirougi @techlowiec @lautarorodriguez96 

Dejamos los últimos cambios de las alertas

![Alertas - desktop](https://user-images.githubusercontent.com/65788456/112057751-760e2500-8b38-11eb-9766-c314b0f43e1d.png)
![Alertas - Mobile](https://user-images.githubusercontent.com/65788456/112057754-773f5200-8b38-11eb-8a81-637c85acee66.png)
