### ISSUE TITLE
Armar ficha de Modals

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#62]
[https://github.com/gcba/estandares/issues/35](url)

¿Queremos fomentar el uso de modals como banners completamente bloqueantes?
La biblia dice que no es muy buena idea.

Desde mi punto de vista el modal debería estar limitado a cambios de foco en el contenido después de una interacción del usuario. Hay tanto mal uso de este componente en general, desde el punto de vista de UX, que mucha gente ya lo cierra antes de leer cualquier cosa si se le aparece de la nada.

Para este componente estaría bueno plantear los casos en forma de historias de usuario con lo que entendemos que queremos solucionar.

De la referencia de arriba:

People have grown accustomed to seeing premature popups on websites and usually ignore them or immediately look for the fastest means by which to close the popup to return to their task. Popups that appear before the page loads make the site look desperate and the user experience feel frantic. Additionally, sites who fail to recognize these facts risk low rankings in search-engine results as Google penalizes sites that use practices which make content less accessible to users, especially on mobile.

**Comment by Vpappacena** [comment]
@mathiassassone1  ,  cuando puedas vemos que el faltaba ala ficha de modals en cuanto a imágenes para sumar y tipografías . @techlowiec

**Comment by mathiassassone1** [comment]
@techlowiec

OK, actualizada la ficha de Modal.

**Comment by nirougi** [comment]
@mathiassassone1 ¿Podemos agregar acá al link de las definiciones?

**Comment by mathiassassone1** [comment]
@nirougi dejo el link 

https://xd.adobe.com/view/b15aa7bf-9779-43ac-a85b-9d818c499c23-e409/screen/f8d8b11c-5341-4267-88fe-eac56d9b2039/
