### ISSUE TITLE
Versión 1.1 de listas

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#69]
[https://github.com/gcba/estandares/issues/34](url)

**Comment by Vpappacena** [comment]
Trabajar como es el estado activo de una categoría mas grande. Solo esta hecho con los item interno. @Fcunsolo

**Comment by Fcunsolo** [comment]
Comparto las modificaciones que aplicamos a las listas.
https://xd.adobe.com/view/c5e691f2-0643-4e9e-a769-f2252af77984-90b5/screen/13a11386-db64-4ee9-8d60-21f3ed80afa6/

Ahora, una categoría que anide a otras categorías puede contener información, por lo que generamos estilos correspondientes a los diferentes comportamientos:

- Categoría Nivel 1 (Seleccionada)
- Categoría Nivel 2 (Seleccionada)
- Categoría Nivel 2 (Cuando una de sus categorías anidadas está seleccionada)
- Categoría Nivel 2 (Hover cuando una de sus categorías anidadas está seleccionada)

@Vpappacena @nirougi @techlowiec

Gracias!
