### ISSUE TITLE
accesibilidad recursos para desarroladores

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#70]
Revisar con Manu: 

El objetivo es: listar  webs en a las que pueden obtenerse recursos orientados a desarrolladores. 
-https://github.com/dequelabs/axe-cli
-https://pa11y.org/
-https://github.com/dequelabs/react-axe
-https://www.ssa.gov/accessibility/andi/help/developerguide.html
-https://www.w3.org/TR/wai-aria-practices-1.1/
-https://inclusive-components.design/toggle-button/
-http://pauljadam.com/moderna11y/
-https://es.reactjs.org/docs/accessibility.html 
-https://www.google.com/intl/es/accessibility/for-developers/
- https://developer.android.com/guide/topics/ui/accessibility
- https://developer.mozilla.org/es/docs/Learn/Accessibility

**Comment by armenio-s** [comment]
@Vpappacena dejo comentarios

**Recursos para desarrolladores**
Los recursos para desarrolladores nos ayudarán a dar más herramientas para quien quiera utilizar obelisco para construir sus aplicaciones y cumplir con los estándares de accesibilidad. Llamamos recurso a toda aquella documentación que le permita al desarrollador construir su aplicación cumpliendo las normas de accesibilidad.

-¿Cómo lo implementamos? 
-¿Lo sumamos a la ficha? 
-¿Cómo hacemos para sumarlo y qué sumamos?
-¿Qué criterio utilizamos para definir qué contenido debemos utilizar y cuál no?
-¿Cuándo profundizamos sobre un tema? ¿Cuándo no?
-¿Cuándo deberíamos utilizar información externa y cuándo brindar información propia sobre accesibilidad?

Agregar ejemplo de enlaces externos para profundizar sobre el componente que se está describiendo (React)

Recursos:
 
**ANDI - Accessible Web Development Guide**
https://www.ssa.gov/accessibility/andi/help/developerguide.html
Documentación sobre cómo utilizar atributos aria, atributos de html y etiquetas HTML para hacer que el código sea reconocible por un lector.
 
**WAI-ARIA Authoring Practices 1.1 - W3C**
https://www.w3.org/TR/wai-aria-practices-1.1/
Bueno obvio, hay mucha info sobre componentes específicos y cómo hacerlos accesibles aún cuando sean dinámicos.
 
https://inclusive-components.design/#components
 
**Modern Web Accessibility with JavaScript & WAI-ARIA**
http://pauljadam.com/moderna11y/
 
**Accesibilidad - React**
https://es.reactjs.org/docs/accessibility.html
Brinda información sobre cumplimiento de estándares de accesibilidad utilizando la librería pero se apoya bastante en documentación externa (webAIM, W3C)
 
**Google y Mozilla:**
_Recursos para desarrolladores y editores – Google Accesibilidad_
https://www.google.com/intl/es/accessibility/for-developers/

_Build more accessible apps_
https://developer.android.com/guide/topics/ui/accessibility

_Accesibilidad - Aprende sobre desarrollo web | MDN_
https://developer.mozilla.org/es/docs/Learn/Accessibility
 
https://www.eniun.com/diseno-desarrollo-webs-accesibles-accesibilidad-web/#6_Tabla_de_puntos_de_verificacion
 
**Para investigar:** 
https://developer.paciellogroup.com/blog/2017/04/what-is-an-accessible-name/
