### ISSUE TITLE
web obelisco 

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#73]
Propuesta de primera versión de [estándares](https://xd.adobe.com/view/6dbfdecc-888f-4a2c-aec4-96a058e576de-38ec/)

**Comment by Vpappacena** [comment]
Subo primera versio de la web [web obelisco](https://xd.adobe.com/view/6dbfdecc-888f-4a2c-aec4-96a058e576de-38ec/)

**Comment by Vpappacena** [comment]
@Fcunsolo, cuando puedas subís la versión del viernes 25/9

**Comment by Vpappacena** [comment]
Dejo la lista de elementos de lo que se charlo el viernes para ajustar entre el lunes y martes:

- Anclas: ¿Hacemos el componentes?¿Salimos con listas simples?¿Cual sera el estándar de palabras por ancla?
-Miga de pan: ¿Será el del componente defino?¿Se modifica en mobile, como funcionaría?
-La navegación de la web de estandar 
----------------------------

Si me falta algun punto sumemoslo a este issu @nirougi @Fcunsolo @mathiassassone1 @aloyber @techlowiec @lautarorodriguez96

**Comment by Fcunsolo** [comment]
> @Fcunsolo, cuando puedas subís la versión del viernes 25/9

Comparto versión Landing versión Desktop y Mobile compartida en la reunión (25/9)
https://xd.adobe.com/view/cebd49c1-712a-461b-800f-ad7f2f3ef588-9bee/

Gracias!

**Comment by nirougi** [comment]
No me carga la página, queda con el spinner todo el tiempo.
¿Hay que estar logeado o algo así?

**Comment by techlowiec** [comment]
Acabo de abirirlo y me carga normal con ese mismo link. No hay necesidad de estar logueado -recién probé en incógnito-.

**Comment by Vpappacena** [comment]
https://xd.adobe.com/view/66c6797a-d01f-45a2-b33e-38b9ea3b34a7-3395/screen/3f905914-6347-4416-9173-001a6187178a - V2 de la web con las diferentes paginas

**Comment by nirougi** [comment]
Holis, veo que agregaron una parte de historias con contenido más editorializado sobre el proyecto o algunos casos de éxito.
¿Cuál es el objetivo que pensaron para estos contenidos?
Personalmente no sé si eso debería estar en la web del estándar. Si bien me parece bien contarlo, creo que es parte de lo que debería estar en la web de Drupal sobre el proyecto.

No solo por lo técnico, ya que drupal está mejor armado para ese tipo de contenidos, sino también desde el lado conceptual, para tener la info más general, dura y útil en github y el proyecto + el por qué en buenos aires.

**Comment by Vpappacena** [comment]
[Sumo la sección de herramientas y recursos ](https://xd.adobe.com/view/af26b65d-104b-460f-b475-92e21256f7fc-fa75/)

**Comment by Vpappacena** [comment]
@nirougi  te paso [https://xd.adobe.com/view/316a3509-b144-4290-815d-43120d4620e2-6439/](guía de estilos)

**Comment by Vpappacena** [comment]
@nirougi  , el correo de la home es experienciadigital@buenosaires.gob.ar

**Comment by Vpappacena** [comment]
dejo el interactivo de citas @nirougi 
https://xd.adobe.com/view/d3506a4a-36f8-41e0-8e7a-f58277d57c88-8603/specs/
Cita
Ocupan 6 columnas, centradas
En Subtitulo 2, Italica.

**Comment by Vpappacena** [comment]
[Uploading Cita(1).pdf…]()

**Comment by Vpappacena** [comment]
https://xd.adobe.com/view/b745e134-4670-402d-a81a-72bb6cdd96cd-e216/ -  la sección e nuestras historias

**Comment by Vpappacena** [comment]
https://xd.adobe.com/view/b745e134-4670-402d-a81a-72bb6cdd96cd-e216/screen/25230f48-c98b-4df5-ab97-0a7c87fc1009

**Comment by mathiassassone1** [comment]
Componentes

https://xd.adobe.com/view/b15aa7bf-9779-43ac-a85b-9d818c499c23-e409/screen/5d9607f8-35c2-40dd-942f-3b8e24eefd43/

**Comment by Vpappacena** [comment]
comparto los ajustes para la home de obelisco https://xd.adobe.com/view/def047d0-897f-4589-96dc-d1092cd8dc4d-8ba3/

**Comment by Vpappacena** [comment]
@Fcunsolo  @mathiassassone1 @techlowiec @aloyber 
¿Cómo impacta nuestro trabajo?

ajustar la respuesta apuntando más a la expectativas de impacto

**Comment by nirougi** [comment]
@Vpappacena ¿Podemos cerrar este issue que se hizo eterno e ir armando uno para cada cosa nueva?
