### ISSUE TITLE
Header - Footer

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#74]
Armar el footer y  header para productos digitales de gobierno.

- Subir el header y footer de BA
- construir Header y Footer  para productos digitales: 
 Va haber solo un modelo? o más? como sera el estandar

**Comment by Fcunsolo** [comment]
_[Pendiente revisión]_

Comparto propuesta Header / Footer (Desktop y Mobile)

La idea es que **toda página dentro de buenosaires.gob.ar tenga el header y footer completo insitucional** (ambos con logos BA y Ciudad). 
Para **páginas fuera de buenosaires.gob.ar se proponen header y footer alternativos y customizables** según las necesidades del área (en cuanto a información). El header alternativo puede tener solo el logo BA y nombre del área. El footer alternativo debe contener el logo BA y Ciudad)

https://xd.adobe.com/view/67212fdb-cb63-45c8-bcf2-c5de74095338-3272/

Gracias!
