### ISSUE TITLE
Armar Ficha modelo de botón

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#8]
[https://github.com/gcba/estandares/issues/29](url)

Construir una ficha con el caso "Componente Botón"

La estructura de la ficha:
 - [x] definición del elemento
- [x] código
- [x] ¿Cómo funciona?
- [x] ¿Cómo se usa?
- [x] Orden
- [x] Alineación
- [x] Estados del Botón
- [x] Tipos de Botón
- [x] Tipografia
- [x] Estructura

**Comment by ghoyos95** [comment]
@mejiamarce sumar link de adobe para pasar a vicky 

Devolución del viernes 12.06: 
- Definir ajustes sobre el color del contorno de botón y si seguimos utilizando botones secundarios en gris u otra alternativa.
- Pensar si hay una mejor forma de especificar cuando es de éxito y cuando no un botón

**Comment by aloyber** [comment]
Adjunto una primer versión de la ficha de los botones

[FICHA 1 - BOTONES.pdf](https://github.com/gcba/estandares/files/4794835/FICHA.1.-.BOTONES.pdf)
@Vpappacena @ghoyos95

**Comment by ghoyos95** [comment]
@victoriajustina necesitamos que descarguen el pdf que subió Ari con la ficha modelo, y ustedes, en un documento aparte, hagan una revisión con el detalle de los puntos que consideran destacar/agregar en cuanto a: 
- Tono y voz
- Imágenes 

Una vez finalizada la revisión, necesitaríamos que suban el doc a este hilo y luego hacemos una puesta en común entre todos.

**Comment by victoriajustina** [comment]
@aloyber, @ghoyos95, @Vpappacena les dejo por acá la primera parte de las correcciones de la ficha modelo de un componente. Para que se den una idea, hice corrección de estilo y gramatical y en algunas partes enriquecí un poco el texto. 

Las cuestiones de tono y voz del mensaje también las tuve en cuenta. 

No me metí con las imágenes porque considero que es una cuestión más de diseño. 

Para la revisión final por favor banquen a que tenga lista la segunda parte.
[Correcciones Ficha Botones (parte 1).pdf](https://github.com/gcba/estandares/files/4838816/Correcciones.Ficha.Botones.parte.1.pdf)

**Comment by victoriajustina** [comment]
Hola @aloyber, @ghoyos95, @Vpappacena les dejo el pdf con la corrección terminada de esta primera ficha modelo. 

Me avisan  cualquier cosa.  

[Correcciones Ficha Botones (Final).pdf](https://github.com/gcba/estandares/files/4859121/Correcciones.Ficha.Botones.Final.pdf)

**Comment by aloyber** [comment]
@victoriajustina Subo ficha actualizada
En cuanto a la explicación sobre los estados de los botones, no sé si agregar cuando se produce cada estado o ya queda explícito por el nombre de cada uno. Esto lo podemos revisar..
[FICHA BOTONES 24:07.pdf](https://github.com/gcba/estandares/files/4973142/FICHA.BOTONES.24.07.pdf)

En breve seguramente agreguemos a la ficha un Ghost button, funcionalidad:

- Se utilizarán en cards principalmente cuando haya más de una acción 
- Cuando haya varias cards repitiendo la misma acción.

@Vpappacena @Fcunsolo @Jinik

**Comment by nirougi** [comment]
Van algunos comentarios:

- En la parte de **botones secundarios**, definiría que si hay mas de N botones (Creo que el máximo debería ser 4/5) considerar utilizar una lista con enlaces.
- A los **enlaces tipo botón** los veo muy similares a un enlace común, ¿qué diferencia hay? Entiendo que la gracia de un "botón tipo enlace" es tener un área de clic mayor, en algo que no llama tanto la atención.
- Al **botón de éxito** le agregaría el caso de acciones que agreguen alguna entidad en la aplicación. Está más orientado a un aplicación web o similar, no para BsAs.
- Para los **íconos**, ¿por qué definimos ponerlos a la derecha? A mi entender el ícono busca ayudar al usuario a identificar la acción del botón sin tener que leer. Al [escanear de izquierda a derecha](https://www.nngroup.com/articles/text-scanning-patterns-eyetracking/) (en castellano) es más factible que del lado izquierdo se lo identifique antes. Material design no lo tiene escrito, pero [en las especificaciones](https://material.io/components/buttons#specs) está del lado izquierdo.
- ¿Estamos dejando posibilidad de usar botones que solamente tengan ícono? Yo no estoy muy de acuerdo con esa idea, [esta investigación tampoco](https://www.nngroup.com/articles/icon-usability/), pero veo que en la parte de estructura hay un ejemplo. Les parece agregar escrito que no se puede?
- En **accesibilidad**, para los botones que no están escritos como `<button>` hay que definir el `role=button` y `tabindex=0` para que se le pueda hacer foco. El `aria-label` es para agregar un texto extra que el lector va a decir pero no se ve, por ejemplo botones que solo tienen íconos. El `aria-labelledby` no aplica para botones creo, porque enlaza a otro elemento.
- ¿Vamos a dejar opción a que un boton tenga 2 líneas de texto? Desde le css se puede forzar a que siempre sea una, pero puede traer problemas. Si no lo forzamos, deberíamos tener un ejemplo en estructura para ver bien los espacios y especificar que no se recomienda.
