### ISSUE TITLE
Preguntas_ fichas

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#86]
Leer la fichas publicada y generar un doc con las preguntas que surgen para consultar y ver como avanzar

**Comment by Vpappacena** [comment]
@ armenio-s compartamos el doc con las preguntas sobre la fichas para poder ir avanzando. :)

**Comment by armenio-s** [comment]
@Vpappacena dejo comentarios

**Ver también los recursos para los desarrolladores y cómo estos pueden aportar a ayudar al desarrollador a hacer que los componentes sean accesibles aún cuando se vuelvan de contenido dinámico.**

-Estamos probando los componentes para ver si un lector los interpreta correctamente?
-Se prueba la navegación por teclado y el foco del componente?
-Cómo hacemos para que el componente reaccione como se debe a una herramienta de asistencia?
-Cómo lo vamos a probar?
-Qué herramientas o información vamos a brindar en la ficha en cuanto a accesibilidad?

**Código-Atributos-Links.** 
Le damos el HTML base pero no le decimos cómo hacerlo accesible. Más allá de que utiliza la semántica, el contenido dinámico a veces aparece o desaparece sin que el usuario note los cambios con una herramienta como un lector, sobre todo en frameworks basados en componentes donde no se linkea de una página a la otra sino que se actualizan los componentes por separado. (Ver react como ejemplo)

Tal vez se podrían hacer algunos ajustes.
Por alguna razón el menú se muestra más a la derecha de lo que se ve el div al inspeccionar el código. También estaría bueno que el menú quede fijo al scrollear para no perderlo de vista, ya que las fichas son muy largas y puede se medio tedioso tener que scrollear hacia arriba para ir a otro lado. Un botón flotante que permita “ir arriba”, también puede servir.

En el caso de los botones, cuando pasan a una segunda fila, se pegan al top
En los textos se ven algunos errores de ortografía o redacción que se podrían ir revisando para corregirlos

El footer cuando hay poco o nada de contenido, no queda pegado al fondo
