### ISSUE TITLE
Miga pan

### ISSUE THREAD

**Issue by Vpappacena** [gcba/estandares#97]
https://github.com/gcba/estandares/issues/17

Queda pendiente revisar la propuesta en mobile de como se ve y se comporta el componentes

**Comment by mathiassassone1** [comment]
Para Mobile se decide mostrar siempre solo 2 items, el inicio, Buenos Aires como pagina de home, y la página anterior a la que actualmente se encuentre.

El tamaño de la tipografía es de 13 px.

Si el texto excede el limite de columna, se colapsa a puntos suspensivos.

https://xd.adobe.com/view/c5e691f2-0643-4e9e-a769-f2252af77984-90b5/screen/a6f3d369-592a-41a5-b1ba-e5f8e43d5e46/
